### ISSUE TITLE
403 error with provisioning request for Learning Pathways

### ISSUE THREAD

**Issue by Lee-Myhre** [SharePoint/sp-provisioning-service#102]
Hi,

I've had 2 provisioning requests for the Learning Pathways solution fail, both with a 403 error. I tried before and had the "appCatalog permissions" issue, but have had an app catalog with this user having global-admin access as well as both Site Collection Admin and Site Owner permissions to the App Catalog for years already since we used this tenant for 2013-style Add-In development back before dev tenants were a thing.

 Below is the content of the most recent error email I received:

Your request to provision "Microsoft 365 learning pathways"  template failed! Please  report the issue here providing the following provisioning action correlation ID: 406b1b5d-a2b3-4681-985d-4aa6edaad8be !
--
Please provide use feedback around your used template or the service in general by using our feedback form  . Thank you for your input advance.

Exception: The remote server returned an error: (403) Forbidden.
Provisioning action correlation ID: 406b1b5d-a2b3-4681-985d-4aa6edaad8be

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
