### ISSUE TITLE
Learning Pathways provisioning failed with ID f22b56c3-9252-4550-9ce7-9382ea13efeb 

### ISSUE THREAD

**Issue by NikNau** [SharePoint/sp-provisioning-service#103]

**Comment by NikNau** [comment]
Tried again - failed again with ID 83ee8729-7d67-44f1-b8cc-cb709d3f2a18 ! 
The other solution of SharePoint Starter Kit was deployed fine at the same time.

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
