### ISSUE TITLE
Failed to Provision Microsoft 365 Learning Pathways

### ISSUE THREAD

**Issue by Shaun-J** [SharePoint/sp-provisioning-service#113]
Your request to provision"Microsoft 365 learning pathways"template failed!Please report the issue here providing the following provisioning action correlation ID: 6e227202-71c3-42d9-9ce7-79c4e2643fef !
--
Please provide use feedback around your used template or the service in general by using our feedback form . Thank you for your input advance.

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
