### ISSUE TITLE
Your request to provision “Microsoft 365 Learning Pathways” template failed!

### ISSUE THREAD

**Issue by craigwoodburn** [SharePoint/sp-provisioning-service#115]
Your request to provision
"Microsoft 365 learning pathways"
template failed!
Please report the issue here providing the following provisioning action correlation ID: efb82d64-0bbf-4b09-b575-c9586fde2fab !

**Comment by s60aun** [comment]
I am also getting this issue on our tenant.  Any ideas?

Your request to provision
"Microsoft 365 learning pathways" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: 75ffffd4-3758-4a6f-984a-3201568df59e !

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
