### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by jdonajkowski** [SharePoint/sp-provisioning-service#118]
correlation ID: 71bf8438-ea4e-4ef9-9d34-cec09cd35325 ! 

and it keeps sending me the email over and over that it failed.

**Comment by lacastafiore** [comment]
correlation ID: f0f7e450-bbdc-4228-9187-1ed9a287cb32

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
