### ISSUE TITLE
Login Error unable to create site

### ISSUE THREAD

**Issue by ababinchak** [SharePoint/sp-provisioning-service#12]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

I'm unable to add the training solution to my tenant. I tried a few days ago and got the same error. The behavior is that after selecting add to Tenant it flips to an authentication screen then just site there and the screen flashes. If I back out I'm presented with the following error message.

There was an unexpected issue. Please try again after a while.
IDX21323: RequireNonce is '[PII is hidden]'. OpenIdConnectProtocolValidationContext.Nonce was null, OpenIdConnectProtocol.ValidatedIdToken.Payload.Nonce was not null. The nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'. Note if a 'nonce' is found it will be evaluated.

**Comment by PaoloPia** [comment]
Hi @ababinchak ,
I don't see any feedback on this topic. As such, I will close it. Feel free to write a comment if you are still experiencing the issue and you want me to re-open it. Thanks.
