### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways" template failed!

### ISSUE THREAD

**Issue by al-131168** [SharePoint/sp-provisioning-service#129]
Please report the issue here providing the following provisioning action correlation ID: 25f9ceea-d3af-489d-991b-25bdc40d4368 !

I deployed the microsoft learning pathways in our tenant and deleted the website again (because the site name was wrong). Afterwards I deployed it again with a new site name and then I got this message.

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
