### ISSUE TITLE
Installing in Vanity URL SPO environment

### ISSUE THREAD

**Issue by jrummer** [SharePoint/sp-provisioning-service#136]
Is there anyone in this community that can confirm that installing Learning Pathways in SPO with a vanity URL will not work?  I'm also curious if the manual install option can resolve this issue.  

I'm guessing that the code in the webpart is looking for onmicrosoft.

Thanks.

**Comment by PaoloPia** [comment]
Hi, vanity URLs are not supported by the Provisioning Service. Thanks.
