### ISSUE TITLE
Unexpected exception when provisioning the Custom Learning site

### ISSUE THREAD

**Issue by ChrispyBites** [SharePoint/sp-provisioning-service#14]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The, uh... the site provisions with all the content in it.

#### Observed Behavior

I attempted this once before and it went through fine but the provisioned site was devoid of content.  So I deleted the site I created the first time around, read a little more, realized we didn't have an app catalog site collection set up, so I did that.  I waited for 10 or 15 minutes until the app catalog site collection was up and running and then attempted to re-provision the custom learning site, and I got:

##Unfortunately, your request to provision "Custom Learning for Office 365" template failed.

Here is the exception that occurred:

`Type = System.FormatException Message = Expected hex 0x in '{0}'. Source = mscorlib TargetSite = Void SetFailure(ParseFailureKind, System.String, System.Object, System.String, System.Exception) StackTrace = at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException) at System.Guid.TryParseGuidWithHexPrefix(String guidString, GuidResult& result) at System.Guid.TryParseGuid(String g, GuidStyles flags, GuidResult& result) at System.Guid.Parse(String input) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectApplicationLifecycleManagement.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceSites.ProvisionObjects(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser tokenParser, ProvisioningTemplateApplyingInformation applyingInformation) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ProvisioningTemplateApplyingInformation provisioningInfo) at Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ProvisioningTemplateApplyingInformation applyingInformation) at SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__0.MoveNext() in C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line 337 HResult = -2146233033 `

PnP Correlation ID: 3fbaffe9-7cc3-4241-81b4-f04d40d7008a

#### Steps to Reproduce

I guess you can try everything I described above in the Observed Behavior section

**Comment by PaoloPia** [comment]
Hi @ChrispyBites ,
I don't see any feedback on this topic. As such, I will close it. Feel free to write a comment if you are still experiencing the issue and you want me to re-open it. Thanks.
