### ISSUE TITLE
 Your request to provision  "Microsoft 365 learning pathways"  template failed

### ISSUE THREAD

**Issue by kevmcdonk** [SharePoint/sp-provisioning-service#145]
Failed with Correlation ID:

9e1ce9a0-5174-4dfd-9dc5-783ab13dd9ca

**Comment by kevmcdonk** [comment]
Actually worked and I received the email later saying that it was successful. Not seen anything missing so far

**Comment by kevmcdonk** [comment]
Whoops, fat fingers, didn't mean to close. However, feel free to close if no further action needed.

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
