### ISSUE TITLE
"Microsoft 365 learning pathways"

### ISSUE THREAD

**Issue by robinricharddsouza** [SharePoint/sp-provisioning-service#146]
Your request to provision

"Microsoft 365 learning pathways"

template failed!

Please report the issue here providing the following provisioning action correlation ID: a58586ca-2d62-4836-99e3-379b69a89122 !

We have reported this to microsoft support but was advised this is outside of their scope and that you would be best to assist. Any guidance would be most appreciated.

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
