### ISSUE TITLE
Your request to provision "Human resources hub"  template failed!

### ISSUE THREAD

**Issue by kamilazet** [SharePoint/sp-provisioning-service#150]
provisioning action correlation ID: f1ef68d3-87d1-4f94-9668-51c496be895e

**Comment by PaoloPia** [comment]
Hi @kamilazet ,
In the email message that notified you about the failure, there should a text explaining the reason why it failed. Specifically, for this failed action, the exception is that you were already provisioning the same site with the same URL and we cannot provision the same site twice.
