### ISSUE TITLE
Your request to provision  "The Perspective"  template failed!

### ISSUE THREAD

**Issue by fpignalosa** [SharePoint/sp-provisioning-service#153]
correlation ID: 7477bba3-d930-4f30-87cf-5f8056fd1a22

**Comment by PaoloPia** [comment]
Hi @fpignalosa,
In the email message that notified you about the failure, there should a text explaining the reason why it failed. Specifically, for this failed action, the exception is the following one:

_The requested Communications Site at https://{tenant}.sharepoint.com/sites/{SiteURL} is in the Recycle Bin and cannot be created_

So you should empty the Site Collections Recycle Bin, or you should change the URL of the target site to create.

**Comment by fpignalosa** [comment]
thanks Paolo.
