### ISSUE TITLE
Your request to provision  "Global sales hub"  template failed!

### ISSUE THREAD

**Issue by fpignalosa** [SharePoint/sp-provisioning-service#155]
correlation ID: 62d8664a-74b8-4cdf-b7be-91818f911a03

**Comment by PaoloPia** [comment]
Hi @fpignalosa,
In the email message that notified you about the failure, there should a text explaining the reason why it failed. Specifically, for this failed action, the exception is the following one:

_The requested Communications Site at https://<tenant>.sharepoint.com/sites/<SiteUrl> is in the Recycle Bin and cannot be created_

So you should empty the Site Collections Recycle Bin, or you should change the URL of the target site to create.
