### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by pwfitzsimmons** [SharePoint/sp-provisioning-service#160]
Your request to provision
"Microsoft 365 learning pathways" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: 9275b32b-733f-428e-b9c2-566fc366aa8e !

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
