### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by phyberoptx** [SharePoint/sp-provisioning-service#173]
Please report the issue here providing the following provisioning action correlation ID: 7dcebb79-51a9-4863-a4d5-0fe8bd5ac121 ! 

Main page itself looks to have been created, but going to CustomLearningAdmin.aspx throws a 404 error.

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
