### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed! Please report the issue here providing the following provisioning action correlation ID: c82b10ef-1724-47fa-bca0-c23cb80e52a6 ! 

### ISSUE THREAD

**Issue by rbernsteinIIC** [SharePoint/sp-provisioning-service#177]
Provisioning action correlation ID: c82b10ef-1724-47fa-bca0-c23cb80e52a6 !

**Comment by rbernsteinIIC** [comment]
Provisioning action correlation ID: c82b10ef-1724-47fa-bca0-c23cb80e52a6 !

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
