### ISSUE TITLE
Issues with SharePoint Early provision sample content and structures

### ISSUE THREAD

**Issue by Surya-Ch** [SharePoint/sp-provisioning-service#18]
Issues with SharePoint Early provision sample content and structures . Please see attachments for complete details.
[SharePoint Online Provisioning Service.pdf](https://github.com/SharePoint/sp-dev-docs/files/3098163/SharePoint.Online.Provisioning.Service.pdf)
![1](https://user-images.githubusercontent.com/49786212/56424998-82b8dd00-6280-11e9-8796-3b196da13191.PNG)

**Comment by PaoloPia** [comment]
Hi @Surya-Ch,
Thanks for your feedback. Are you still experiencing this problem? We improved the check of pre-requisites and, if you don't have the AppCatalog in your tenant, you should see an explicit warning and you should not be able to provision the template. Please, let me know ...

**Comment by PaoloPia** [comment]
Hi @Surya-Ch ,
I don't see any reply on this thread, so I will close this item. If you are still experiencing the issue let me know and I will be more than happy to open it back. Thanks.
