### ISSUE TITLE
Request to provision "Microsoft 365 learning pathways" template failed

### ISSUE THREAD

**Issue by STETHE** [SharePoint/sp-provisioning-service#189]
Provisioning action correlation ID: 48dc8fbf-bb2e-446f-85c0-e1ca67f51e4b
Provisioning Status | Unfortunately your site provisioning at least partially failed!

No custom Theme selected.
Best regards
Stephan Theiss

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
