### ISSUE TITLE
Error: "Unfortunately your site provisioning at least partially failed!" when provisioning M365 Learning Pathways solutions

### ISSUE THREAD

**Issue by bhargavshukla** [SharePoint/sp-provisioning-service#193]
When I try to provision M365 Learning Pathways solution, I'm getting an error "Unfortunately your site provisioning at least partially failed!". This is happening across multiple Office 365 tenants, each logged in with global administrator to avoid any permissions issues.

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
