### ISSUE TITLE
 SharePoint PnP Provisioning Service

### ISSUE THREAD

**Issue by juliemturner** [SharePoint/sp-provisioning-service#20]
#### Category
- [ ] Question
- [ ] Typo
- [ x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

User @jharveysummit is reporting that the provisioning service indicates he has no tenant app catalog in the notification email, although they believe they do.  Ref: https://github.com/pnp/custom-learning-office-365/issues/44#issuecomment-486794925

#### Steps to Reproduce

I've attempted to use the service (as my subject line would suggest) w/ this link... https://aka.ms/CLO365. I get an e-mail saying "Unfortunately, request to provising "Custom learning for Office 365" template failed." If that same e-mail it states... "In order to provision the template you need to have an App Catalog in your tenant. Please create one, wait 30 mins, and try again" We already have one (see below). Please advise.

Thanks for your contribution! Sharing is caring.

**Comment by PaoloPia** [comment]
Hi @juliemturner,
Thanks for your feedback. As you know we improved quite a lot the validation controls for the AppCatalog. Is this still an open issue on your side or can I close it? Thanks.

**Comment by PaoloPia** [comment]
Hi @juliemturner,
I will close this item, because I assume you are not experiencing anymore the issue due to lack of replies here. If I'm wrong, just let me know and I will re-open it. Thanks.
