### ISSUE TITLE
SharePoint PnP Provisioning Service failed 

### ISSUE THREAD

**Issue by SankaAmarakoon** [SharePoint/sp-provisioning-service#201]
Tried to add new SharePoint template from https://lookbook.microsoft.com/ and provision failed.

Got below error, Please advice,

Your request to provision
"The Perspective"
template failed!
correlation ID: d4f7450d-7d7e-43e2-9c81-284ef138f09e

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
