### ISSUE TITLE
Provisioning failed

### ISSUE THREAD

**Issue by gophfy** [SharePoint/sp-provisioning-service#202]
Reporting an issue provisioning the Microsoft 365 Learning Pathways template.

Your request to provision "Microsoft 365 learning pathways" template failed!

Please report the issue here providing the following provisioning action correlation ID: a6add676-6398-40db-8f9a-a95f46bc8a42 !

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
