### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways" template failed

### ISSUE THREAD

**Issue by crdavidson77** [SharePoint/sp-provisioning-service#203]
Your request to provision
"Microsoft 365 learning pathways"
template failed!
Please report the issue here providing the following provisioning action correlation ID: 5b1290d3-3875-481a-b563-b4ac95c5c989 !

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
