### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by hanspettermalme** [SharePoint/sp-provisioning-service#212]
As instructed here is the correlation ID: 6c5e1315-4edf-4186-8329-d3d87ae5d0ce ! 

Hope there is an easy fix for this as we are very interested inn the product :) 

Regards 
Hans Petter

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
