### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways" template failed!

### ISSUE THREAD

**Issue by ldleasher** [SharePoint/sp-provisioning-service#216]
I was just watching the provisioning page and my Provisioning status changed from Provisioning.... at the bottom to:  "Unfortunately your site provisioning at least partially failed!"

I got this in the email as an update:

Your request to provision
"Microsoft 365 learning pathways" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: 5c2c3bf2-d229-471c-9984-3b77e8401978 ! 

I went to the site that was being provisioned and it looks ok so not sure what happen.  However, I have not tried to do anything with the page yet.

**Comment by PaoloPia** [comment]
Hi, Thanks for your comprehension. There was an issue that is now fixed.
