### ISSUE TITLE
The work @ contoso template provisioning is failed 

### ISSUE THREAD

**Issue by muges01** [SharePoint/sp-provisioning-service#22]
Hi @VesaJuvonen 

Thank you for the reply. I have try to recreate with totally new site but i'm getting the following error.

Type = System.Exception Message = {"DocumentsUrl":null,"ErrorMessage":null,"GroupId":"ab4315bf-6d77-4863-a304-65f5968724fc","SiteStatus":1,"SiteUrl":null} Source = OfficeDevPnP.Core TargetSite = Void MoveNext() StackTrace = at OfficeDevPnP.Core.Sites.SiteCollection.<CreateAsync>d__3.MoveNext() in C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Sites\SiteCollection.cs:line 256 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at OfficeDevPnP.Core.Sites.SiteCollection.Create(ClientContext clientContext, TeamSiteCollectionCreationInformation siteCollectionCreationInformation) in C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Sites\SiteCollection.cs:line 43 at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceSites.ProvisionObjects(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser tokenParser, ProvisioningTemplateApplyingInformation applyingInformation) in C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectHierarchySequenceSites.cs:line 59 at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ProvisioningTemplateApplyingInformation provisioningInfo) in C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line 207 at Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ProvisioningTemplateApplyingInformation applyingInformation) in C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\TenantExtensions.cs:line 42 at SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__2.MoveNext() in C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line 360 HResult = -2146233088

_Originally posted by @muges01 in https://github.com/SharePoint/sp-dev-docs/issues/3874#issuecomment-488795440_

**Comment by PaoloPia** [comment]
Hi @muges01,
Thanks for the feedback. Are you still experiencing this issue?

**Comment by PaoloPia** [comment]
Hi @muges01 ,
I don't see any reply on this thread, so I will close this item. If you are still experiencing the issue let me know and I will be more than happy to open it back. Thanks.

**Comment by muges01** [comment]
Hi @PaoloPia ,

I'm really sorry, i don't know how can i missed the email notification regarding your question on 5 Jun 2019.. I have tested and the issue is not there anymore.  Yes, this issue can be closed now.

Thank you @PaoloPia
