### ISSUE TITLE
M365 Learning Pathway Provisioning stuck at Validating URL

### ISSUE THREAD

**Issue by garimatewari17** [SharePoint/sp-provisioning-service#220]
M365 Learning Pathway Provisioning stuck at Validating URL . I checked the pre requisites and its all in place.
[M365 Learning Pathway error.txt](https://github.com/SharePoint/sp-provisioning-service/files/4503115/M365.Learning.Pathway.error.txt)

**Comment by garimatewari17** [comment]
Can someone look into this.

**Comment by PaoloPia** [comment]
Hi, Thanks for your comprehension. There was an issue that is now fixed.
