### ISSUE TITLE
Learning Pathways Provisioing Failed

### ISSUE THREAD

**Issue by Chiliyago** [SharePoint/sp-provisioning-service#229]
Please report the issue here providing the following provisioning action correlation ID: 1bcb207e-590d-4bec-b6ca-72fb157a916b !

**Comment by msolutionsplt** [comment]
Please report the issue here providing the following provisioning action correlation ID: c77293af-b0ac-4820-887e-6272bf5ff3f9 !

**Comment by PaoloPia** [comment]
Hi, Thanks for your comprehension. There was an issue that is now fixed.
