### ISSUE TITLE
Can we provision M365 Learning Pathway on Vanity domain URLs

### ISSUE THREAD

**Issue by garimatewari17** [SharePoint/sp-provisioning-service#233]
We are trying to provision Learning pathway on our domain and getting error.Can you confirm if we can provision M365 Learning Pathway on Vanity domain URLs

**Comment by PaoloPia** [comment]
Hi, Thanks for your comprehension. There was an issue that is now fixed. BTW, the M365 Learning Pathways template cannot be used on vanity URLs.
