### ISSUE TITLE
Unable to provision o365 learning pathways site

### ISSUE THREAD

**Issue by ram5555ster** [SharePoint/sp-provisioning-service#235]
I am trying to provision the o365 learning pathways site using the following solution page: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239

We have multi tenant SharePoint Online environment with custom domains. I get the below error message when i try provisioning the site. The error message says "Current site is not a tenant admin site" even though i logged in as tenant admin to the SP admin site . Can you please help me identify the problem?

![O365Learningpathwayserror](https://user-images.githubusercontent.com/31449895/87353579-141e0a00-c52b-11ea-84d4-dac847dfb548.JPG)

**Comment by PaoloPia** [comment]
Hi, custom domains/vanity URLs are not supported by the provisioning service.
