### ISSUE TITLE
Unable to provision o365 learning pathways

### ISSUE THREAD

**Issue by Nima0912** [SharePoint/sp-provisioning-service#236]
I have issue with provisioning.
after provisioning, i never received the email and the URL is not accessible and i cannot find the M365LP under Site Collections.

My account is Global administrator.
![image](https://user-images.githubusercontent.com/68592464/88152038-bdd45980-cc03-11ea-8df1-587d7c4ede84.png)

I created a App Catalog with the same account.
![image](https://user-images.githubusercontent.com/68592464/88046900-08e16480-cb51-11ea-96c1-00a901625dea.png)

I used the provisioning link.
![image](https://user-images.githubusercontent.com/68592464/88047133-6fff1900-cb51-11ea-86aa-378916cf82a1.png)

I watched this tutorial but i never get the permissions request windows.
https://www.youtube.com/watch?v=Rj3U6ds-x1c
![image](https://user-images.githubusercontent.com/68592464/88047894-a0938280-cb52-11ea-8896-5f1386d402d6.png)

**Comment by Dannyvzon** [comment]
Having the same issue!

**Comment by PaoloPia** [comment]
Hi, Thanks for your comprehension. There was an issue that is now fixed. Could you please try again? Thanks.

**Comment by Dannyvzon** [comment]
PaoloPia,

Working like a charm! Thnx

**Comment by Nima0912** [comment]
Your request to provision "Microsoft 365 learning pathways" template failed!
Please report the issue here providing the following provisioning action 
correlation ID: 9ebf5988-cce1-44c8-aba7-213b9b26ed64 !
