### ISSUE TITLE
request to provision "Microsoft 365 learning pathways"  template failed

### ISSUE THREAD

**Issue by AchimBossler** [SharePoint/sp-provisioning-service#239]
provisioning action correlation ID: dcb3df0b-8e1d-4476-82d6-dfac310b39ed

Thank you for any hints.

**Comment by PaoloPia** [comment]
Hi,
We're facing an issue, which we're working on. The functionality should be back soon. Sorry for any inconvenience.

**Comment by mabvill** [comment]
i have problem:  ID: cf928c74-32b4-4ddf-b28a-ca12072e2d79 !

**Comment by PaoloPia** [comment]
Hi, the service is now fully functional. However, it looks like you (@mabvill) targeted an already existing site with your provisioning, in fact, the exception related to your ID refers to a page Home.aspx which is a classic page, while was expected to be a modern page. Could you please try targeting a fresh new site (don't create it, just provide the URL to the service, which will create it for you). In case of any exception, please open a new issue. I'll close this one. Thanks.
