### ISSUE TITLE
SharePoint Online Provisioning Service -  Microsoft 365 learning pathways site

### ISSUE THREAD

**Issue by Tyr03** [SharePoint/sp-provisioning-service#24]
**Category**
- [ ]   Question
- [ ]   Typo
- [X]   Bug
- [ ]   Additional article idea

**Expected or Desired Behavior**
Site should be created as mentioned on the following link:
[https://provisioning.sharepointpnp.com/home/details?packageId=3df8bd55-b872-4c9d-88e3-6b2f05344239](url)

**Steps to Reproduce**
Go to https://provisioning.sharepointpnp.com/
Click on Solution then choose Microsoft 365 learning pathways template
Click Add to Tenant
Click Provision
Click Confirm in the pop-up confirmation screen
Wait for the email after the provision#### Submission Guidelines

I got the followling error message by email : 

SharePoint     Online Provisioning Service     Unfortunately, your     request to provision     "Custom     learning for Office 365"      template failed. | SharePoint     Online Provisioning Service     Unfortunately, your     request to provision     "Custom     learning for Office 365"      template failed.
-- | --
SharePoint     Online Provisioning Service     Unfortunately, your     request to provision     "Custom     learning for Office 365"      template failed.
 
Here is the exception that occurred:     Type = System.Net.WebException Message = The remote server     returned an error: (404) Not Found. Source = System Status = ProtocolError     Response = System.Net.HttpWebResponse TargetSite = System.Net.WebResponse     EndGetResponse(System.IAsyncResult) StackTrace = at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult     asyncResult) at     System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar,     Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean     requiresSynchronization) --- End of stack trace from previous location     where exception was thrown --- at     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at Microsoft.SharePoint.Client.SPWebRequestExecutor.<ExecuteAsync>d__0.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientContext.<GetFormDigestInfoPrivateAsync>d__b.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientContext.<EnsureFormDigestAsync>d__8.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientObjectExtensions.<EnsurePropertyImplementation>d__5`2.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientObjectExtensions.EnsureProperty[T,TResult](T     clientObject, Expression`1 propertySelector) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceSites.ProvisionObjects(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser     tokenParser, ProvisioningTemplateApplyingInformation applyingInformation)     at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation provisioningInfo) at Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation applyingInformation) at     SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__2.MoveNext()     in     C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line     389 HResult = -2146233079 | Here is the exception that occurred:     Type = System.Net.WebException Message = The remote server     returned an error: (404) Not Found. Source = System Status = ProtocolError     Response = System.Net.HttpWebResponse TargetSite = System.Net.WebResponse     EndGetResponse(System.IAsyncResult) StackTrace = at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult     asyncResult) at     System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar,     Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean     requiresSynchronization) --- End of stack trace from previous location     where exception was thrown --- at     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at Microsoft.SharePoint.Client.SPWebRequestExecutor.<ExecuteAsync>d__0.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientContext.<GetFormDigestInfoPrivateAsync>d__b.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientContext.<EnsureFormDigestAsync>d__8.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientObjectExtensions.<EnsurePropertyImplementation>d__5`2.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientObjectExtensions.EnsureProperty[T,TResult](T     clientObject, Expression`1 propertySelector) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceSites.ProvisionObjects(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser     tokenParser, ProvisioningTemplateApplyingInformation applyingInformation)     at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation provisioningInfo) at Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation applyingInformation) at     SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__2.MoveNext()     in     C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line     389 HResult = -2146233079
Here is the exception that occurred:     Type = System.Net.WebException Message = The remote server     returned an error: (404) Not Found. Source = System Status = ProtocolError     Response = System.Net.HttpWebResponse TargetSite = System.Net.WebResponse     EndGetResponse(System.IAsyncResult) StackTrace = at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult     asyncResult) at     System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar,     Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean     requiresSynchronization) --- End of stack trace from previous location     where exception was thrown --- at     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at Microsoft.SharePoint.Client.SPWebRequestExecutor.<ExecuteAsync>d__0.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientContext.<GetFormDigestInfoPrivateAsync>d__b.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientContext.<EnsureFormDigestAsync>d__8.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientObjectExtensions.<EnsurePropertyImplementation>d__5`2.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientObjectExtensions.EnsureProperty[T,TResult](T     clientObject, Expression`1 propertySelector) at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceSites.ProvisionObjects(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser     tokenParser, ProvisioningTemplateApplyingInformation applyingInformation)     at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation provisioningInfo) at Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation applyingInformation) at     SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__2.MoveNext()     in     C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line     389 HResult = -2146233079
 
PnP     Correlation ID: 7e61ca2c-dd3f-41c5-bbf5-bf8d523dfc26          Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues | PnP     Correlation ID: 7e61ca2c-dd3f-41c5-bbf5-bf8d523dfc26          Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues
PnP     Correlation ID: 7e61ca2c-dd3f-41c5-bbf5-bf8d523dfc26          Please submit any unexpected exception using the following issues list: aka.ms/spdev-issues

Can someone help me with this ?

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
