### ISSUE TITLE
Provisioning Learning Pathways in Sharepoint failed

### ISSUE THREAD

**Issue by rbutgins21** [SharePoint/sp-provisioning-service#241]
Sorry, something went wrong
There was an unexpected issue.
Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use and max pool size was reached.

Any ideas?

**Comment by Maurikrm** [comment]
Same here!

**Comment by rbutgins21** [comment]
Does anyone know if Learning Pathways is for Sharepoint On prem only?

**Comment by himani-chi** [comment]
I am also getting the same issue since yesterday.

**Comment by Maurikrm** [comment]
> Does anyone know if Learning Pathways is for Sharepoint On prem only?

As far as I know the Learning Pathway is only for SharePoint Online and not for SharePoint 2019 on-prem.

**Comment by PaoloPia** [comment]
Hi,
The Learning Pathways template is for SharePoint Online. We're facing an issue, which we're working on. The functionality should be back soon. Sorry for any inconvenience.

**Comment by himani-chi** [comment]
Looks like Provisioning is back up.

**Comment by rbutgins21** [comment]
Thanks for the heads up.

**Comment by rbutgins21** [comment]
Now getting a permissions error:  In order to provision the template you need Tenant Admin rights.  Please as a Tenant Admin to provision the template for you or to promote yourself to a Tenant Admin.

I'm a Sharepoint Admin on this tenant.

**Comment by vamsikott** [comment]
Please make sure you the user that's provisioning the site is a Site Admin and Owner for the App Catalog as per the Prerequisites. I am trying to setup Microsoft Training Paths Site and I am having issues saying its partially successful, So I am waiting for some feedback from Paolopia.

**Comment by PaoloPia** [comment]
The Provisioning Service should check for you the pre-requirements and give you feedback accordingly. There was an issue, that we fixed about 2 hours ago, so please try again and let us know. I will close this issue. Open another one in case of any further exception. Thanks.

**Comment by rbutgins21** [comment]
Is it possible to share the learning pathways site with a guest in your tenant or does the person have to be a member of the tenant.  For example, we have 3 tenants - 2 of them are for our separate business units and the 3rd is a common area that we share between the 2 business units and we add members as tenant guests.  I provisioned M365LP in the common tenant but am only seeing members of that tenant when trying to share.
