### ISSUE TITLE
Provisioning service unexpected issue

### ISSUE THREAD

**Issue by JAndre7** [SharePoint/sp-provisioning-service#243]
Hi. I'm trying to provision the learning pathways and am getting the attached screenshot issue. This has happened from numerous tries yesterday and today. Is there a service issue or what can I do? Thank you.

![image](https://user-images.githubusercontent.com/69250539/89420520-d2831800-d700-11ea-9dee-02cd6d7a1191.png)

**Comment by himani-chi** [comment]
I have been getting the same error in different tenants since yesterday

**Comment by PaoloPia** [comment]
Hi,
Thanks for filing this issue. It should be now fixed. In case of any other issue, please let us know.
