### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by sklicka** [SharePoint/sp-provisioning-service#247]
Your     request to provision     "Microsoft     365 learning pathways"      template     failed!     Please report the     issue here providing the following provisioning action correlation ID:     9017f129-3e94-4e32-abc6-09307dc27179 !                        Please provide use feedback around your used template or the     service in general by using our feedback     form . Thank you for your input advance.

**Comment by PaoloPia** [comment]
Hi, Thanks for your comprehension. There was an issue that is now fixed.
