### ISSUE TITLE
LearningPatways error

### ISSUE THREAD

**Issue by QuintenBas** [SharePoint/sp-provisioning-service#248]
Your request to provision   "Microsoft 365 learning   pathways"    template failed!   Please report the   issue here providing the following provisioning action correlation ID:   365bb79f-3f7b-4901-bf6b-e3c83d6a7e0d !
--
Please provide use feedback around your used template or the   service in general by using our feedback   form . Thank you for your input advance.

Exception: {"error":{"code":"-2147467261, System.ArgumentNullException","message":"Value cannot be null.\r\nParameter name: title"}}
Provisioning action correlation ID: 365bb79f-3f7b-4901-bf6b-e3c83d6a7e0d

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Based on the logs for the provided PnP Correlation ID, it looks like you provided an empty value for the site title. Could you please try again, double-checking the value of the title for the site? In case of any further exception, please open another issue providing the new PnP Correlation ID. Thanks.
