### ISSUE TITLE
Your request to provision "Staff home page" template failed!

### ISSUE THREAD

**Issue by martynkevans** [SharePoint/sp-provisioning-service#249]
Your request to provision "Staff home page" template failed!

Please report the issue here providing the following provisioning action correlation ID: a3df3a55-e525-42ea-870e-4dba4ccff45e !

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Based on the logs for the provided PnP Correlation ID, it looks like you created a site with a primary language other than English (1033). In fact, the provisioning failed while applying Regional Settings. Could you please try again, targeting a site with English as the primary language? In case of any further exception, please open another issue providing the new PnP Correlation ID. Thanks.

**Comment by martynkevans** [comment]
Spot on - you're a star - thanks
