### ISSUE TITLE
Your request to provision "School home page"  template failed!

### ISSUE THREAD

**Issue by jsmith0706** [SharePoint/sp-provisioning-service#251]
Please report the issue here providing the following provisioning action correlation ID: acf15126-58b5-4535-9f83-8d88852c0b9c !

**Comment by jsmith0706** [comment]
All lookbook templates are failing at the moment. Is this stemming from the issues that was happening Yesterday? Is there an ETA for resolution?

**Comment by vamsikott** [comment]
I was able to provision  the Learning Paths Site yesterday evening after the fixes. I didn't try anything today. However my CustomLeaningAdmin.aspx page to customize the site is not working.

**Comment by jsmith0706** [comment]
Yeah it seems none of the templates are provisioning today.  I have tried multiple ones and they all fail.

Thank you
Jeremiah Smith
Solutions Engineer
I.T. Solutions Engineering
[cid:image001.png@01D66BF8.1F0F0DB0]
30 W. Gore St.| MP 145 | Orlando, FL 32806
Tel: (321) 841-8280 |

website<http://www.orlandohealth.com/> | facebook<https://www.facebook.com/orlandohealth> | youtube<https://www.youtube.com/orlandohealth> | twitter<https://twitter.com/orlandohealth> | instagram<https://www.instagram.com/orlandohealth>

**Comment by PaoloPia** [comment]
Hi @jsmith0706,
Thanks for your feedback. Based on the logs for the provided PnP Correlation ID, it looks like you created a site with a primary language other than English (1033). In fact, the provisioning failed while applying Regional Settings. Could you please try again, targeting a site with English as the primary language? Thanks.

**Comment by PaoloPia** [comment]
In case of any further exception, please open another issue providing the new PnP Correlation ID.

**Comment by jsmith0706** [comment]
Thank you for the email, all of our sites are English and in the provisioning there is no way to change the language so not sure where you would change that. Please look at your tool and double check that it is set to provision in English.

Thank you
Jeremiah Smith
Solutions Engineer
I.T. Solutions Engineering
[cid:image001.png@01D66C89.8AB86CF0]
30 W. Gore St.| MP 145 | Orlando, FL 32806
Tel: (321) 841-8280 |

website<http://www.orlandohealth.com/> | facebook<https://www.facebook.com/orlandohealth> | youtube<https://www.youtube.com/orlandohealth> | twitter<https://twitter.com/orlandohealth> | instagram<https://www.instagram.com/orlandohealth>
