### ISSUE TITLE
Error while accessing the CustomLearningAdmin.aspx page

### ISSUE THREAD

**Issue by vamsikott** [SharePoint/sp-provisioning-service#253]
I get an error while accessing the CustomLearningAdmin.aspx page.
![image](https://user-images.githubusercontent.com/69254964/89545313-2eb56d00-d7d1-11ea-9d01-4ef3ce8b1001.png)

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Do you have the PnP Correlation ID of the provisioning action? Thanks.

**Comment by vamsikott** [comment]
I am afraid I don't. Is there a way I can find out from the current Site ?

**Comment by PaoloPia** [comment]
Without that information, I cannot figure out what happened. I'm sorry. Eventually, you can try to apply the template one more time, onto a new site, and see if the issue is still there. In case of any further exception, please open another issue providing the new PnP Correlation ID. Thanks.

**Comment by vamsikott** [comment]
Thanks. I provisioned a new Site and It Works fine. May be something got corrupted.

Vamsi Kotta
Chief Technology Officer
Work:         561.841.0103    Cell:           954.871.3727
Email:        vkotta@smart-infrastructure.com<mailto:vkotta@smart-infrastructure.com>
Website:    www.SMART-INFRASTRUCTURE.com<http://www.smart-infrastructure.com/>
Office:        4152 W Blueheron Blvd, Suite 1114
 Riviera Beach, FL 33404

[cid:image002.png@01D66CA0.BF673EB0]







The contents of this e-mail message and any attachments are confidential and are intended solely for the addressee.
The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to
the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this
transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by­
reply e-mail or phone and delete this message and its attachments, if any.
