### ISSUE TITLE
Issue Provision Site

### ISSUE THREAD

**Issue by rmcintosh535** [SharePoint/sp-provisioning-service#255]
The go the following issue when trying to provision a class site

correlation ID: 6421b1bb-1fb6-4db1-8d3a-ef455afd95cc !

Provisioning Status: - Unfortunately your site provisioning at least partially failed!

**Comment by omerahm** [comment]
Your request to provision "Staff home page" template failed!

correlation ID: 14bf1777-78bd-4cae-b9ce-6c3c603b18e1 !
--

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately, you provided, as the URL of the target site, the URL of the "Shared Documents" library, instead of the actual URL of the site. That's why the provisioning failed. Please, try again providing the correct URL of the site. Thanks.
