### ISSUE TITLE
Your request to provision  "Class home page"  template failed!

### ISSUE THREAD

**Issue by rkandasamy1** [SharePoint/sp-provisioning-service#256]
I have issues with adding the Class home page template to our institution's Sharepoint. Funny thing is, I was able to add the staff and school template with the same privileges. I don't know how.
Here's the contents of the email I received:
Your request to provision "Class home page" template failed!
Please report the issue here providing the following provisioning action correlation ID: 6f25e8cc-22d3-4fd1-b975-0966ca221a40 !

I tried adding again, but haven't received the email from the provisioning service.
![image](https://user-images.githubusercontent.com/69339444/89615918-14e55a00-d8a5-11ea-9c5f-c6e8c51e9d97.png)

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Are you applying the template with a user that is Owner of the target site? Did you grant the permissions requested by the app? In the log we see an "Access Denied" exception ...
