### ISSUE TITLE
LearningPathways error

### ISSUE THREAD

**Issue by QuintenBas** [SharePoint/sp-provisioning-service#259]
Your request to provision   "Microsoft 365 learning   pathways"    template failed!   Please report the   issue here providing the following provisioning action correlation ID:   1395e302-7607-4a4c-9ae2-5561b0031f49 !
--
Please provide use feedback around your used template or the   service in general by using our feedback   form . Thank you for your input advance.

Exception: {"error":{"code":"-2147467261, System.ArgumentNullException","message":"Value cannot be null.\r\nParameter name: title"}}
Provisioning action correlation ID: 1395e302-7607-4a4c-9ae2-5561b0031f49

As mentioned here: [https://github.com/SharePoint/sp-provisioning-service/issues/248](https://github.com/SharePoint/sp-provisioning-service/issues/248)
the title is missing. From the URL https://provisioning.sharepointpnp.com/tenant/home/provision?packageId=3df8bd55-b872-4c9d-88e3-6b2f05344239&source=default there is no option to enter a title.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. What is the default locale for your tenant?
Here are the localizations that the template supports:

LCID="1033" Name="English (United States)"
LCID="1031" Name="Deutsch (Deutschland)"
LCID="1036" Name="français (France)"
LCID="1049" Name="русский (Россия)"
LCID="2052" Name="中文(中国)"
LCID="1041" Name="日本語 (日本)"
LCID="1046" Name="português (Brasil)"
LCID="3082" Name="español (España, alfabetización internacional)"
LCID="1040" Name="italiano (Italia)"

**Comment by PaoloPia** [comment]
Please, eventually refer to #258 . In the meantime, I will close this item. Thanks.
