### ISSUE TITLE
Microsoft 365 learning pathways template failed

### ISSUE THREAD

**Issue by markgriffi** [SharePoint/sp-provisioning-service#261]
**Describe the issue**
Your request to provision
"Microsoft 365 learning pathways"
template failed!
Please report the issue here providing the following provisioning action correlation ID: 79814c83-b199-4b0e-8c19-5d3331c15492 !

**Expected behavior**
Service provisioned

**Screenshots**
Your request to provision
"Microsoft 365 learning pathways"
template failed!
Please report the issue here providing the following provisioning action correlation ID: 79814c83-b199-4b0e-8c19-5d3331c15492 !

**Details (please complete the following information):**
- PnP Correlation ID: 79814c83-b199-4b0e-8c19-5d3331c15492 !
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{Template-ID}]
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Based on the logs, we can see that there was a "(503) Server unavailable" exception. As such, it looks like an accidental server API hiccup. Please, try again provisioning the template and in case of any issue let us know, creating another issue and providing the new PnP Correlation ID. In the meantime, I will close this item. Thanks.
