### ISSUE TITLE
Provisioning Learning Pathways 

### ISSUE THREAD

**Issue by rbutgins21** [SharePoint/sp-provisioning-service#266]
Getting the following error when trying to provision learning pathways:

Sorry, Something went wrong.  There was an unexpected issue.

Cannot retrieve a valid access token for user

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Do you have the PnP Correlation ID of the request? Without the ID we cannot see what is happening. Thanks.

**Comment by rbutgins21** [comment]
Everything seems to be working now.  Thanks!
