### ISSUE TITLE
Education Staff Home Page site template provisioning error

### ISSUE THREAD

**Issue by Emmaburt26** [SharePoint/sp-provisioning-service#267]
Having just tried to provision the Staff home page site template into an existing but empty staff Microsoft team site but get the following error.
provisioning action correlation ID: 8bc01ca8-d002-4696-8ae7-907ef96b5a42 !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that there was an "access denied" exception while trying to upload a custom file into the target site. It might be that the site was in use while the provisioning was running. Could you please try again, targeting a fresh new site? Thanks for your cooperation.
