### ISSUE TITLE
Global sales hub Provisioning Issue - 4371541e-360d-47b1-ac5a-58f3f819718b !

### ISSUE THREAD

**Issue by koneill2020** [SharePoint/sp-provisioning-service#271]
While going to the https://lookbook.microsoft.com/ 
Clicked the See Examples button 
Click on the selected template in this case:
Department tab then Global Sales Hub  
Which uses this template:
https://lookbook.microsoft.com/details/4541e5c4-dff6-4cd7-87be-4646b56d6000 
Entered in information for site and e-mail was sent as such with error:

4371541e-360d-47b1-ac5a-58f3f819718b ! 
Your request to provision
"Global sales hub" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: 4371541e-360d-47b1-ac5a-58f3f819718b ! 

Note: Primary language of the target tenant is English
I am a SharePoint Admin using my account to provision the template.

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action]
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{Template-ID}]
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: [Yes/No]

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
I'm closing this item. Please create a new one, in case of any further issue while trying again the template. Thanks.
