### ISSUE TITLE
Your request to provision "Staff home page" template failed

### ISSUE THREAD

**Issue by gherardo76** [SharePoint/sp-provisioning-service#274]
**Describe the issue**
Non riesco ad installare il template "Staff home page"

**Screenshots**
![Schermata 2020-08-13 alle 17 25 23](https://user-images.githubusercontent.com/69428567/90154351-5042c580-dd8a-11ea-9322-250de33822ec.png)

**Details (please complete the following information):**
ID: 720843bd-2451-46d5-b23e-c409788d76ef

- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{Template-ID}]
- Primary language of the target tenant: Italiano

- Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
