### ISSUE TITLE
Your request to provision "New Employee Onboarding Hub"  template failed!

### ISSUE THREAD

**Issue by SathyaVasudevan3** [SharePoint/sp-provisioning-service#275]
**Describe the issue**
Please report the issue here providing the following provisioning action correlation ID: 8c9f020f-0f31-48dc-a995-68ac2b4fcd8a !
 

**Details (please complete the following information):**
- PnP Correlation ID: 8c9f020f-0f31-48dc-a995-68ac2b4fcd8a
- Reference Template: New Employee Onboarding Hub
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
