### ISSUE TITLE
Learning Pathways Provisioning is Forcing Tenant Sharing Policy Change

### ISSUE THREAD

**Issue by dobby10** [SharePoint/sp-provisioning-service#276]
During provisioning, the Learning Pathways template is forcing the tenant sharing policy to change to "only people in the organization".
This has been confirmed on two different tenants today 8/14/2020.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. There was a bug, which in theory we fixed few days ago, though. Can you confirm that you experienced the issue still on August 14th?

**Comment by dobby10** [comment]
Yes, this affected two tenants on Friday April 14th, around 1:30Pm and then 4pm EST.

Sent from my iPhone

On Aug 17, 2020, at 4:26 AM, Paolo Pialorsi <notifications@github.com> wrote:

﻿

Hi,
Thanks for your feedback. There was a bug, which in theory we fixed few days ago, though. Can you confirm that you experienced the issue still on August 14th?

**Comment by PaoloPia** [comment]
Hi,
Thanks for using Look Book site. This issue is now solved and fixed. I'm closing this item. Thanks for your feedback.
