### ISSUE TITLE
Your request to provision  "Microsoft 365 freelance communications site"  template failed!

### ISSUE THREAD

**Issue by ReeSources** [SharePoint/sp-provisioning-service#281]
I have tried several times but this is the error I get when trying to provision the site

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.

**Comment by ReeSources** [comment]
Good Morning

Thank you for responding.  Yes, the site was provisioned but without the content.  How do I fix that?
