### ISSUE TITLE
Template provisioning - Staff Home Page failed

### ISSUE THREAD

**Issue by AndreQuinteiro** [SharePoint/sp-provisioning-service#286]
*Details (please complete the following information):**
- PnP Correlation ID: [d3625f7e-7838-4902-8344-553dc9f74ebc]
- Reference Template: [https://lookbook.microsoft.com/details/eb5d4741-e2f4-44f1-954b-e7d598585c63]- STAFF HOME PAGE
- Primary language of the target tenant: Portuguese or English - Were can I check that ?
- Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
