### ISSUE TITLE
Provisioning of the New Employee Onboarding sites failed

### ISSUE THREAD

**Issue by johnravas** [SharePoint/sp-provisioning-service#287]
While trying to provision the NEO in my tenant, I received the following error on the provisioning screen: Unfortunately your site provisioning at least partially failed!

Here is the correlation ID: 126983c7-18d0-49d7-9481-fcb3dbefc995 from the email

It created the sites using the company name.  However it did not apply the template to the sites.  I used the default site URLs

I installed this in a different Dev tenant at the end of July and it worked perfectly fine.  Something must have changed with the process.  Please advise.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
