### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways" template failed!

### ISSUE THREAD

**Issue by drxanadu** [SharePoint/sp-provisioning-service#288]
Your request to provision "Microsoft 365 learning pathways" template failed!

The site was not built.

correlation ID: c6595988-5a5a-459d-b3bb-6921d0d8dba5

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
