### ISSUE TITLE
Microsoft 365 learning pathways" template failed

### ISSUE THREAD

**Issue by lcorvalan** [SharePoint/sp-provisioning-service#291]
ID: 9fc577c0-a53d-4ef0-a1b3-8c9f13a0f3a4

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
