### ISSUE TITLE
template failed - Mark8 Project Team 

### ISSUE THREAD

**Issue by samanehnawaz** [SharePoint/sp-provisioning-service#292]
Your request to provision

"Mark8 Project Team"

template failed!

Please report the issue here providing the following provisioning action correlation ID: 3a4f1def-a68a-4da9-9439-731dae94abe3 !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
