### ISSUE TITLE
class provisioning template failed

### ISSUE THREAD

**Issue by stevemaybury** [SharePoint/sp-provisioning-service#293]
adding Class template failed with correlation ID: 48cfec28-ea61-44cc-8822-1b3a9429af73 !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
