### ISSUE TITLE
New Employee Onboarding Hub"  template failed

### ISSUE THREAD

**Issue by hubros** [SharePoint/sp-provisioning-service#294]
Your request to provision
"New Employee Onboarding Hub" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: ccad56b3-1165-4757-945c-3b40b669cd6a !

**Comment by BladeFireLight** [comment]
I got the same error.   ID: 9b101a35-9e62-4ecf-8f1c-ea913b4b8187

**Comment by BladeFireLight** [comment]
#287

**Comment by BladeFireLight** [comment]
"Unfortunately your site provisioning at least partially failed!"
looks like part of it worked but I have no idea what is not working

**Comment by hubros** [comment]
I found that we have an existing site named NewEmployeeOnboarding since 2019 so there is a conflict. Tried to add the New Employee Onboarding Hub again to our tenant so I could change the proposed hub URL but it won't let me do it again. 

Error: Sorry, something went wrong
There was an unexpected issue.
The remote server returned an error: (403) Forbidden.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. I can confirm that, based on the event log, there is a Forbidden exception when the provisioning engine tries to create the site that already exists. You can simply apply the template again, providing a new and available URL for the target site collections. Thanks.

**Comment by hubros** [comment]
Hello, why is this closed? Did you read my last comment? I am unable to apply the template again and provide an alternate URL. So we are still stuck.

![image](https://user-images.githubusercontent.com/67300682/93215968-1ec86b80-f735-11ea-8e4b-26f41759d2e0.png)
