### ISSUE TITLE
"New Employee Onboarding Hub" template failed

### ISSUE THREAD

**Issue by KoenZomers** [SharePoint/sp-provisioning-service#298]
correlation ID: 71c83570-de6a-4ac3-8b96-42ade5df93d3

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, you provisioned the same template, targeting the same site URL at the same time, and the service does not support concurrent provisioning of the same template with the same URL. Please try again, avoiding concurrent provisionings.
