### ISSUE TITLE
Your request to provision  "New Employee Onboarding Hub"  template failed!

### ISSUE THREAD

**Issue by hbenzemel** [SharePoint/sp-provisioning-service#299]
correlation ID: 4b755e8b-2870-486f-b004-ffad10388ab7 !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was a "Modern Team Site" (GROUP#0), while the template was expecting to have a "Communication Site" (SITEPAGEPUBLISHING#0). Please, try again providing a correct site target or avoid using existing sites and let the service create the sites for you. In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
