### ISSUE TITLE
Your request to provision "New Employee Onboarding Hub" template failed!

### ISSUE THREAD

**Issue by npullin-bsi** [SharePoint/sp-provisioning-service#300]
**Describe the issue**
Unable to create a hub based on the template: 7d649598-d87c-4d54-bf1a-fdde29b7320e !

**Expected behavior**
Expected the sites to be created

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action]
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{Template-ID}]
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: [Yes/No]

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
