### ISSUE TITLE
Your request to provision "Human resources hub" template failed!

### ISSUE THREAD

**Issue by mlarmon99** [SharePoint/sp-provisioning-service#301]
Please report the issue here providing the following provisioning action correlation ID: 266a1351-039c-4547-a854-f586d2f6f797 !

**Comment by AntonRobbins** [comment]
Please report the issue here providing the following provisioning action correlation ID: 9b668198-2dc1-4f00-a725-55df8b84fa90 !

**Comment by PaoloPia** [comment]
Hi @mlarmon99,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.

Hi @AntonRobbins,
Thanks for using the Look Book site. In your case, based on the event log, you targeted an already existing sub-site, which is not the correct target for the template. In fact the exception was "Scope of template does not match target". Can you test this one more time with a correct target URL and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
