### ISSUE TITLE
"Microsoft 365 learning pathways" template failed!

### ISSUE THREAD

**Issue by simon-gueroult-transdev** [SharePoint/sp-provisioning-service#304]
Please report the issue here providing the following provisioning action correlation ID: 3d2fec6b-9142-4010-a998-00bf18ac27c1

Sorry no more detail.
Thanks in advance

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Provisioning Service. Based on the event log, I can see that the exception was "Save Conflict. Your changes conflict with those made concurrently by another user. If you want your changes to be applied, click Back in your Web browser, refresh the page, and resubmit your changes." Could it be that you were using the site before it was fully provisioned? If not, it might be a hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.

**Comment by simon-gueroult-transdev** [comment]
I had to destroy the provisioned site (and of course remove it from the recycle bin).
Then I submitted the creation request again.
It's been created just fine.
Thanks.
Simon
