### ISSUE TITLE
Provisioning failed

### ISSUE THREAD

**Issue by chrkli193** [SharePoint/sp-provisioning-service#305]
Your request to provision

"Microsoft 365 learning pathways"

template failed!

Please report the issue here providing the following provisioning action correlation ID: c99c2b1b-436c-453e-9074-df303d154430 !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Provisioning Service. Based on the eventlog, I can see that the SharePoint Framework package of the "Microsoft 365 Learning Pathways" (customlearning.sppkg) was checked out in the app catalog and, as such, the template provisioning failed. Please check-in the file or remove it before applying the template. In case of any further issue, please let us know filing another issue in this repo. Thanks.
