### ISSUE TITLE
Template Provisioning Error - MSoft 365 learning pathways

### ISSUE THREAD

**Issue by bosh345** [SharePoint/sp-provisioning-service#306]
**Describe the issue**
Emailed that provisioning had failed. Site is accessible.

3de769bd-5732-48c6-bbe0-5fb15be71844

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
