### ISSUE TITLE
Your request to provision "Human resources hub" template failed!

### ISSUE THREAD

**Issue by mlarmon99** [SharePoint/sp-provisioning-service#307]
Please reply with an answer with something other than

_"Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks."_

This is an issue other than that as I have tried a half dozen times to perform this and there is no solution

Your request to provision
"Human resources hub" template failed!
Please report the issue here providing the following provisioning action correlation ID: 326ca25e-b2e3-45bf-9970-6537701e73ad !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that there was a "Forbidden" (403) exception while trying to create the site in your target tenant. Are you sure that the target URL is available and that you have proper permissions to create the target Communication Site? Thanks for your cooperation.

**Comment by calebhoward80** [comment]
I tried to provision my HR site to show an example to management and it failed. 


Your request to provision   "New Employee Onboarding Hub"    template failed!   Please report the   issue here providing the following provisioning action correlation ID:   123ebcb5-bf08-4787-915f-1b756bf53779 !
--

**Comment by PaoloPia** [comment]
Hi @calebhoward80,
based on the event log, it was a temporary issue on the API-side. There was a server exception while uploading an image file into the target site. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.

**Comment by PaoloPia** [comment]
Hi @calebhoward80,
We haven't seen any feedback in the last 18 days. I assume that you solved your problem. If not, please open another issue. Thanks.
