### ISSUE TITLE
Staff home page"  template failed!

### ISSUE THREAD

**Issue by ipat12345** [SharePoint/sp-provisioning-service#308]
**Describe the issue**
Your request to provision
"Staff home page" template failed!
Please report the issue here providing the following provisioning action correlation ID: b445564e-a2ff-4d1c-8f1f-2ae59b820a02 ! 

**Expected behavior**
The given sharepoint site to have the template applied and provisioned

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: correlation ID: b445564e-a2ff-4d1c-8f1f-2ae59b820a02 ! 
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://provisioning.sharepointpnp.com/details/eb5d4741-e2f4-44f1-954b-e7d598585c63
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]

- Are you using a Tenant Global Admin account to provision the template: [Yes/No]
YES

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that there was an "access denied" exception while trying to upload a custom file into the target site. It might be that the site was in use while the provisioning was running. Could you please try again, targeting a fresh new site? Thanks for your cooperation.
