### ISSUE TITLE
Staff home page - provisioning fails

### ISSUE THREAD

**Issue by ChristianHaake** [SharePoint/sp-provisioning-service#309]
**Describe the issue**
A clear and concise description of what the issue is.

Started the provisioning process. After a short time, it fails. 

**Expected behavior**

failed after a few sconds

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: [0dd0b882-23dc-4edc-a31a-8e3148aac2ee !]
- Reference Template: [https://lookbook.microsoft.com/details/eb5d4741-e2f4-44f1-954b-e7d598585c63]
- Primary language of the target tenant: [German]
- Are you using a Tenant Global Admin account to provision the template: [Yes]

**Additional context**
First import in a new Site worked out.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that there was an "access denied" exception while trying to upload a custom file into the target site. It might be that the site was in use while the provisioning was running. Could you please try again, targeting a fresh new site? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
