### ISSUE TITLE
Your request to provision "New Employee Onboarding Hub" template failed!

### ISSUE THREAD

**Issue by jdmacasf** [SharePoint/sp-provisioning-service#310]
correlation ID: 1941c1f0-7fa7-4d61-b721-d500028901d0 !

Is there something I have done incorrectly here?

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
