### ISSUE TITLE
	 Unfortunately your site provisioning at least partially failed!

### ISSUE THREAD

**Issue by dafrees** [SharePoint/sp-provisioning-service#311]
Had an issue with this code and told to post here :-

0ead7e2d-c29d-4545-8a26-8e78149b56b9 

Any ideas?

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that the home page of the target site was checked out by a user and the provisioning engine was unable to update its content. Might be that you were targeting an already existing site, or that you edited the home page (home.aspx) before the end of the provisioning? Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation
