### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by TCappabianca** [SharePoint/sp-provisioning-service#313]
**Describe the issue**
I was attempting to deploy Microsoft 365 learning pathways and I received the warning.

**Expected behavior**
I would have expected this to complete without issue but this is a new deployment so the expectation was unknown

**Screenshots**
We only received the provisioning failed message, there are no images that we can locate to provide more information.

**Details (please complete the following information):**
- PnP Correlation ID: 74a11b91-fe69-435b-83bc-d2c2f6a5b234
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: EN-US
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
