### ISSUE TITLE
Your request to provision "The Perspective" template failed

### ISSUE THREAD

**Issue by rrodriguez0** [SharePoint/sp-provisioning-service#314]
**Describe the issue**
Your request to provision "The Perspective" template failed

**Expected behavior**
Get the site created with the template.

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: b8e9e6bb-cc42-424b-bc1d-b8bcceec2291 
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/6944f54d-cc8e-45ca-ba13-5f887a2d5f81
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
Done the process before and worked with another template.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you targeted an already existing site and the exception was "Unauthorized" (HTTP Status Code 401). Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
