### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by ggepponi** [SharePoint/sp-provisioning-service#315]
I try to install Microsoft 365 learning pathways

I follow the instruction here:

https://docs.microsoft.com/en-us/office365/customlearning/custom_provision

The provisioning started but i received the message:

![image](https://user-images.githubusercontent.com/72130616/94666762-2e87a880-030e-11eb-97b3-171cd2c980f5.png)
Unfortunately your site provisioning at least partially failed!

I received an email that ask me to open an issu to solve the problem.

Your request to provision   "Microsoft 365 learning   pathways"    template failed!   Please report   the issue here providing the following provisioning action correlation   ID: 23d99152-d7e0-4f51-b9bb-06cefa8c7a96 !
--

Regards

Giacomo

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that there was the following exception: "App Install timeout hit, could not determine installed state". This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
