### ISSUE TITLE
Unable to apply Staff home page template

### ISSUE THREAD

**Issue by ekrizon** [SharePoint/sp-provisioning-service#317]
Please reopen issue #316 

@PaoloPia you are incorrect, it is not a Communication site. Please see screenshot:

![image](https://user-images.githubusercontent.com/20015781/94949669-8bb26400-049e-11eb-832d-5a7fc074559c.png)

All details the same as per issue #316 

Thanks.

**Comment by PaoloPia** [comment]
Hi @ekrizon,
As far as I can see from the above screenshot, the team site is based on the "no Office 365 group" model, which is not correct. You need to follow the instructions provided here: https://go.microsoft.com/fwlink/?linkid=2135144. Thanks,

**Comment by ekrizon** [comment]
@PaoloPia thanks for confirming it only will work with the full blown Team site (with the O365 Group).  you can close. Cheers.
