### ISSUE TITLE
Need a Yes/No editor prompt that returns True/False to template parameter

### ISSUE THREAD

**Issue by jsuddsjr** [SharePoint/sp-provisioning-service#318]
**Is your feature request related to a problem? Please describe.**
The Custom Learning PnP template includes a parameter to enable or disable telemetry. We would like to make this parameter visible when the template is installed. 

**Describe the solution you'd like**
When provisioning the template, the user is presented with Yes or No radio buttons, which they can select in response to a text prompt.

**Describe alternatives you've considered**
We tried using the Boolean editor, in settings.json as follows:

```
      {
          "name":"Telemetry",
          "caption":"Improve learning pathways by sending usage telemetry to Microsoft?",
          "description":"Microsoft uses this data to help improve future Microsoft 365 learning pathways solutions. To learn more about Microsoft privacy policies see https://go.microsoft.com/fwlink/?LinkId=521839.",
          "editor": "Boolean"
      }
```
But it returned this error: 

There was an unexpected issue. The model item passed into the dictionary is of type 'SharePointPnP.ProvisioningApp.WebApp.Models.TemplateParameterModel', but this dictionary requires a model item of type 'System.Boolean'.

**Additional context**
Bert suggested I tag @PaoloPia in my inquiry.

**Comment by jsuddsjr** [comment]
@VesaJuvonen, is the right place to ask for feature requests, or would you like me to submit this elsewhere? @MHollinshead

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. I'm going to close this item because it has been stale for a long time. Thanks for your understanding.
