### ISSUE TITLE
SharePoint PnP Provisioning Service partially Failed

### ISSUE THREAD

**Issue by CherylMcKay** [SharePoint/sp-provisioning-service#319]
Your request to provision   "Microsoft 365 learning   pathways"    template failed!   Please report the   issue here providing the following provisioning action correlation ID:   19745eab-2d97-4e54-9365-c180a576e76f !
--

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on our event logs, the provisioning with ID 19745eab-2d97-4e54-9365-c180a576e76f was successful. Could you please double-check if you can see the provisioned site? Thanks.

**Comment by CherylMcKay** [comment]
The site was provisioned. I just wanted to make sure it wasn’t missing anything when I go the error.

Cheryl McKay
T 867-667-9447 | F 867-393-6200 | Yukon.ca

Working from home?
Visit the ICT Work from Home SharePoint site<https://yukonnect.gov.yk.ca/collab/hpw-c1/WfH/_layouts/15/start.aspx#/SitePages/Home.aspx>
