### ISSUE TITLE
URL validation error after cloning the repo

### ISSUE THREAD

**Issue by SubratoPati** [SharePoint/sp-provisioning-service#32]
Having cloned the repository and attempted a build of the SharePointPnP.ProvisioningApp.sln, URL validation http request throws 302 found.

**Comment by PaoloPia** [comment]
Hi @SubratoPati,
Unfortunately, as an open source community so far we cannot scale at the level of supporting single community members while customizing and building their own version of the Provisioning Service. I suggest you to double check the content of the .config files (starting from the provided models) and to properly register the AAD applications required by the service. In the future maybe we will publish some documentation about how to customize the Provisioning Service. Nowadays we are mainly focused on improving the service targeting its RTM release. As such, I will close this item.
