### ISSUE TITLE
Microsoft 365 learning pathways"  template failed

### ISSUE THREAD

**Issue by peritaun** [SharePoint/sp-provisioning-service#320]
Please report the issue here providing the following provisioning action correlation ID: 7c446d3f-5d06-44c1-ba54-a8b4b989e454 !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
