### ISSUE TITLE
New Employee Onboarding hub did not load the pre-populated content

### ISSUE THREAD

**Issue by RebeccaBundschuh** [SharePoint/sp-provisioning-service#321]
**Describe the issue**
New Employee Onboarding hub did not load the pre-populated content, and just has the standard communication site template. 

**Expected behavior**
As listed in the look book I expected some pre-built pages and pre-populated site content. 

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: ID: 60e4100d-5689-4cff-b87f-a2161f72d855 !
- Reference Template: https://provisioning.sharepointpnp.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
