### ISSUE TITLE
CustomLearningAdmin.aspx site does not appear after successful provisioning

### ISSUE THREAD

**Issue by marosonda** [SharePoint/sp-provisioning-service#322]
**Describe the issue**
A clear and concise description of what the issue is.
Original issue:
Hi Guys,

After getting "Provisioning completed" on sharepoint provisioning web-page, my Learning365 site is created but there is no CustomLearningAdmin.aspx created + I can't use Learning Pathways app on site. When i try to add new app i don't have it in "Apps You can add" list. I have to click on " From Your organization" tab and there are Pathways marked as "You can't add this app here."

After some updates from different team and running some scripts I was able to get both .aspx websites to my Sharepoint site, but apparently I'm missing templates which haven't been deployed. By the info I got there should be 11 of them.

I'm linking the issue description for better understanding:

https://github.com/pnp/custom-learning-office-365/issues/388

Thank You

**Expected behavior**
There should be some templates deployed to my learning pathways site apparently, but they are not there.

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action]
- Reference Template: https://lookbook.microsoft.com/tenant/home/provision?packageId=3df8bd55-b872-4c9d-88e3-6b2f05344239&returnUrl=https%3A%2F%2Flookbook.microsoft.com%2Fdetails%2F3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: english
- Are you using a Tenant Global Admin account to provision the template: [Yes]

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Without the PnP Correlation ID of your provisioning request, we cannot investigate it in the event logs. Please create a new issue providing that information. In the meantime, I will close this item.

**Comment by marosonda** [comment]
Hi, that's the problem. I'm not getting any error during the provisioning. It looks everything finishes successfully. But templates are not provisioned. I've tried it several times.
