### ISSUE TITLE
SharePoint Provisioning Service failed, 

### ISSUE THREAD

**Issue by klc-jay** [SharePoint/sp-provisioning-service#325]
**Describe the issue**
When using the lookbook templates everything fails when using a template with multiple sites i.e. global marketing, onboarding

**Expected behavior**
I expect it to create a new collection of sites and apply the style

**Screenshots**
![Screenshot 2020-11-02 103112](https://user-images.githubusercontent.com/60631745/97815930-9018a980-1cf6-11eb-88d0-2d19c8f6df3b.png)

**Details (please complete the following information):**
- PnP Correlation ID: ID: fe9ff7b9-ec48-4284-a638-5fec087711b7 !
- Reference Template: https://lookbook.microsoft.com/details/abef115b-e40e-469d-9bc0-e91a7bddca19 or https://lookbook.microsoft.com/details/75e60a32-9849-4ed4-b83e-b2b08983ad19
- Primary language of the target tenant: English New Zealand
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
Seems to work fine with lookbook templates that only provision one /site

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side (in the log I can see Microsoft.SharePoint.Client.UnknownError) which would imply that the template should work properly if you try it one more time. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.

**Comment by klc-jay** [comment]
Hey dude,
just tried again, had the same issue:



Your request to provision

"New Employee Onboarding Hub"

template failed!

Please report the issue here<http://aka.ms/provisioning-issue> providing the following provisioning action correlation ID: 8a8267c0-9cc8-41d6-a8de-18f3ed067492 !






________________________________
