### ISSUE TITLE
Unfortunately your site provisioning at least partially failed

### ISSUE THREAD

**Issue by HeadrickJ** [SharePoint/sp-provisioning-service#326]
**Describe the issue**
Unfortunately your site provisioning at least partially failed!

**Expected behavior**
I expected the Microsoft Learning pathways site to deploy to my tenant

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: 22ff6c3f-0e3f-4c68-aa74-0b14a0524a9e 
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239?source=default
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]English
- Are you using a Tenant Global Admin account to provision the template: [Yes]

**Additional context**
I have provisioned other sites before, no problem. I want to deploy this and the new SharePoint Success Site (https://lookbook.microsoft.com/details/0b860749-56a0-4c4c-992c-536d56d9accf?source=default)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
