### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by criscles** [SharePoint/sp-provisioning-service#327]
Please report the issue here providing the following provisioning action correlation ID: 3b2ca908-5d70-4adc-b196-bdf2bfc7491a !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that there was an "access denied" exception while trying to access the target site. Is your user authorized to access the target site? Could you please try again, targeting a fresh new site or checking that you have proper permissions for the target site? Thanks for your cooperation.
