### ISSUE TITLE
Learning pathways provisioning is not working

### ISSUE THREAD

**Issue by marosonda** [SharePoint/sp-provisioning-service#329]
**Describe the issue**

CURRENT SITUATION : i was advised by MS support to use logging option in Mozilla to try to get correlation ID, this time the provisioning is running for 30 minutes and hasn't finished. I think it's stuck.

OLDER UPDATES:

After getting "Provisioning completed" on sharepoint provisioning web-page, my Learning365 site is created but there is no CustomLearningAdmin.aspx created + I can't use Learning Pathways app on site. When i try to add new app i don't have it in "Apps You can add" list. I have to click on " From Your organization" tab and there are Pathways marked as "You can't add this app here."

After some updates from different team and running some scripts I was able to get both .aspx websites to my Sharepoint site, but apparently I'm missing templates which haven't been deployed. By the info I got there should be 11 of them.

I'm linking the issue description for better understanding:

pnp/custom-learning-office-365#388

**Expected behavior**
I want learning pathways to fully work, with templates provisioned automatically.

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: 50bb9db2-99ae-497f-b116-37c658340dce
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book service. Actually, based on the event log, I can see that your provisioning completed successfully. Regarding your other questions about how to use the Learning Pathways content in sites, please keep on discussing in the https://github.com/pnp/custom-learning-office-365 repository. Thanks.
