### ISSUE TITLE
New Sharepoint site failing to provision

### ISSUE THREAD

**Issue by benalbertfourth** [SharePoint/sp-provisioning-service#330]
We're trying to add a Sharepoint site from LookBook and getting this error: bbf59299-1b0b-480b-8a87-e20bbc01a4c7.

The URL we're attempting to add is: https://fourthlimited.sharepoint.com/sites/TheHub.

Have tried to create twice but got an error both times.

**Comment by benalbertfourth** [comment]
Hello, any update on this issue?

**Comment by benalbertfourth** [comment]
FYI, I tried creating this site again and got another error: 1fb8ac01-e127-41ed-80ad-bc8b8a9825eb

Any update on this?  This is a blocker stopping us from creating a Sharepoint site.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.

**Comment by benalbertfourth** [comment]
Hi,
I figured out a solution to the "cannot re-use a SharePoint site URL that has been changed to something else" issue, in case you run into this with any other customers.

If you rename a SharePoint site the old name no longer shows up anywhere in the system or SharePoint admin center.  HOWEVER, a hidden redirect is created that will prevent you from creating a new site using the old name.  You have to delete this hidden URL in SharePoint via PowerShell using the SharePoint Online Management Shell, covered [here](https://docs.microsoft.com/en-us/sharepoint/manage-site-redirects).

There's one more catch though!  You cannot connect to the SharePoint Online Management Shell if the Global Admin account you're using has MFA enabled.  It will give the following error:

"Connect-SPOService : The sign-in name or password does not match one in the Microsoft account system."

Which is not super helpful as the sign-in name nor the password are the issue.  MFA being enabled is.  So you also must temporarily disable MFA for your Global Admin Account (this is a bit worrisome however given the security hole this opens up).  This secondary issue is covered [here](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_sharepoint-mso_win10-mso_o365b/help-with-problem-connecting-to-sposervice/601d9863-0942-4123-99e0-3e072a894422).
