### ISSUE TITLE
NEO Sharepoint Provisioning issue

### ISSUE THREAD

**Issue by lakrupka** [SharePoint/sp-provisioning-service#332]
**Describe the issue**
NEO Sharepoint site provisioning failed

**Expected behavior**
Expect the site template to provision successfully. 

**Screenshots**
![image](https://user-images.githubusercontent.com/50598974/98571658-6291aa00-227a-11eb-9866-0601e3438cc4.png)

**Details (please complete the following information):**
- PnP Correlation ID: [79dd04b4-91c3-439b-a6ef-4415bdcd0ec1 !
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/75e60a32-9849-4ed4-b83e-b2b08983ad19
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
Trying to provision the NEO Sharepoint site template in my demo environment: 
m365x417119.onmicrosoft.com

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was a "Modern Team Site" (GROUP#0), while the template was expecting to have a "Communication Site" (SITEPAGEPUBLISHING#0). Please, try again providing a correct site target or avoid using existing sites and let the service create the sites for you. In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
