### ISSUE TITLE
Your request to provision "Staff home page"  template failed!

### ISSUE THREAD

**Issue by Bozzl** [SharePoint/sp-provisioning-service#333]
I tried to use a template from the lookbook and got this message:

Your request to provision
"Staff home page" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: 8427009c-6612-49d2-85db-0b722f2dc848 !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
