### ISSUE TITLE
Failed to Provision Site using the "The Landing Template"

### ISSUE THREAD

**Issue by bgibbons-carrier** [SharePoint/sp-provisioning-service#334]
I tried to use a template from the lookbook and got this message:

Your request to provision
"The Landing"
template failed!
Please report the issue here providing the following provisioning action correlation ID: ea3a1a57-d6c5-45b1-9c39-c0c1723fd424

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
