### ISSUE TITLE
Help with provisioning that failed

### ISSUE THREAD

**Issue by PYPsitehelp** [SharePoint/sp-provisioning-service#335]
Thank you in advance for your help! 
Kind regards

I received the following message:

provisioning action correlation ID: f2dbcfd7-5796-4362-a3c7-f7dfd329be7b !

I expected the site to provision without issue, since I do not think I have anything special in the layout of my sharepoint site to make a team site

- Reference Template: 
Lookbook > Schools > Staff site:

https://lookbook.microsoft.com/details/eb5d4741-e2f4-44f1-954b-e7d598585c63

Here is the site I am at now after trying to do the provision:

https://lookbook.microsoft.com/site/Home/Provision?returnUrl=https%3A%2F%2Flookbook.microsoft.com%2Fdetails%2Feb5d4741-e2f4-44f1-954b-e7d598585c63&source=default

<img width="1249" alt="Screen Shot 2020-11-10 at 13 30 04" src="https://user-images.githubusercontent.com/74246896/98674282-e15d1480-2358-11eb-83ca-15f180e876a7.png">

**Comment by PYPsitehelp** [comment]
Hello! I am not really sure how this works, if someone could help me I would truly appreciate it.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
