### ISSUE TITLE
Unable to Provision Collaboration team site template

### ISSUE THREAD

**Issue by khaygood** [SharePoint/sp-provisioning-service#336]
**Describe the issue**
Im trying to download the collaboration team site and I keep getting a message saying the site failed. 

**Expected behavior**
I expected the site to create a new template and website for me. 

**Screenshots**
![image](https://user-images.githubusercontent.com/74373376/98976668-a20ffe80-24e5-11eb-92e8-e29adee749bd.png)
[SharePoint PnP Provisioning Service.pdf](https://github.com/SharePoint/sp-provisioning-service/files/5532308/SharePoint.PnP.Provisioning.Service.pdf)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see the following error message: "Tenant admin has not enabled Unified Group creation." So, it looks like your user is not authorized to create Microsoft 365 Groups. Please, ask a tenant admin to enable you or to provision the site for you. Thanks.
