### ISSUE TITLE
issue with provisioning one of the lookbook template title "The Landing"

### ISSUE THREAD

**Issue by Mahent** [SharePoint/sp-provisioning-service#337]
**Describe the issue**
I was trying to provision "The Landing" template from Microsoft.lookbook.com onto our Production O365 Tennant but its failing. However it worked fine in our Development O365 Tenant

**Expected behavior**
The provisioning is straight forward and it should have worked

**Screenshots**
Your request to provision
"The Landing" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: 2cc75160-45f1-490d-8086-e395478d94e6 ! 
Please provide use feedback around your used template or the service in general by using our feedback form . Thank you for your input advance. 

**Details (please complete the following information):**
I am just wondering if it is the add rotator banner that is failing but I am not sure why it was successfully deployed on the dev tenant and not the prod tenant when they are both O365 

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.

**Comment by Mahent** [comment]
Hi PaoloPia, 

Thank you for the response but I just tried again and it failed as per screen below : 

Your request to provision
"The Landing" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: d0f43d53-356c-4037-b339-ec893c92b61d ! 
Please provide use feedback around your used template or the service in general by using our feedback form . Thank you for your input advance.

**Comment by Mahent** [comment]
Tried this template again and it failed but others works which is a shame because this is the template the company wants to use
error screen :
 
Provisioning has started
You'll get an email notification when your site(s) is(are) ready

SharePoint Look Book
Want to add another site or get more inspiration?

Email	Mahen.Teeluck@uk.rlb.com
Site Title	RLB Intranet
Site URL	
https://ukrlb.sharepoint.com/sites/Intranet
Provisioning Status	
Unfortunately your site provisioning at least partially failed!
