### ISSUE TITLE
Powershell to provision staff template to multiple team sites in our tenant

### ISSUE THREAD

**Issue by ShahidAbubakarFurniturewala** [SharePoint/sp-provisioning-service#339]
We have more than 200 staff team sites and need to provision below template on all these sites: https://provisioning.sharepointpnp.com/details/eb5d4741-e2f4-44f1-954b-e7d598585c63 
We can do it manually one by one, but it is very time consuming. Please advise if it can be done from PowerShell code? Can we add list of sites in csv file and run PowerShell code on csv file?

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. The source of the template is available here (https://github.com/SharePoint/sp-dev-provisioning-templates/tree/master/site/edustaff) on GitHub. You can download the .PNP file and apply it using PnP PowerShell (https://github.com/pnp/powershell) using a foreach on all of the sites/teams. The cmdlet to use is Apply-PnPTenantTemplate.
