### ISSUE TITLE
Partially Failed Provision

### ISSUE THREAD

**Issue by PYPsitehelp** [SharePoint/sp-provisioning-service#341]
**Describe the issue**
Second Attempt: Template lookbook-schools-staff homepage

**Screenshots**
<img width="887" alt="Screen Shot 2020-11-17 at 19 28 14" src="https://user-images.githubusercontent.com/74246896/99431672-6d4bdf00-290b-11eb-8ef6-55359431809a.png">

**Details (please complete the following information):**

Your request to provision"Staff home page" template failed!Please report the issue here providing the following provisioning action correlation ID: df7b6846-ab8e-49ef-ac26-f751fdf94af9 !

Template lookbook: Schools-Staff homepage
https://lookbook.microsoft.com/details/eb5d4741-e2f4-44f1-954b-e7d598585c63

**Additional context**
This is the second post. I recieved this message, and so I tried it again. It failed again though! : Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.

**Comment by PaoloPia** [comment]
Hi,
Thanks for trying again. In the log, we see the following exception: "Access denied. You do not have permission to perform this action or access this resource" while uploading a sample file (Updated Classroom Policies and Procedures.pptx) into a library. Could it be that you were already using/browsing the site before the end of the provisioning and, as such, the file was accidentally locked? Or could it be that you targeted the same site as before (the first try), and that file is somehow locked/checked-out? Please, let me know. I'll keep this item open in the meantime. Thanks.

**Comment by bbarnwell** [comment]
I'm having the same issue. In my case, I created a site, then realized you can't apply this theme to an existing site. So, I deleted the site (also permanently deleted the site) I created and tried to provision the Schools template using the same name and URL and go this same error message as above. I tried this twice - same result both times. I did not browse the new site URL during provisioning.

**Comment by bbarnwell** [comment]
Third time's a charm! My site was successfully provisioned.

**Comment by PaoloPia** [comment]
Unfortunately, it can be because of temporary hiccups in the APIs on the server side. Thanks for the update.
