### ISSUE TITLE
Your request to provision "New Employee Onboarding Hub"  template failed!

### ISSUE THREAD

**Issue by mlukela** [SharePoint/sp-provisioning-service#344]
**Describe the issue**
I tried to add the Onboarding Hub to our tenant. https://lookbook.microsoft.com/details/75e60a32-9849-4ed4-b83e-b2b08983ad19

**Expected behavior**
4 sites should have provisioned but instead a I got an error 

**Screenshots**
![image](https://user-images.githubusercontent.com/74734070/99707803-cd4c9d80-2a51-11eb-8380-2f1dd3ae06ad.png)

**Details (please complete the following information):**
- PnP Correlation ID: 6447e747-a93d-4714-81d2-40b299de6deb 
- Reference Template: [https://lookbook.microsoft.com/details/75e60a32-9849-4ed4-b83e-b2b08983ad19]
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: [Yes

**Additional context**

**Comment by githubsteveb** [comment]
did you manage to get anywhere with this one? I am experiencing the same issue.

**Comment by mlukela** [comment]
I reported the issue to support but nothing yet.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
