### ISSUE TITLE
Unable to use school home page template and it is my co-relation ID: 973ff8c4-838d-4cc9-9e2e-538c2b3e6f3c ! 

### ISSUE THREAD

**Issue by shaik11111** [SharePoint/sp-provisioning-service#347]
**Describe the issue**
A clear and concise description of what the issue is.

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action]
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{Template-ID}]
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: [Yes/No]

**Additional context**

**Comment by shaik11111** [comment]
Tried to adding the template into my tenant but provisioning failed

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
