### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways" template failed!

### ISSUE THREAD

**Issue by borrelnoten** [SharePoint/sp-provisioning-service#349]
Your request to provision "Microsoft 365 learning pathways" template failed!

Please report the issue here providing the following provisioning action

correlation ID: 9c8ecb4e-e81d-41eb-9f3d-7ccec98a10da !

**Comment by borrelnoten** [comment]
Update on the error details:

Exception: The URL 'SitePages/de/Get-started-with-Microsoft-Teams.aspx' is invalid. It may refer to a nonexistent file or folder, or refer to a valid file or folder that is not in the current Web.
Provisioning action correlation ID: ee7c537b-56a3-4af0-bc7d-1b23c0052d74

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
