### ISSUE TITLE
I receive Your request to provision "Global marketing hub"  template failed! when provision is finised 

### ISSUE THREAD

**Issue by steper2020** [SharePoint/sp-provisioning-service#350]
**Describe the issue**
A clear and concise description of what the issue is.

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action]
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{Template-ID}]
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: [Yes/No]

**Additional context**

**Comment by steper2020** [comment]
I try to create a Sharepoint Space platform for a virtual event next week, unfortunately, I receive this message after provision is completed. What should I do?
![provision](https://user-images.githubusercontent.com/75259257/100618439-c3f5e780-3313-11eb-8449-c6c14ecf3629.JPG)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
