### ISSUE TITLE
Request to provision "Class home page" template failed

### ISSUE THREAD

**Issue by EmCoulter** [SharePoint/sp-provisioning-service#351]
Your request to provision   "Class home page"    template failed!   Please report   the issue here providing the following provisioning action correlation   ID: 885b2a29-2e24-43d7-a187-8fe95a161666 !
--

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was a "Communication Site" (SITEPAGEPUBLISHING#0), while the template was expecting to have a "Modern Team Site" (GROUP#0). Please, try again providing a correct site target. In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
