### ISSUE TITLE
Error provisioning Microsoft 365 learning pathways

### ISSUE THREAD

**Issue by IvanParedes365** [SharePoint/sp-provisioning-service#352]
- PnP Correlation ID: 1bd170e6-de1a-4e1f-b9a5-be6137e4dacc
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: EN-US
- Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
