### ISSUE TITLE
Your request to provision "New Employee Onboarding Hub" template failed!

### ISSUE THREAD

**Issue by garethismyname** [SharePoint/sp-provisioning-service#354]
524ae5dd-c70f-457d-bcf0-34ab0f7780f0 !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that there was an "access denied" exception while trying to upload a custom file into the target site. It might be that the site was in use while the provisioning was running. Could you please try again, targeting a fresh new site? Thanks for your cooperation.
