### ISSUE TITLE
Your request to provision "New Employee Onboarding Hub"  template failed!

### ISSUE THREAD

**Issue by LBIWebMaster** [SharePoint/sp-provisioning-service#356]
Provisioning MS SharePoint Onboarding Hub

Your request to provision "New Employee Onboarding Hub"template failed!
Please report the issue here providing the following provisioning action correlation ID: 9fea5558-9aaf-4c62-bddf-d52394d5ff66 ! 

**Expected behavior**
On Boarding site to be provisioned

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: 9fea5558-9aaf-4c62-bddf-d52394d5ff66
- Reference Template: https://lookbook.microsoft.com/details/75e60a32-9849-4ed4-b83e-b2b08983ad19: 
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: [Yes/No] Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
