### ISSUE TITLE
Provision failed for Global Marketing template

### ISSUE THREAD

**Issue by gavin-adams** [SharePoint/sp-provisioning-service#357]
**Describe the issue**
Provision failed 

**Details (please complete the following information):**
- PnP Correlation ID: 470fdd68-b562-4963-b189-5323f2a4d00f 

- Reference Template: https://lookbook.microsoft.com/details/abef115b-e40e-469d-9bc0-e91a7bddca19

- Primary language of the target tenant: en
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
First attempt at using the provisioning tool in this tenancy

**Comment by gavin-adams** [comment]
sorry close this.
I just found that the main site URL was already taken by a microsoft team.
I hadn't looked at the provision page requesting site title / url looked like it had checked that the url was available.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Inpsecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while creating the target Communication Site (the exception was 403 - "Forbidden"). Could you please try to provision the solution to a different site URL or with a different user account? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
