### ISSUE TITLE
impossible to activate template

### ISSUE THREAD

**Issue by chrisboulet** [SharePoint/sp-provisioning-service#358]
**Describe the issue**
Trying to activate the sharepoint Template 
https://lookbook.microsoft.com/details/6944f54d-cc8e-45ca-ba13-5f887a2d5f81

**Expected behavior**
supposed to enable the template and provision a site automatically.
**Screenshots**

**Details (please complete the following information):**

- PnP Correlation ID:  5341d81d-2322-4928-a023-845f98e9738b 
- Reference Template: https://lookbook.microsoft.com/details/6944f54d-cc8e-45ca-ba13-5f887a2d5f81

- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: YES

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
