### ISSUE TITLE
New Employee Onboarding Site won't fully provision

### ISSUE THREAD

**Issue by NJoll** [SharePoint/sp-provisioning-service#359]
**Describe the issue**
New Employee Onboarding Site won't fully provision

**Expected behavior**
The site is suppose to provision fully and I should receive an email saying it's provisioned, with a link to the new site.

**Screenshots**
<img width="1792" alt="Screen Shot 2020-12-11 at 3 29 00 PM" src="https://user-images.githubusercontent.com/75820498/101854105-b5d28180-3bc5-11eb-982f-5c6d8a2b0684.png">

**Details (please complete the following information):**
- PnP Correlation ID:  3fa2851f-d4ad-4024-998f-1f060aa59425 !
- Reference Template: https://lookbook.microsoft.com/details/75e60a32-9849-4ed4-b83e-b2b08983ad19
- Primary language of the target tenant: Unsure
- Are you using a Tenant Global Admin account to provision the template: No but even the global admin had the same problem!

**Additional context**
I've followed the steps in adding the template to the tenant. Then I inserted my company name (instead of it saying Contoso) and changed the URL for the sales and engineering departmental sites before clicking on provision site.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Inpsecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while creating the target Communication Site (the exception was 403 - "Forbidden"). Could you please try to provision the solution to a different site URL or with a different user account? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
