### ISSUE TITLE
Didn't complete execution

### ISSUE THREAD

**Issue by krueger80** [SharePoint/sp-provisioning-service#361]
Your request to provision
"New Employee Onboarding Hub" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: e097dd7d-ec61-4e54-bcc4-5e6004b9c8a7 ! 

After looking at the sharepoint sites, there was the 4 sites, but hub configuration was not done and no customization too.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. I inspected the logs and I can see that the 4 site collections were created, but then there was an unexpected exception (a random _ArgumentNullException_) while applying the provisioning template on the very first site. I'd like to ask you to try again, eventually using new URLs or deleting the old ones (and removing them from the recycle bin). In case of any further problem, please file another issue in this repository and provide detailed information about the inputs you provided while provisioning the package. Thanks for your cooperation.

**Comment by krueger80** [comment]
I've made few tentatives with support (email) and it worked one time when we kept default site name + "Test" suffix. The site hubs were not fully done though. Hub name was empty and only one site was set as child. 

After we tried again with the final site names, it failed again. At this point we told support we'll rename the "Test" sites and we can close the case.
