### ISSUE TITLE
SharePoint Provisioning Service - Your request to provision  "New Employee Onboarding Hub"  template failed!

### ISSUE THREAD

**Issue by jesperschroder** [SharePoint/sp-provisioning-service#362]
Providing the following provisioning action correlation ID: 48054827-4e56-4f78-bec6-306851496daf !

Tenant = pointstoshare.dk

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Inspecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while creating the target Communication Site (the exception was 403 - "Forbidden"). Could you please try to provision the solution to a different site URL or with a different user account? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
