### ISSUE TITLE
Leadeship Connection Template Failed

### ISSUE THREAD

**Issue by jgenese** [SharePoint/sp-provisioning-service#363]
Your   request to provision   "Leadership   Connection"    template   failed!   Please report the   issue here providing the following provisioning action correlation ID:   0db2610d-8507-4a5f-b6dc-055bf5901877 !
--

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
