### ISSUE TITLE
provisioning action correlation ID: 0c16a44c-37a4-4cae-84e5-0507d89a1943 

### ISSUE THREAD

**Issue by Danewitham** [SharePoint/sp-provisioning-service#364]
New Employee Onboarding Hub" 
template failed

**Details (please complete the following information):**
- PnP Correlation ID: [0c16a44c-37a4-4cae-84e5-0507d89a1943 ]
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/tenant/Home/Provision?returnUrl=https%3A%2F%2Flookbook.microsoft.com%2Fdetails%2F75e60a32-9849-4ed4-b83e-b2b08983ad19&source=default
- Primary language of the target tenant: [English]
- Are you using a Tenant Global Admin account to provision the template: [Yes]

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
