### ISSUE TITLE
Template provisioning failed

### ISSUE THREAD

**Issue by jcacperalta** [SharePoint/sp-provisioning-service#367]
**Describe the issue**
I tried to provision my team site, it failed. I had successfully provisioned once but had to delete the site to start fresh. But when I try to provision again with same site url, I now get this issue

**Screenshots**
![image](https://user-images.githubusercontent.com/10722528/103208547-da578900-493b-11eb-92b1-6700154cbdd8.png)

**Details (please complete the following information):**
- PnP Correlation ID: 20a75850-2166-4ab9-a19a-5cf26619a1b3
- Reference Template: School https://lookbook.microsoft.com/details/44dc3585-9140-4183-81fc-bdb057f71ac1
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: No

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. There was a server-side exception (on the SharePoint Online side) while creating the target Communication Site. Can you test this one more time - using a different target URL - and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
