### ISSUE TITLE
Failed to Provision Learning pathways

### ISSUE THREAD

**Issue by Reddzman** [SharePoint/sp-provisioning-service#369]
Failed to Provision Learning pathways with the following error: correlation ID: acc91f93-1a97-4c8d-81f3-9fb62d35ac9d

**Comment by PaoloPia** [comment]
Hi @Reddzman,
Thanks for using the Look Book site. I inspected the event log, and it looks like your provisioning request did not get processed at all. I need to dig into the log to understand the reason why. In the meantime, could you please try again, providing a different URL? In case of any failure, please open another issue and provide the new correlation ID. Thanks for your cooperation.

**Comment by Reddzman** [comment]
Thank you for responding.  I was able to delete everything including the app that was deployed and successfully deploy Learning pathways after a couple tries. Interesting that the logging doesn't have my request.  Thanks anyways!

-Nick

Nicholas R Patterson
303.949.9811
nickrpatterson@outlook.com
