### ISSUE TITLE
Human Resources Hub failed

### ISSUE THREAD

**Issue by ddkato** [SharePoint/sp-provisioning-service#370]
I got this error but why?

Your request to provision
"Human resources hub" 
template failed!

**Comment by PaoloPia** [comment]
Could you please provide the Correlation ID for further investigation? Thanks.

**Comment by digitalrain101** [comment]
> Could you please provide the Correlation ID for further investigation? Thanks.

Hi Paolo, here is mine, just had this happen to me an hr or so ago:

a6c15857-700a-4125-9f56-ff4c2562cd1b

**Comment by digitalrain101** [comment]
Also @PaoloPia, I had another template provisioned prior to this Hub provisioned that used the same URL. It was deleted using Sharepoint "Settings" > "Site Info" panel first. It remained in the recycle bin after that, then I decided to provision this HR Hub template afterwards (layout worked better) and received the failed notification via email. Just a bit of backstory, let me know if you need anything else, I can provide whatever is needed. Thanks.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
