### ISSUE TITLE
SharePoint look book failed to install 

### ISSUE THREAD

**Issue by Sandkev** [SharePoint/sp-provisioning-service#371]
Received this message: 
Your request to provision
"Collaboration team site" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: 6a728f98-76e4-4b72-8692-b46446f8e880 !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log I can see the exception "Tenant admin has not enabled Unified Group creation.". So, please ask your Tenant Administrator to enable Microsoft 365 Groups creations. Thanks.
