### ISSUE TITLE
Template Provisioning Failed

### ISSUE THREAD

**Issue by Lilian1331** [SharePoint/sp-provisioning-service#372]
**Describe the issue**
I have tried to provision the site template to my site, but I have received an Template Failed!. 
Have tried again with different template, it turns out the same.
Could you please help to check? Thanks

**Expected behavior**
Template Provision Succeed.

**Screenshots**
![image](https://user-images.githubusercontent.com/23545532/103988308-d263d880-51c8-11eb-9ccf-18492cc280e4.png)

**Details (please complete the following information):**
- PnP Correlation ID: cb14584c-c7d6-4c08-8d94-e3756207c301
- Reference Template: https://lookbook.microsoft.com/details/4541e5c4-dff6-4cd7-87be-4646b56d6000
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.

**Comment by Lilian1331** [comment]
> Hi,
> Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.

Thanks!
