### ISSUE TITLE
Unable to provision the site (Template: The Landing)

### ISSUE THREAD

**Issue by parsonchenpico** [SharePoint/sp-provisioning-service#373]
Your request to provision
"The Landing"
template failed!
Please report the issue here providing the following provisioning action correlation ID: 4d69b2ce-6a39-4466-85ec-85876f296abd !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
