### ISSUE TITLE
New Employee Onboarding Hub Provisioning Failed

### ISSUE THREAD

**Issue by HiltonGiesenow** [SharePoint/sp-provisioning-service#374]
**Describe the issue**
I'm trying to deploy the NEO hub to a totally new demo tenant (m365x.....sharepoint.com) and it fails both in the provisioning portal and via PowerShell.

Via the portal, I get the following email correlation ID: 7568b0b1-24a3-47c8-8848-e14b0524ba4b

Via PowerShell, I get:

```
Apply-PnPTenantTemplate : Access denied. You do not have permission to perform this action or access 
this resource.
```

**Expected behavior**
The NEO hub and sites should be provisioned

**Details (please complete the following information):**
- PnP Correlation ID: 7568b0b1-24a3-47c8-8848-e14b0524ba4b
- Reference Template: https://lookbook.microsoft.com/details/75e60a32-9849-4ed4-b83e-b2b08983ad19
- Primary language of the target tenant: 1033 (I think- it's a default demo tenant)
- Are you using a Tenant Global Admin account to provision the template: Yes

I've tried turning on the PnP logging, but don't get much more info from there:

powershell.exe Information: 0 : 2021-01-10 14:52:00.5550	[OfficeDevPnP.Core]	[0]	[Information]	File NEO.pnp retrieved from folder 	0ms	
powershell.exe Information: 0 : 2021-01-10 14:52:00.8223	[OfficeDevPnP.Core]	[0]	[Information]	File NEO.pnp retrieved from folder 	0ms	
powershell.exe Information: 0 : 2021-01-10 14:52:03.4399	[OfficeDevPnP.Core]	[0]	[Information]	File NEO.xml retrieved from folder 	0ms	
powershell.exe Information: 0 : 2021-01-10 14:52:04.1946	[Provisioning]	[18]	[Information]	ProgressDelegate registered	0ms	8f69876b-d24c-4b2c-8c1a-c47693b92b0c
powershell.exe Information: 0 : 2021-01-10 14:52:04.1946	[Provisioning]	[18]	[Information]	MessagesDelegate registered	0ms	8f69876b-d24c-4b2c-8c1a-c47693b92b0c
powershell.exe Information: 0 : 2021-01-10 14:52:38.8449	[Provisioning]	[18]	[Information]	ProgressDelegate registered	0ms	8f69876b-d24c-4b2c-8c1a-c47693b92b0c
powershell.exe Information: 0 : 2021-01-10 14:52:38.8449	[Provisioning]	[18]	[Information]	MessagesDelegate registered	0ms	8f69876b-d24c-4b2c-8c1a-c47693b92b0c
powershell.exe Warning: 0 : 2021-01-10 14:52:39.1592	[Provisioning]	[18]	[Information]	The source site from which the template was generated had a base template ID value of SITEPAGEPUBLISHING#0, while the current target site has a base template ID value of GROUP#0. This could cause potential issues while applying the template.	314ms	8f69876b-d24c-4b2c-8c1a-c47693b92b0c
powershell.exe Warning: 0 : 2021-01-10 14:52:41.6911	[List instances]	[18]	[Information]	Skip adding/updating custom actions because the site has "noscript" enabled.	1206ms	8f69876b-d24c-4b2c-8c1a-c47693b92b0c
powershell.exe Warning: 0 : 2021-01-10 14:52:42.1485	[List instances]	[18]	[Information]	Skip adding/updating custom actions because the site has "noscript" enabled.	1663ms	8f69876b-d24c-4b2c-8c1a-c47693b92b0c
powershell.exe Warning: 0 : 2021-01-10 14:52:51.5611	[List instances]	[18]	[Information]	Skip adding/updating custom actions because the site has "noscript" enabled.	854ms	8f69876b-d24c-4b2c-8c1a-c47693b92b0c
powershell.exe Warning: 0 : 2021-01-10 14:52:52.0311	[List instances]	[18]	[Information]	Skip adding/updating custom actions because the site has "noscript" enabled.	1324ms	8f69876b-d24c-4b2c-8c1a-c47693b92b0c
powershell.exe Error: 0 : 2021-01-10 14:52:53.6043	[OfficeDevPnP.Core]	[0]	[Error]	ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerUnauthorizedAccessException: Access denied. You do not have permission to perform this action or access this resource.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
ServerErrorCode: -2147024891
ServerErrorTypeName: System.UnauthorizedAccessException
ServerErrorTraceCorrelationId: 82e89f9f-f03b-0000-6fde-e0f3ccd8e89a
ServerErrorValue: 
ServerErrorDetails: 
.	0ms	

**I'd be happy to help try resolve this, but not sure where to start...**

**Comment by HiltonGiesenow** [comment]
If it helps in any way, I get the following warning in PowerShell: 

```
WARNING: The source site from which the template was generated had a base template ID value of SITEPAGEPUBLISHING#0, while the current target site has a base template ID value of GROUP#0. This could cause potential issues while applying the template.
```

**Comment by PaoloPia** [comment]
Hi,
Based on the above error message, you applied the template providing the URL of a site that was a "Modern Team Site" (GROUP#0), while the template was expecting to have a "Communication Site" (SITEPAGEPUBLISHING#0). Please, try again providing a correct site target or avoid using existing sites and let the service create the sites for you. In case of any issue, please create another item here. Thanks for your cooperation.
