### ISSUE TITLE
New Employee Onboarding Hub Provisioning Failed

### ISSUE THREAD

**Issue by HiltonGiesenow** [SharePoint/sp-provisioning-service#375]
**Describe the issue**
This is a duplicate of https://github.com/SharePoint/sp-provisioning-service/issues/374 because the issues keep just getting closed, without the chance for further dialog. Perhaps this will clarify:

1) I am using a COMPLETELY new O365 Demo site (provisioned using the https://cdx.transform.microsoft.com/ tool). I am trying the provisioning with MULTIPLE new tenants (like if it fails with the Look Book, I'll delete the tenant and create another COMPLETELY new one, to test with local PowerShell)

2) I'm trying to provision ONLY NEO TEMPLATE to this new tenant - NOTHING ELSE am I touching in the Tenant

3) I'm trying to provision with the LOOKBOOK - fails as per the logs I've sent in the past (correlation id). Happy to try again, and send another correlation ID if that helps?

4) I'm trying to provision with the local PowerShell - fails as per my previous issue).

PLEASE NOTE - to repeat, I'm trying EITHER the Lookbook OR the PowerShell, and BOTH are failing to provision. I've tried:

a) new tenant -> Lookbook -> fail
b) new tenant -> PowerShell -> fail
c) new tenant -> Lookbook -> fail, then try PowerShell -> fail

I am NOT pre-creating the sites at all, I am ONLY using the above approaches, and BOTH are failing.

I hope that's more clear. Please get in touch rather than just closing the issue, without further discussion. As I said in the previous issues, I'm more than happy to try resolve this, but I'm struggling with where to begin even.

**Comment by Marc-WMReply** [comment]
I too am experiencing this issue when using the Lookbook

**Comment by PaoloPia** [comment]
Hi @HiltonGiesenow,
Recently we've been experiencing some issues with file uploads during provisioning. In particular with the NEO template, which creates multiple sites and uploads quite some files. We're working on improving the experience, from a Look Book site point of view. At the same time, I see that you're experiencing issues using PowerShell, too. Could you please use the Get-PnPException cmdlet to get the detailed exception that you get in PowerShell and share it here, for further investigation? Thanks.

**Comment by HiltonGiesenow** [comment]
Sure, here you go:

CorrelationId    : fac3a29f-50f2-0000-7aad-eb41de20e1dc
TimeStampUtc     : 19 Jan 2021 9:59:28 AM
Message          : Access denied. You do not have permission to perform this action or access this resource.
Stacktrace       :    at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyTenantTemplate(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, ApplyConfiguration configuration)
                      at PnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
ScriptLineNumber : 1

**Comment by PaoloPia** [comment]
Just out of curiosity, did you try with a tenant created without the CDX tool? Thanks.

**Comment by HiltonGiesenow** [comment]
No, I would only have a production tenant otherwise, which I don't want to install into. Suggestion?

**Comment by HiltonGiesenow** [comment]
@PaoloPia , I signed up for a new developer tenant, and it worked fine in there! Thanks for the suggestion! Any idea why it would fail in a CDX environment? At least it's (hopefully) a big clue to the issue though

**Comment by PaoloPia** [comment]
I've no clue, but I'll definitely investigate the issue. Thanks for reporting. I will close this one, in the meantime.
