### ISSUE TITLE
"Staff home page" template provision failed

### ISSUE THREAD

**Issue by jjosepagan** [SharePoint/sp-provisioning-service#378]
**Describe the issue**
I am trying to apply the template "Staff home page" to the site https://fundacioneducacioncatolica.sharepoint.com/sites/PortaldelEducadorHEEP

**Expected behavior**
I set tEAMS in English with the account @heep.es
I created the Team  as PLC with the account @heep.es
I have invited myself to the account @colegiosfec.com (which has got access to the tenant admin site)
I got the Sharepoint URL from the web
I set the site in English (both region and language)
I started the provision of the template.
I got the message "Unfortunately your site provisioning at least partially failed!"

**Screenshots**

![image](https://user-images.githubusercontent.com/69315872/105023292-12d61880-5a4b-11eb-9605-6fd388e2d86c.png)

**Details (please complete the following information):**
- PnP Correlation ID:  18c2f717-e324-4e36-8fba-9d9fffb5c07d !
- Reference Template: Staff home page
- Primary language of the target tenant: Spanish
- Are you using a Tenant Global Admin account to provision the template: [No]

**Comment by HiltonGiesenow** [comment]
I don't know if this is relevant to you, but I was having trouble and it finally worked when I tried in another tenant - I was using one of the "demo" tenants Microsoft offers, and when I switched to another type of tenant (an Office/Microsoft 365 "developer" tenant) then it worked fine - see here for how to get one - https://developer.microsoft.com/en-us/microsoft-365/dev-program

**Comment by jjosepagan** [comment]
Thanks a lot for your answer, but I don't think it is really that the issue, because we are not using "demo" tenants. Anyway, I'll check the link just in case it could give some light about the question. thx!!!

**Comment by PaoloPia** [comment]
Hi @jjosepagan,
Thanks for using the Look Book site. Based on the log I can see that the issue was an "Access Denied" while trying to upload an image on the target site. In the last few weeks, we've been experiencing some issues related to files upload and we're working on making the provisioning engine stronger. In the meantime, you can only try again or wait. I'm sorry. Thanks for your cooperation.
