### ISSUE TITLE
provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by 0ddmonkey** [SharePoint/sp-provisioning-service#379]
**Describe the issue**
Provisioning Microsoft 365 Learning Pathway from https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239 and received an email with the error "Your request to provision "Microsoft 365 learning pathways" 
template failed!"

**Expected behavior**
Template should have deloyed to out tenant and the email should have acknowledged completion.

**Screenshots**
N/A

**Details (please complete the following information):**
- PnP Correlation ID: 3481163a-a778-4602-860d-2d3d29521307 
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes (millerj-s@wz.hasbro.com)

**Additional context**

**Comment by HiltonGiesenow** [comment]
I don't know if this is relevant to you, but I was having trouble and it finally worked when I tried in another tenant - I was using one of the "demo" tenants Microsoft offers, and when I switched to another type of tenant (an Office/Microsoft 365 "developer" tenant) then it worked fine - see here for how to get one - https://developer.microsoft.com/en-us/microsoft-365/dev-program

**Comment by 0ddmonkey** [comment]
@HiltonGiesenow,  Thank you for the suggestion but we are using a non-demo/production tenant so switching is not an option.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
