### ISSUE TITLE
New Employee Onboarding  partially provisioned in demo tenant

### ISSUE THREAD

**Issue by VincentSterken** [SharePoint/sp-provisioning-service#380]
**Describe the issue**
A clear and concise description of what the issue is.
Sites haven't provisioned fully

**Expected behavior**
New Employee Onboarding to be available

**Screenshots**
![Screenshot 2021-01-20 222022](https://user-images.githubusercontent.com/54710639/105241348-d7803a80-5b6d-11eb-8c32-c63109fd4504.png)

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action]
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{Template-ID}]
- https://lookbook.microsoft.com/tenant/Home/Provision?returnUrl=https%3A%2F%2Flookbook.microsoft.com%2Fdetails%2F75e60a32-9849-4ed4-b83e-b2b08983ad19&source=default
- 
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant] EN
- Are you using a Tenant Global Admin account to provision the template: [Yes/No] Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi @VincentSterken,
Thanks for your feedback. Without the PnP Correlation ID we cannot further investigate the issue. However, in the last few weeks we noticed some issues with NEO template and the Partners demo tenants (CDX). Please, double-check if you are using a "regular" tenant or a demo one, and eventually move to a regular one if that is the case. Thanks for your cooperation.

**Comment by VincentSterken** [comment]
The goal was to test it out on a demo tenant (cdx) in order to evaluate if it is useful to add it to our (or client's) production tenants.

**Comment by Switcher05** [comment]
967b1470-391f-4550-b39f-be7d6e85df0f is my ID when this template failed for me.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Can you eventually test it on a non CDX tenant? Something like a "regular" trial tenant. Thanks.
