### ISSUE TITLE
Your request to provision  "Global marketing hub"  template failed!

### ISSUE THREAD

**Issue by siegfriedcw** [SharePoint/sp-provisioning-service#381]
Please report the issue here providing the following provisioning action correlation ID: f357228b-3b68-4dbc-a53e-df802171dc97 !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, you provisioned the same template, targeting the same site URL at the same time, and the service does not support concurrent provisioning of the same template with the same URL. Please try again, avoiding concurrent provisionings.
