### ISSUE TITLE
Learning Pathways Lookbook install does not recognise global admin

### ISSUE THREAD

**Issue by LukeOHardman** [SharePoint/sp-provisioning-service#384]
I am Trying to install Learning Pathways logged in with Global admin account. On running pre-requisiites from lookbook page

![image](https://user-images.githubusercontent.com/39157809/105868394-0c691300-5fee-11eb-91d0-0d0d68f9ce5a.png)

**Details (please complete the following information):**
Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: [Language Not Set for Installing user]
- Are you using a Tenant Global Admin account to provision the template: [Yes/]

**Additional context**
Can install other lookbooks. Tested on two tenants with same results

Any help greatly appreciated!!

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. I guess you are in the same scenario described in issue  #377 . We're investigating the problem. If your "Company Administrator" is called "Global Administrator" when queried via Microsoft Graph, please close this issue and just follow instructions that will come in the upcoming days for #377 . Thanks.

**Comment by LukeOHardman** [comment]
Thanks Paolo,

Yes looks identical to #377. Searched for ages and couldn't find it. I'll close mine

Thanks again
________________________________

**Comment by LukeOHardman** [comment]
As instructed #377
