### ISSUE TITLE
NEO Hub, Engineering Site Provisioning Failed

### ISSUE THREAD

**Issue by Ukiman1014** [SharePoint/sp-provisioning-service#385]
**Describe the issue**
Engineering site provisioning failed, though the hub and Sales were successful.  
"Your request to provision"New Employee Onboarding Hub"template failed!Please report the issue here providing the following provisioning action **correlation ID: cdd60cab-a043-4359-aa54-8362dae6b232** !"

**Expected behavior**
Hub and both Sales and Engineering sites would provision successfully.

**Screenshots**
N/A

**Details (please complete the following information):**
- PnP Correlation ID: cdd60cab-a043-4359-aa54-8362dae6b232
- Reference Template: https://lookbook.microsoft.com/details/75e60a32-9849-4ed4-b83e-b2b08983ad19
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
First template I've tried to provision.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, you provisioned the same template, targeting the same site URL at the same time, and the service does not support concurrent provisioning of the same template with the same URL. Please try again, avoiding concurrent provisionings.

**Comment by Ukiman1014** [comment]
Hello Paolo,

Hmm, I wonder how that happened.  I remember going to the provisioning
screen, looking at options and going to other screens and coming back, but
I thought I only provisioned once.

Thank you for the response!
-Steve
