### ISSUE TITLE
Unable to provision SharePoint Success Site into M365 Learning Pathways

### ISSUE THREAD

**Issue by dtsmith1984** [SharePoint/sp-provisioning-service#386]
**Describe the issue**
Attempting to add the SharePoint Success Site into M365 Learning Pathways site. Receiving the following error:

Sorry, something went wrong
There was an unexpected issue.
Could not load file or assembly 'OfficeDevPnP.Core, Version=3.28.2012.0, Culture=neutral, PublicKeyToken=5e633289e95c321a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Expected behavior**
Successful Provisioning

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action]
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/0b860749-56a0-4c4c-992c-536d56d9accf
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: YES

**Additional context**

**Comment by pgdrews** [comment]
I had issue #377 open (was closed today) as it seemed issue was resolved.  I've added additional notes/errors on that issue that are occurring now and getting errors.  A colleague of mine had the same error as you (@dtsmith1984) listed above when he tried to provision the Success Site.   

The errors/screenshot I now get are as below:

Custom learning package fails deployment:
![image](https://user-images.githubusercontent.com/7563343/106185958-36931000-6169-11eb-80a2-14e4145abae9.png)

LP site still gets created and you get an email that the provisioning was successful, but get the following errors on the LP site

![image](https://user-images.githubusercontent.com/7563343/106186071-59252900-6169-11eb-9d8d-ad16fd2b0783.png)

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
Failed to load component "c6062b6a-f22c-4475-897b-25081673c54a" (CustomLearningAdminWebPart). Original error: Failed to load URL 'https://tsim365.sharepoint.com/sites/appcatalog/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/webpart-m365lpstrings_en-us_5ebf05c87596e5efe5e691d313907759.js' for resource 'M365LPStrings' in component 'c6062b6a-f22c-4475-897b-25081673c54a' (CustomLearningAdminWebPart). The file was not found in the server.

INNERERROR:
Failed to load URL 'https://tsim365.sharepoint.com/sites/appcatalog/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/webpart-m365lpstrings_en-us_5ebf05c87596e5efe5e691d313907759.js' for resource 'M365LPStrings' in component 'c6062b6a-f22c-4475-897b-25081673c54a' (CustomLearningAdminWebPart). The file was not found in the server.
CALLSTACK:
Error
at t [as constructor] (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6a45ef39ba2a14a973246917083942bc.js:1:874013)
at new t (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6a45ef39ba2a14a973246917083942bc.js:1:1017762)
at Function.e.buildErrorWithVerboseLog (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6a45ef39ba2a14a973246917083942bc.js:1:1040936)
at Function.e.buildLoadComponentError (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6a45ef39ba2a14a973246917083942bc.js:1:1036981)
at https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_06fb90fbb103ba8a0bb1.js:1:66114

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. The issue with the SharePoint Success Site is now fixed. Please, try again and in case of any failure, create another issue. About the issues related to LP, let's refer to #377 . Thanks.
