### ISSUE TITLE
Unable to provision SharePoint Success Site

### ISSUE THREAD

**Issue by siegfriedcw** [SharePoint/sp-provisioning-service#387]
Not getting a correlation ID though. Using the following URL (direct link from lookbook site):
https://lookbook.microsoft.com/details/0b860749-56a0-4c4c-992c-536d56d9accf

When hitting "Add to your tenant" I'm getting the following error on the next page:

Sorry, something went wrong
There was an unexpected issue.
Could not load file or assembly 'OfficeDevPnP.Core, Version=3.28.2012.0, Culture=neutral, PublicKeyToken=5e633289e95c321a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. The issue with the SharePoint Success Site is now fixed. Please, try again and in case of any failure, create another issue.
