### ISSUE TITLE
Your request to provision "Global marketing hub" template failed!

### ISSUE THREAD

**Issue by JanineBoza** [SharePoint/sp-provisioning-service#388]
**Describe the issue**
A clear and concise description of what the issue is.

**Expected behavior**
Installed then deleted and cannot reinstall template even thought so deleted templates
**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action] correlation ID: b8fe123c-fdcc-4a7a-894b-8e1f0ba56f84 !
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/added-115b-e40-469d-9bc0-e91a7bddca19
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant] English
- Are you using a Tenant Global Admin account to provision the template: [Yes/No]
Yes
**Additional context**
I installed then deleted templates from the admin center. The next day tried to reinstall and failed

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
