### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by raviuberatna** [SharePoint/sp-provisioning-service#391]
**Describe the issue**
Please report the issue here providing the following provisioning action correlation ID: 7464bcc6-f26d-4984-9aa9-9a007dbd9365 ! 

**Expected behavior**
Provision Microsoft Learning Pathways Template

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: [7464bcc6-f26d-4984-9aa9-9a007dbd9365 ]
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{Template-ID}]
- Primary language of the target tenant: [English]
- Are you using a Tenant Global Admin account to provision the template: [Yes
[PnP SharePoint Provisiong errors.docx](https://github.com/SharePoint/sp-provisioning-service/files/5894757/PnP.SharePoint.Provisiong.errors.docx)
]

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.

**Comment by raviuberatna** [comment]
Thank you.  Much appreciated.RaviOn Jan 29, 2021 8:50 AM, Paolo Pialorsi <notifications@github.com> wrote:
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
