### ISSUE TITLE
Installation of Microsoft Learning Pathways partially failed

### ISSUE THREAD

**Issue by MelanieTe** [SharePoint/sp-provisioning-service#392]
Problem description: 
In our test tenant I have installed MLP several times without any issues. After deleting all active LP-sites, I installed a fresh new one. This didn't go as normal. This is the error shown on the installation page:

![image](https://user-images.githubusercontent.com/78249123/106349339-838ff700-62cd-11eb-8a83-09f98305fe1e.png)

The expected behavior is that the site gets installed without any problem. 
Instead I received the following email: 
![image](https://user-images.githubusercontent.com/78249123/106349096-53475900-62cb-11eb-8322-1f987debd629.png)

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: e8d7debd-3ca5-4e2b-9916-f1ede44f99d3 !
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239 and then click: Add to your tenant.
- 
![image](https://user-images.githubusercontent.com/78249123/106349366-bfc35780-62cd-11eb-9d12-b4f41d006995.png)

- Primary language of the target tenant: No language selected 
- Are you using a Tenant Global Admin account to provision the template: Yes
- These are the roles, the used account is assigned:
- 
![image](https://user-images.githubusercontent.com/78249123/106349257-f351b200-62cc-11eb-859b-197390d18768.png)

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
