### ISSUE TITLE
Your request to provision  "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by abkamath-cmd** [SharePoint/sp-provisioning-service#393]
**Describe the issue**
Unable to Provision MS Learning Pathways - correlation ID: 5f4c1e47-3795-44d3-b175-126f7b9c4080 !

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: correlation ID: 5f4c1e47-3795-44d3-b175-126f7b9c4080 !
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{Template-ID}] https://lookbook.microsoft.com/tenant/Home/Provision?returnUrl=https%3A%2F%2Flookbook.microsoft.com%2Fdetails%2F3df8bd55-b872-4c9d-88e3-6b2f05344239&source=default
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: [Yes/No]

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, you provisioned the same template, targeting the same site URL at the same time, and the service does not support concurrent provisioning of the same template with the same URL. Please try again, avoiding concurrent provisionings.
