### ISSUE TITLE
SharePoint Provisioning Service Partial field (Department/Product Support ) 

### ISSUE THREAD

**Issue by yota210** [SharePoint/sp-provisioning-service#394]
Hello 

Here providing the following provisioning action correlation  ID: 83a89cc1-f259-4ad9-9568-c0d9eb210649 
![image](https://user-images.githubusercontent.com/75987114/106719236-1fde3480-6613-11eb-927a-af5916a00ed2.png)

Thanks
Dima

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
