### ISSUE TITLE
Your request to provision "New Employee Onboarding Hub"  template failed!

### ISSUE THREAD

**Issue by eliezerbnu** [SharePoint/sp-provisioning-service#395]
**Describe the issue**
Your request to provision "New Employee Onboarding Hub" template failed!
Not make the sites. No working.

**Expected behavior**
success deploy

**Screenshots**
![NEO](https://user-images.githubusercontent.com/53222753/106843875-d4b13980-6685-11eb-8dd4-7157029b4f39.jpg)

**Details (please complete the following information):**
- PnP Correlation ID: e3d27724-7a35-49f3-8615-3a371f79b5ee ! 
- Reference Template: https://lookbook.microsoft.com/tenant/home/provision?packageId=75e60a32-9849-4ed4-b83e-b2b08983ad19&returnUrl=https%3A%2F%2Flookbook.microsoft.com%2Fdetails%2F75e60a32-9849-4ed4-b83e-b2b08983ad19
- Primary language of the target tenant: 1046 | Português (Brasil)
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by eliezerbnu** [comment]
Hello,
I have success on deploy template, but only no customize url.
I use the default url.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
