### ISSUE TITLE
Learning Pathway provisioning error 

### ISSUE THREAD

**Issue by mikeparkie** [SharePoint/sp-provisioning-service#396]
We are attempting to provision the Learning Pathways solution from the SharePoint Lookbook.

It should be a simple click to ingest it into our tenant. I have completed this previously on our test tenant but want to migrate it to our production tenant. I am a SharePoint administrator but not a Global Admin. I have had a GA attempt to provision the template using their credentials, two different GA's now actually. So different machines and different accounts.  

After clicking add to your tenant and confirming the details (name etc) the error presented is:  

`Sorry, something went wrong.
There was an unexpected issue.
Exception while invoking endpoint https://graph.microsoft.com.v1.0/sites/root.
`

Is there a known issue or something we can do to resolve this please? TIA

Requested info from the incident template: 
- PnP Correlation ID: I don't get this far due to the error
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English (GB)
- Are you using a Tenant Global Admin account to provision the template: Yes

Regards, 
Mike Park

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Unfortunately, I don't have enough information to search for this issue in the log. The only idea that pops in my mind is that you did not consent to the provisioning app the needed permissions, and as such the Microsoft Graph request fails. Eventually, try to delete the app "SharePointPnP.ProvisioningApp.Tenant" from AAD in the Enterprise Applications and restart from scratch the provisioning using a Tenant Global Admin account and granting the requested permissions. Thanks for your cooperation.
