### ISSUE TITLE
Wrong content in Microsoft 365 Learning Pathways template

### ISSUE THREAD

**Issue by Gezeitenbrand** [SharePoint/sp-provisioning-service#397]
I was trying to provision the Microsoft 365 learning pathways template from the lookbook. After the provision is done I don't get a notification via email.
The template is provisioned, although the content is not what should be in the template. 
Therefore I can't open CustomLearningAdmin.aspx to initialize learning pathways Admin properties. 

**Expected 

behavior**
I expected the template to provision with the correct content and the possibility to open CustomLearningAdmin.aspx to initialize learning pathways Admin properties. 

**Screenshots**
Expected Learning Template
<img width="633" alt="Expected_Learning_Template" src="https://user-images.githubusercontent.com/58400001/108000104-68b9c400-6fe9-11eb-9f81-7000bff7d5eb.png">

Provisioned Learning Template
<img width="1115" alt="Provisioned_Learning_Template" src="https://user-images.githubusercontent.com/58400001/108000144-86872900-6fe9-11eb-9416-17e1bb40d37a.png">

error message when trying to open CustomLearningAdmin.aspx
<img width="720" alt="Error_Learning_Template" src="https://user-images.githubusercontent.com/58400001/108000194-a4ed2480-6fe9-11eb-9f9a-65165da937c5.png">

**Details (please complete the following information):**
- PnP Correlation ID: I don't get an ID, because I don't get an error notification
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Inspecting the event log, it looks like the provisioning was stuck trying to upload the Learning Pathways app into the app catalog. Could you please verify that you have proper access to the app catalog? And if you have proper access, please try to remove the SPPKG file (if already there) and restart the provisioning from scratch. In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
