### ISSUE TITLE
NewEmployee Onboarding Hub

### ISSUE THREAD

**Issue by Seanfh** [SharePoint/sp-provisioning-service#399]
I have been trying to install the new employee onboarding hub for my company and I am receiving partial fail error : 51bc320e-e717-4e90-be9b-00f4616917b1 !

I expected provisions to download and install the site as per git hub guideline.

I am quite a note with this kind of stuff so any help is very much welcome!

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action]
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/tenant/Home/Provision?returnUrl=https%3A%2F%2Flookbook.microsoft.com%2Fdetails%2F75e60a32-9849-4ed4-b83e-b2b08983ad19&source=default
- 
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Inpsecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while creating the target site (the exception was 403 - "Forbidden"). Could you please try to provision the solution to a different site URL or with a different user account? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
