### ISSUE TITLE
Your request to provision  "Leadership Connection"  template failed!

### ISSUE THREAD

**Issue by nilang-shah** [SharePoint/sp-provisioning-service#400]
SharePoint Provisioning Service

**Your request to provision"Leadership Connection"template failed!**

Please report the issue here providing the following provisioning action correlation ID: f806cb01-11c1-4ac3-949f-927b6b21d37a !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, you provisioned the same template, targeting the same site URL at the same time, and the service does not support concurrent provisioning of the same template with the same URL. Please try again, avoiding concurrent provisionings.
