### ISSUE TITLE
Your request to provision  "Staff home page"  template failed!

### ISSUE THREAD

**Issue by leeseetja** [SharePoint/sp-provisioning-service#403]
My attempt to provision the "staff home page" template failed.

The error emailed asked that I provide the following provisioning action correlation ID: 2ce4d6cb-f826-475b-ac81-b0b19db47685 !

Thanks in advance.

**Comment by maniraj-dev** [comment]
someone please help me . Details : 

correlation ID: 113cb2b0-52c3-4c86-9dca-827bbc862ce7 ! 


Thanks in advance

**Comment by progahmed1** [comment]
Your request to provision

"School home page"

template failed!

Please report the issue here providing the following provisioning action correlation ID: f0f37a8f-92dd-47ad-8f87-d3c581054dba !

**Comment by PaoloPia** [comment]
Hi @leeseetja,
Thanks for using the Look Book site. Inspecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while configuring the target site (the exception was "Access denied. You do not have permission to perform this action or access this resource."). Could you please try to provision the solution to a different site URL or with a different user account? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.

About your exception @maniraj-dev: in the log we see 403 - "Forbidden". Could you please try to provision the solution to a different site URL or with a different user account? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks.

About your exception @progahmed1: based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks.
