### ISSUE TITLE
Your request to provision “Human resources hub” template failed! Correlation ID: 1c8eae7b-699d-453c-912c-f277fc25096f !

### ISSUE THREAD

**Issue by rarmont** [SharePoint/sp-provisioning-service#405]
**Describe the issue**

Your request to provision"Human resources hub" template failed! Please report the issue here providing the following provisioning action correlation ID: 1c8eae7b-699d-453c-912c-f277fc25096f
--
Please provide use feedback around your used template or the service in general by using our feedback form . Thank you for your input advance.

**Expected behavior**
Provisioning for other sites were successful using the same global admin account, so expected behavior was to provision the site. 

**Screenshots**
![9411F64B-0633-4602-9181-0A56BAEEDC2E](https://user-images.githubusercontent.com/26283018/109907223-8339a180-7c67-11eb-8f81-c36a99ae0d0d.png)
![1774C738-39B5-44AB-9751-FCF5E71813CA](https://user-images.githubusercontent.com/26283018/109907224-83d23800-7c67-11eb-9e9e-df120910266e.png)
![E84A5776-F000-4DFD-94CB-76890EFE5B4C](https://user-images.githubusercontent.com/26283018/109907226-846ace80-7c67-11eb-9da3-1ae94fc189f7.png)

**Details (please complete the following information):**
- PnP Correlation ID: 1c8eae7b-699d-453c-912c-f277fc25096f
- Reference Template: https://lookbook.microsoft.com/details/ebb9432c-3bbd-4f64-8f74-e75a8b4f96de
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
Exception: The remote server returned an error: (403) Forbidden.
Provisioning action correlation ID: 1c8eae7b-699d-453c-912c-f277fc25096f

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
