### ISSUE TITLE
Tried to provision a template but it keeps failing

### ISSUE THREAD

**Issue by bbarnwell** [SharePoint/sp-provisioning-service#408]
**Describe the issue**
A clear and concise description of what the issue is.

**Expected behavior**
A successful provision of the school template.

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: 913cb317-c30d-4329-85bb-51519241bc0b 
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/44dc3585-9140-4183-81fc-bdb057f71ac1
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: No

**Additional context**
Each time it fails, I delete the site, try again and it fails again.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Inspecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while configuring the target site (the exception was "Access denied. You do not have permission to perform this action or access this resource."). Could you please try to provision the solution to a different site URL or with a different user account? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
