### ISSUE TITLE
Provisioning failing and failing over again : 2668b88d-f90a-486d-86bf-290595f77561

### ISSUE THREAD

**Issue by AndreMustang74** [SharePoint/sp-provisioning-service#409]
Your request to provision   "News site"    template failed!   Please report   the issue here providing the following provisioning action correlation   ID: 2668b88d-f90a-486d-86bf-290595f77561 !
--
Please provide use feedback around your used template or the   service in general by using our feedback form . Thank you for your   input advance.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Inspecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while trying to access the target site (the exception was 403 - "Forbidden"). Could you please try to provision the solution to a different site URL or with a different user account? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
