### ISSUE TITLE
provisioning Multiple learning Path for single tenant

### ISSUE THREAD

**Issue by Mandyhdxc** [SharePoint/sp-provisioning-service#41]
Can we provision multiple learning path for single office 365 Tenant? any article or info on this?

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. Yes you can.

**Comment by juliemturner** [comment]
Actually, you cannot... you can only provision learning pathways into one site collection... technically you can do it more than once but the solution won't work.

**Comment by PaoloPia** [comment]
Ops ... thanks @juliemturner for the additional info.
