### ISSUE TITLE
	 Unfortunately your site provisioning at least partially failed!

### ISSUE THREAD

**Issue by skhrushchev** [SharePoint/sp-provisioning-service#410]
I followed all rules to upgrade my existing SharePoint site https://satbayevuniversity.sharepoint.com/sites/PLC with the templates number two (for teachers) and the process failed with these codes 
Please report the issue here providing the following provisioning action correlation ID: 378d8688-4f1d-43de-8321-e5dddd2038ab ! 
<img width="1452" alt="Screenshot 2021-03-06 102120" src="https://user-images.githubusercontent.com/80141378/110194985-d0836200-7e65-11eb-9daf-cdc5396916c1.png">
<img width="1192" alt="Screenshot 2021-03-06 102130" src="https://user-images.githubusercontent.com/80141378/110194990-d711d980-7e65-11eb-8a9c-2916c134d641.png">

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Inspecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while trying to access the target site (the exception was 403 - "Forbidden"). Could you please try to provision the solution to a different site URL or with a different user account? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
