### ISSUE TITLE
lookbook provisioning failed 

### ISSUE THREAD

**Issue by nanabonsu123** [SharePoint/sp-provisioning-service#412]
Hi, 

I tried to activate a tenant and the following provisioning error message appeared: 

Your request to provision
"Staff home page" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: 51d9bcb9-2ae9-4df0-952d-2d6af915e538 ! 

Please  help, 

Many thanks 

Nana

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Inpsecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while creating the target site (the exception was 403 - "Forbidden"). Could you please try to provision the solution to a different site URL or with a different user account? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
