### ISSUE TITLE
SPS School Site failed

### ISSUE THREAD

**Issue by regthaman88** [SharePoint/sp-provisioning-service#413]
daafe75a-7843-4380-835c-b5ab8323c4ba

**Comment by PaoloPia** [comment]
Thanks for using the Look Book site. Inspecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while configuring the target site (the exception was "Access denied. You do not have permission to perform this action or access this resource."). Could you please try to provision the solution to a different site URL or with a different user account? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.

**Comment by PaoloPia** [comment]
Hi,
After further investigation, the problem could be a regression on the API side. We're investigating the problem. I've re-opened the issue and I will let you know. Thanks for your cooperation.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We investigated the issue and we found a fix to the regression. Could you please try to provision the solution again, eventually to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
