### ISSUE TITLE
"School home page" template provision failed

### ISSUE THREAD

**Issue by ipats86** [SharePoint/sp-provisioning-service#414]
**Describe the issue**
We are trying to deploy the "School home page" template in our tenant and after a couple of minutes we get the below error message:

"Your request to provision"School home page"template failed!"

**Expected behavior**
Deploy the site without the error message.

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: e2bf544a-43e7-4fdb-b375-308f6c05305f
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/44dc3585-9140-4183-81fc-bdb057f71ac1
- Primary language of the target tenant: EN-US
- Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by PaoloPia** [comment]
Thanks for using the Look Book site. Inspecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while configuring the target site (the exception was "Access denied. You do not have permission to perform this action or access this resource."). Could you please try to provision the solution to a different site URL or with a different user account? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.

**Comment by ipats86** [comment]
Hello Paolo. Thanks a lot for your answer.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We investigated the issue and we found a fix to the regression. Could you please try to provision the solution again, eventually to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
