### ISSUE TITLE
"Leadership Connection"  template failed!

### ISSUE THREAD

**Issue by edsonfarias** [SharePoint/sp-provisioning-service#415]
It's not possible create site.
I tried several templates, but some error.
I have permission, and I alread  created many sites

**Details (please complete the following information):**
- PnP Correlation ID:  a0550d6b-a629-43b1-a200-6ca0e9e0dcc3
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/c19f437b-35ca-42f2-b27a-1caa49ad8bde

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Inspecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while creating the target Communication Site (the exception was 403 - "Forbidden"). We investigated the issue and we found a fix. Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
