### ISSUE TITLE
Provisioning failed consistently

### ISSUE THREAD

**Issue by kris552** [SharePoint/sp-provisioning-service#418]
Your request to provision
"Benefits"
template failed!
Please report the issue here providing the following provisioning action correlation ID: d75d6ec5-2de5-405d-a04b-31192e4938c0 !

- Reference Template: https://lookbook.microsoft.com/details/bb8e1900-b40f-4791-b667-f963af651111
- Primary language of the target tenant: english
- using a Tenant Global Admin account to provision the template: yes

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
