### ISSUE TITLE
Your request to provision "Global sales hub"  template failed!

### ISSUE THREAD

**Issue by BrettBluePearl** [SharePoint/sp-provisioning-service#419]
**Describe the issue**
Your request to provision
"Global sales hub" 
template failed!

**Expected behavior**
Success

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: correlation ID: b9642847-be0a-4b89-abd7-32c6d7c012be ! 
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/4541e5c4-dff6-4cd7-87be-4646b56d6000
- Primary language of the target tenant: US English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
