### ISSUE TITLE
Example config files

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-provisioning-service#42]
Whilst I acknowledge its good practice to omit app/web config files from the project, however could you add sample config files in order to understand what keys and config is required in the projects for this to run in our own environments?

**Comment by PaoloPia** [comment]
Hi @pkbullock,
Thanks for your feedback. Actually, there sample config files in all the project that require a config file.

**Comment by pkbullock** [comment]
Ah I see how I missed them XXX-Model.config, some are referenced in the project  some are not e.g. SharePointPnP.ProvisioningApp.WebJob - my bad.
