### ISSUE TITLE
Provisioning Status - Unfortunately your site provisioning at least partially failed!

### ISSUE THREAD

**Issue by gfinberg** [SharePoint/sp-provisioning-service#423]
Hi, am trying to provision a template from the lookbook. I am logged in as Global Admin.

The process fails with:
Provisioning Status - Unfortunately your site provisioning at least partially failed!

Your request to provision "Mark8 Project Team" template failed!
Please report the issue here providing the following provisioning action correlation ID: 4bf7256e-b122-4e38-b0e6-afeba4917897 ! 

Please advise
Thanks
Gary

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
