### ISSUE TITLE
How to revoke permissions granted to SharePointPnP.ProvisioningApp.Tenant?

### ISSUE THREAD

**Issue by Kikaider** [SharePoint/sp-provisioning-service#424]
How do I, as a tenant admin, revoke permissions or delete the SharePointPnP.ProvisioningApp.Tenant app from https://myapplications.microsoft.com/?

![Screenshot 2021-03-23 114021](https://user-images.githubusercontent.com/19256231/112176554-912b7400-8bce-11eb-83af-93ebff26aa21.png)

**Comment by PaoloPia** [comment]
Hi,
If you go to portal.azure.com and you select "Azure Active Directory", from "Enterprise Applications" you should be able to find and remove the SharePointPnP.ProvisioningApp.Tenant application.
