### ISSUE TITLE
Provisioning template Crisis Management fails partially

### ISSUE THREAD

**Issue by jalbers55** [SharePoint/sp-provisioning-service#425]
**Describe the issue**
There was an unexpected issue.
IDX21323: RequireNonce is '[PII is hidden]'. OpenIdConnectProtocolValidationContext.Nonce was null, OpenIdConnectProtocol.ValidatedIdToken.Payload.Nonce was not null. The nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'. Note if a 'nonce' is found it will be evaluated.

**Details (please complete the following information):**
- PnP Correlation ID: d25b6956-dabd-4cfc-a83a-cbc5e4e612da
- Reference Template: https://lookbook.microsoft.com/details/8f8337d2-b1f6-4a84-91a4-9081f841f0f6
- Primary language of the target tenant: 1033
- Are you using a Tenant Global Admin account to provision the template: [Yes]

**Comment by jalbers55** [comment]
despite the error I noticed that the provisioning ended successfully afterall!

**Comment by PaoloPia** [comment]
Thanks for the update. I'll close the item.
