### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by OrigamiPhil** [SharePoint/sp-provisioning-service#426]
**Describe the issue**
Tried to provision the M365 learning pathway via LookBook and get the above message.

**Expected behavior**
The template to be deployed successfully.

**Screenshots**

**Details (please complete the following information):**
Correlation ID: 38fdf273-7013-4dc7-b715-7d2f2891ab37
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
I have removed the tenant level Enterprise Application from Azure, deleted the app from the Catalog site and tried again with the same result.

I did have an old v2 version of the learning pathways, and have deleted that site and the app before trying to install the new v4 version (I wasn't worried about keeping any of the old stuff).

**Comment by OrigamiPhil** [comment]
I've checked this morning, and the site was created, but some of the menu options are in a foreign language:
![image](https://user-images.githubusercontent.com/55708540/112609860-f623db80-8e13-11eb-979c-680acb47a802.png)
And there seem to be a bunch of menu options missing.

I have installed Learning Pathways in a different tenant successfully this morning, so there must be something specific to this tenant that is causing it to fail/behave strangely.

**Comment by OrigamiPhil** [comment]
Is there anyone looking at these issues and able to assist with them?

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Inspecting the event log, we can see - based on the provided Correlation ID - that there was an exception while provisioning the navigation of the site. It is an uncommon issue. Considering that you were able to provision the template onto another tenant, what kind of tenant is this? Is it a demo tenant for partners? Thanks for your cooperation.

**Comment by OrigamiPhil** [comment]
The tenant with the failure is my employers tenant. The successful tenant is my personal one. There are no demo/partner tenants.

**Comment by OrigamiPhil** [comment]
Is this still being investigated?

**Comment by PaoloPia** [comment]
Hi,
We've recently seen some provisioning processes failing during the creation of the navigation nodes. We're investigating the issue and we will eventually fix it, in case it depends on our codebase. Stay tuned. Thanks for your cooperation.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.
