### ISSUE TITLE
SharePointSuccessSite Provisioning failed correlation ID: 81323735-fe73-4252-962b-73d5ebcb0338

### ISSUE THREAD

**Issue by ken-hansen-rga** [SharePoint/sp-provisioning-service#427]
**Describe the issue**
Provisioning from Look Book fails, notification comes by email with a correlation ID. The Site Collection was created, but some of the links are showing Italian in the EN-US site
![image](https://user-images.githubusercontent.com/61423243/112523951-4dbb3c00-8d6d-11eb-868c-1b02eb31f1fb.png)

The pages seem to have been created and the Learning Webparts are working, but the Navigation is not complete and I am not sure what else may have failed.

**Expected behavior**
Expected the site to be fully provisioned.

**Screenshots**
![image](https://user-images.githubusercontent.com/61423243/112523621-f321e000-8d6c-11eb-90ce-549bc6e5fdaa.png)

**Details (please complete the following information):**
- PnP Correlation ID: 81323735-fe73-4252-962b-73d5ebcb0338
- Reference Template: https://lookbook.microsoft.com/details/0b860749-56a0-4c4c-992c-536d56d9accf
- Primary language of the target tenant: 1033
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. We've recently seen some provisioning processes failing during the creation of the navigation nodes. We're investigating the issue and we will eventually fix it, in case it depends on our codebase. Stay tuned. Thanks for your cooperation.

**Comment by vishalbsacet** [comment]
I am also getting the same problem... is there any ETA for it

![image](https://user-images.githubusercontent.com/69198450/115585821-983ac480-a2e9-11eb-8b33-804026748540.png)

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.
