### ISSUE TITLE
Your request to provision "Sharepoint site" template failed

### ISSUE THREAD

**Issue by aoden555** [SharePoint/sp-provisioning-service#428]
**Describe the issue**
Can't apply the sharepoint lookbook template to create sharepoint site

**Expected behavior**
Sharepoint site with lookbook template is created successfully
**Screenshots**
![image](https://user-images.githubusercontent.com/13504497/112782259-cb858d00-9076-11eb-8780-b8aaba7f3787.png)
![image](https://user-images.githubusercontent.com/13504497/112782284-db04d600-9076-11eb-9f76-d33ef2c836d5.png)

- PnP Correlation ID: 401b3a1c-28c8-4002-af76-a80549587476
- Reference Template: https://lookbook.microsoft.com/details/ebb9432c-3bbd-4f64-8f74-e75a8b4f96de
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
