### ISSUE TITLE
Your request to provision  "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by km1727** [SharePoint/sp-provisioning-service#429]
The  Learning Pathway provisioning FAILED

**Details (please complete the following information):**
- PnP Correlation ID: d9b7cfd5-d0f4-4875-ae44-6f3f961592b9
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: ENGLISH
- Are you using a Tenant Global Admin account to provision the template: YES

**Additional context**
I see the site getting created in the SP admin center with NO additional pages except the home page.
BUT, the provisioning process gives this message followed by FAILURE email. "Unfortunately your site provisioning at least partially failed!"

**Comment by km1727** [comment]
Is there anyone looking at these issues and able to assist with them?

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. We've recently seen some provisioning processes failing during the creation of the navigation nodes. We're investigating the issue and we will eventually fix it, in case it depends on our codebase. Stay tuned. Thanks for your cooperation.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.
