### ISSUE TITLE
template failed!

### ISSUE THREAD

**Issue by silcarr** [SharePoint/sp-provisioning-service#431]
Please report the issue here providing the following provisioning action correlation ID: a90ff4b0-1592-4645-a9bf-fce5b1ed5204 ! 

I am trying to deploy  "the landing template" to a team site. However, I can't get it to work. 

![sharepoint](https://user-images.githubusercontent.com/81645525/113036362-6bafe480-9151-11eb-9399-f33604b38540.PNG)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. As per the message, you are targeting an already existing site created with the wrong template. Please try providing the URL of a not existing site, and the service will create it for you with the correct template. Thanks.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. I'm going to close this item because you did not reply back after 10 days. Please, feel free to try again the template and to create another issue, providing the Correlation ID of the request, for further investigation. Thanks for your feedback.
