### ISSUE TITLE
Template failed (schools home page)

### ISSUE THREAD

**Issue by gkim28** [SharePoint/sp-provisioning-service#433]
**Describe the issue**
Every time I try to provision this template, it fails but it doesn't if the link name is different. I think the problem might be because I refreshed the page in the middle of provisioning, but I made sure not to visit the link because I didn't want to affect the provisioning process. However, I refreshed it because I got no notification of completion, and it had been at least 20 minutes "provisioning". 

**Expected behavior**
I expected the template to be successfully provisioned. I now only get notifications to email that the template failed to work.

**Screenshots**

<img width="1440" alt="Screen Shot 2021-03-31 at 9 49 22 PM" src="https://user-images.githubusercontent.com/81724721/113232727-b58ced80-926b-11eb-8df2-76556e050fd1.png">

**Details (please complete the following information):**
- PnP Correlation ID: ID: 5ab8aded-4847-436d-b94a-b2df5826c053 !
- Reference Template: https://lookbook.microsoft.com/details/44dc3585-9140-4183-81fc-bdb057f71ac1
- Primary language of the target tenant: ENU
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, you provisioned the same template, targeting the same site URL at the same time, and the service does not support concurrent provisioning of the same template with the same URL. Please try again, avoiding concurrent provisionings.
