### ISSUE TITLE
ISSUE: "Global marketing hub" template failed!

### ISSUE THREAD

**Issue by JanineVogler** [SharePoint/sp-provisioning-service#434]
**Describe the issue**
I get an email which is saying: Your request to provision
"Global marketing hub" template failed!

**Expected behavior**
I´d like to use the template.

**Screenshots**
![Bildschirmfoto 2021-04-01 um 09 36 34](https://user-images.githubusercontent.com/81697661/113259843-e00f9280-92cd-11eb-810f-a6b5d8e64e3f.png)

**Details (please complete the following information):**
- PnP Correlation ID: [6e216bb5-cfc1-48f4-b4ea-2d5f5f1236e0]
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: 
- https://lookbook.microsoft.com/details/abef115b-e40e-469d-9bc0-e91a7bddca19
- Primary language of the target tenant: [English]
- Are you using a Tenant Global Admin account to provision the template: [Yes/No] Not sure. I tried the Team collaboration site (https://lookbook.microsoft.com/details/4bcbc663-5140-47ef-b90d-af05f16af828) template and that works just fine. 

THX Janine

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Inpsecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while creating the target Communication Site (the exception was 403 - "Forbidden"). Could you please try to provision the solution to a different site URL or with a different user account? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
