### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by degreene** [SharePoint/sp-provisioning-service#442]
**Describe the issue**
Attempted to deploy the M365 Learning pathways

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action] 
**- correlation ID: 64be9bbe-69c4-4b23-8ad9-632080fac3d2 
- correlation ID: 91452283-250f-4c60-a586-cf42fcbe7d7b ! 
- correlation ID: 64be9bbe-69c4-4b23-8ad9-632080fac3d2 !** 
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{Template-ID}]
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: [Yes/No]

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you provided the URL of a site that is not in SharePoint Online or you are targeting a tenant with a vanity domain, which is unfortunately not supported by the Provisioning Service. Eventually, you can manually apply the template with PowerShell, using the source .PNP package file available in this repository: https://github.com/sharepoint/sp-dev-provisioning-templates.  In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
