### ISSUE TITLE
Learning Pathways Installation Fails. Correlation ID 7e08d1bf-3496-4f92-9659-6b00b22cb4e7

### ISSUE THREAD

**Issue by LiamJHarrisonDemo** [SharePoint/sp-provisioning-service#444]
Trying to install Learning Pathways on a Microsoft demo environment. Have set up an app catalog.

Receive the following email:

Your request to provision "Microsoft 365 learning pathways" template failed!
Please report the issue here providing the following provisioning action correlation ID: 7e08d1bf-3496-4f92-9659-6b00b22cb4e7 

A search for that correlation ID came back with nothing.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. We've recently seen some provisioning processes failing during the creation of the navigation nodes. We're investigating the issue and we will eventually fix it, in case it depends on our codebase. Stay tuned. Thanks for your cooperation.

**Comment by LiamJHarrisonDemo** [comment]
I made another attempt and have another correlation ID if it helps :) 
correlation ID: c75d01ee-7872-4b2e-bf35-ec3fc64cccf3

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.
