### ISSUE TITLE
Failed to provision learning pathway

### ISSUE THREAD

**Issue by ahmedbahbah2** [SharePoint/sp-provisioning-service#445]
**Describe the issue**
Your request to provision

"Microsoft 365 learning pathways"

template failed!

Please report the issue here providing the following provisioning action correlation ID: 7dbec001-0b89-47e6-bf57-9196716744e7 
**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action]
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{Template-ID}]
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: [Yes/No]

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. We've recently seen some provisioning processes failing during the creation of the navigation nodes. We're investigating the issue and we will eventually fix it, in case it depends on our codebase. Stay tuned. Thanks for your cooperation.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.
