### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by thomas-bak** [SharePoint/sp-provisioning-service#446]
**Describe the issue**
Deployed the M365 Learning Pathways solution to our company tenant.

**Expected behavior**
Successful deployment

**Screenshots**
Got an e-mail stating the following:
"Please report the issue here providing the following provisioning action correlation ID: 3623582d-e272-4596-b8ab-65493ba98f90 !"

**Details (please complete the following information):**
- PnP Correlation ID: 3623582d-e272-4596-b8ab-65493ba98f90
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
Top menu was in Dutch even though English was the selected language on the site.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. We've recently seen some provisioning processes failing during the creation of the navigation nodes. We're investigating the issue and we will eventually fix it, in case it depends on our codebase. Stay tuned. Thanks for your cooperation.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.
