### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by toddstr** [SharePoint/sp-provisioning-service#447]
Describe the issue: Deployed the M365 Learning Pathways solution to our company tenant.

Expected behavior: Successful deployment

On the site while provisioning it stated: 
Provisioning Status - Unfortunately your site provisioning at least partially failed!

Received an e-mail stating the following:
"Please report the issue here providing the following provisioning action correlation ID: 01ff2297-54ad-41e6-9e37-7a7252439331 !"
Subsequent attempts also resulted in correlation IDs:
0453ff5a-94be-48c1-aebf-de5c0500132b
79f73786-c08a-49e8-b82a-e3ca7ae06d26

Details (please complete the following information):

PnP Correlation ID: 01ff2297-54ad-41e6-9e37-7a7252439331
Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
Primary language of the target tenant: English
Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Inpsecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while creating the target Communication Site (the exception was 403 - "Forbidden"). Could you please try to provision the solution to a different site URL or with a different user account? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
