### ISSUE TITLE
Provisioning Error

### ISSUE THREAD

**Issue by mosoccer** [SharePoint/sp-provisioning-service#448]
Trying to provision a lookbook template and getting a provision error:

Correlation ID: 1eb79884-7203-4fd9-afb5-413d788d47b4 !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
