### ISSUE TITLE
Global Marketing Hub Template failed

### ISSUE THREAD

**Issue by OnlineIS** [SharePoint/sp-provisioning-service#449]
**Describe the issue**
Provisioning from lookbook Global marketing Hub failed

**Expected behavior**
Expected success in provisioning

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: 20e95794-b902-4816-98c2-aca8c123eebd ! 
- Reference Template: https://lookbook.microsoft.com/details/abef115b-e40e-469d-9bc0-e91a7bddca19
- Primary language of the target tenant: English US
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
