### ISSUE TITLE
Provisioning error

### ISSUE THREAD

**Issue by prvanbeek** [SharePoint/sp-provisioning-service#450]
correlation ID: 0b4bf6fa-aaae-4d33-81b3-528819cd334e

**Comment by prvanbeek** [comment]
Second attempt gave this correlation ID: cc92d970-198d-4414-899d-76fb26fb974d !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that for 0b4bf6fa-aaae-4d33-81b3-528819cd334e you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. While for cc92d970-198d-4414-899d-76fb26fb974d we've recently seen some provisioning processes failing during the creation of the navigation nodes. We're investigating the issue and we will eventually fix it, in case it depends on our codebase. Stay tuned. Thanks for your cooperation.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.
