### ISSUE TITLE
Provisioning issue

### ISSUE THREAD

**Issue by arunkalloor** [SharePoint/sp-provisioning-service#452]
**Describe the issue**
Unfortunately your site provisioning at least partially failed!

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/62326677/114977633-9dd97a00-9ea5-11eb-9aa9-4309909e749b.png)

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action]
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{Template-ID}]
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: [Yes/No]

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Please, share the Correlation ID of the provisioning that failed so that we can investigate the log. I will close this item, create a new one with the correct information. Thanks.
