### ISSUE TITLE
Provisioning Issue 

### ISSUE THREAD

**Issue by mazettl** [SharePoint/sp-provisioning-service#453]
<img width="315" alt="Capture" src="https://user-images.githubusercontent.com/82711876/115113923-bc4d7d00-9f5a-11eb-94f9-b29e502248d2.PNG">
<img width="740" alt="Capture 1" src="https://user-images.githubusercontent.com/82711876/115113950-d2f3d400-9f5a-11eb-923d-1feef450acee.PNG">

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.

**Comment by mazettl** [comment]
We have tried several different URL's with the same result time and time again. Do you have any other suggestions?

Marc A. Zettl

Please take a moment to review our service!<https://g.page/r/CSVlSfMzqqZIEAI/review>

[ASZ Logo - Email Signature (Marc Zettl)]
[facebook]<https://www.facebook.com/ASZInsurance/>[twitter]<https://twitter.com/ASZAssociates> [linkedin] <https://www.linkedin.com/company/asz-international-inc-/>  [youtube] <https://www.youtube.com/channel/UCkIzuBtj7PRss3ZrSBQoT5g/featured>  ***@***.***D734E5.3DF96A70] <https://www.instagram.com/ez_insurance/>
[signature_630658492]

**Comment by mazettl** [comment]
[cid:fdcc69d3-4eba-4a86-a9f9-ec8f14571ab5]

Marc A. Zettl

Office:  800.694.0279
Fax:  800.926.9279
***@***.***
www.aszinternational.com

________________________________
From: Marc Zettl
Sent: Monday, April 19, 2021 2:39 PM
To: SharePoint/sp-provisioning-service ***@***.***>; SharePoint/sp-provisioning-service ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [SharePoint/sp-provisioning-service] Provisioning Issue (#453)


We have tried several different URL’s with the same result time and time again. Do you have any other suggestions?



Marc A. Zettl



Please take a moment to review our service!<https://g.page/r/CSVlSfMzqqZIEAI/review>



[ASZ Logo - Email Signature (Marc Zettl)]

[facebook]<https://www.facebook.com/ASZInsurance/>[twitter]<https://twitter.com/ASZAssociates> [linkedin] <https://www.linkedin.com/company/asz-international-inc-/>  [youtube] <https://www.youtube.com/channel/UCkIzuBtj7PRss3ZrSBQoT5g/featured>  ***@***.***D734E5.3DF96A70] <https://www.instagram.com/ez_insurance/>

[signature_630658492]
