### ISSUE TITLE
Microsoft 365 Learning Pathway failed

### ISSUE THREAD

**Issue by Sthitodhi** [SharePoint/sp-provisioning-service#454]
**Describe the issue**
The provisioning for M365 learning pathway failed with the error message "Unfortunately your site provisioning at least partially failed!"

**Expected behavior**
M365 learning pathway to be provisioned successfully

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: de730535-1b2d-451d-b315-ae0f21e38152
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{3df8bd55-b872-4c9d-88e3-6b2f05344239}]
- Primary language of the target tenant: [English]
- Are you using a Tenant Global Admin account to provision the template: [Yes]

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
