### ISSUE TITLE
Provisioning Error

### ISSUE THREAD

**Issue by Lilian1331** [SharePoint/sp-provisioning-service#455]
correlation ID: 6daed2f1-e189-446a-a0be-b6d1de9b0cf4
Please help. I have confirmed that no current site has the same URL and my recycle bin of "Deleted Site" is empty.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
