### ISSUE TITLE
WORKPLACE TRANSFORMATION SITE provisioning failed

### ISSUE THREAD

**Issue by hrfmjp** [SharePoint/sp-provisioning-service#456]
Workplace Transformation site
https://lookbook.microsoft.com/details/b0633491-127d-48bf-ba06-a0cdb6ec749f

correlation ID: 535669f4-a7cf-4232-b488-dbca890d4ba3

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
