### ISSUE TITLE
Provisioning Error

### ISSUE THREAD

**Issue by Lilian1331** [SharePoint/sp-provisioning-service#457]
**Describe the issue**
correlation ID: 1bd3ab21-736d-4b15-827c-c6f18aa27eac 

I have deleted the app and check with the powershell Get-SPOSite -Identity <My Site URL> to check whether there is any same existing link and no site is returned. So I can make sure that I have completely delete the site. Please help.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. I see that this time the provisioning started and the site got created. Unfortunately, the provisioning failed while uploading an image file, which is something that every now and then happens. The only thing you can do is to try again (remember to delete the site and empty the recycle bin before resubmitting the provisioning of the same site URL) and hopefully it will work. If not, please create another issue, still providing the Correlation Id, and we will do our best to see if there is anything else that we can do to help you. Thanks for your cooperation.

**Comment by Lilian1331** [comment]
> Hi,
> Thanks for using the Look Book site. I see that this time the provisioning started and the site got created. Unfortunately, the provisioning failed while uploading an image file, which is something that every now and then happens. The only thing you can do is to try again (remember to delete the site and empty the recycle bin before resubmitting the provisioning of the same site URL) and hopefully it will work. If not, please create another issue, still providing the Correlation Id, and we will do our best to see if there is anything else that we can do to help you. Thanks for your cooperation.

Thanks @PaoloPia is there anyway we can see the log for our own site. it is better if we can trouble shoot by ourselves
