### ISSUE TITLE
Your request to provision  "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by Dyermull** [SharePoint/sp-provisioning-service#458]
**Describe the issue**
Tried to provision M365 Learning pathways site and received this email/error

**Expected behavior**
A provisioned M365 Learning pathways site without error

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: 8cc07f88-e9a3-40fd-891e-d425bc0eefb7 
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
The provisioning page displayed this status message: Unfortunately your site provisioning at least partially failed!

and then received this email:

Your request to provision"Microsoft 365 learning pathways"template failed!
Please report the issue here providing the following provisioning action correlation ID: 8cc07f88-e9a3-40fd-891e-d425bc0eefb7 !

I checked the URL of the site and it was created, but there are language issues, with some links being displayed in Dutch and it looks like I'm missing some Multilingual options. I'm not sure what else might be wrong. I followed the instructions from this link: https://docs.microsoft.com/en-us/office365/customlearning/custom_provision

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. We've recently seen some provisioning processes failing during the creation of the navigation nodes. We're investigating the issue and we will eventually fix it, in case it depends on our codebase. Stay tuned. Thanks for your cooperation.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.
