### ISSUE TITLE
Your request to provision "The Landing"  template failed!

### ISSUE THREAD

**Issue by ChadWBrown** [SharePoint/sp-provisioning-service#459]
I am a global admin and I have used the lookbook provisioning before but I am getting this error trying to deploy "The Landing" template

Your request to provision
"The Landing" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: 91e9b020-4a57-4675-96c7-e3ea84bf22c7 !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
