### ISSUE TITLE
WORKPLACE TRANSFORMATION SITE Provisioning error

### ISSUE THREAD

**Issue by hrfmjp** [SharePoint/sp-provisioning-service#460]
**Describe the issue**
Exception: The remote server returned an error: (400) Bad Request.
Provisioning action correlation ID: 5cba2c1e-4a05-440f-83bf-5256767c5ecb

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
