### ISSUE TITLE
SharePoint PnP Provisioning Service

### ISSUE THREAD

**Issue by GeorgeH88** [SharePoint/sp-provisioning-service#461]
**Describe the issue**
Your request to provision
"Microsoft 365 learning pathways" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: 07739ca6-7fd8-4efe-a2cc-713dfd40ce5a ! 

**Expected behavior**
The template to provision correctly

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: 07739ca6-7fd8-4efe-a2cc-713dfd40ce5a ! 
- Reference Template: https://qehb.sharepoint.com/sites/M365LP
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: [Yes]

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
