### ISSUE TITLE
Your request to provision  "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by Pratik2990** [SharePoint/sp-provisioning-service#462]
Unable to provision Learning pathway template got CID : 36b3c9b6-c043-4d02-8437-91aec6c15c0c !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
