### ISSUE TITLE
Microsoft 365 learning pathways template failed

### ISSUE THREAD

**Issue by aagvae** [SharePoint/sp-provisioning-service#464]
Hi 

I tryed to deploy Microsoft 365 learning path on your tenant.
I got following error:
Your request to provision
"Microsoft 365 learning pathways" 
template failed!

correlation ID: 9c3e4df6-c454-443c-a6eb-4d5870707e37 

please help

**Comment by aagvae** [comment]
It looks like most content got deployed but the two pages CustomLearningAdmins and CustomLearningViewer hav only strange content

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
