### ISSUE TITLE
Your request to provision "The Perspective" template failed!

### ISSUE THREAD

**Issue by Lilian1331** [SharePoint/sp-provisioning-service#472]
Your request to provision "The Perspective" template failed!
Correlation ID: c368a798-0c51-4076-b886-7a8a435f96e2 !

Please help

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
