### ISSUE TITLE
Your request to provision "Microsoft 365 freelance communications site" template failed!

### ISSUE THREAD

**Issue by thompsonsimon** [SharePoint/sp-provisioning-service#473]
**Describe the issue**

Your request to provision
"Microsoft 365 freelance communications site"
template failed!
Please report the issue here providing the following provisioning action correlation ID: c2d3d4cf-c9dd-46e1-b607-b62263b8cb25 !

Please provide use feedback around your used template or the service in general by using our feedback form . Thank you for your input advance.

Exception: The given key was not present in the dictionary.
Provisioning action correlation ID: c2d3d4cf-c9dd-46e1-b607-b62263b8cb25

**Expected behavior**
It should have worked

**Details (please complete the following information):**
c2d3d4cf-c9dd-46e1-b607-b62263b8cb25
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/5789b2a7-f119-4135-b909-aa138382be07
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
This is not the first time Lookbook provisioning has failed on this tenant

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
