### ISSUE TITLE
Learning Pathways Site not provisioning

### ISSUE THREAD

**Issue by mcollins-hub** [SharePoint/sp-provisioning-service#474]
**Describe the issue**
Learning Pathways Site not provisioning. Getting Unfortunately your site provisioning at least partially failed!

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/83044202/115797257-1f934100-a399-11eb-8e68-a273933d5daa.png)
![Sharepoint Screenshot 2021-04-13 090902](https://user-images.githubusercontent.com/83044202/115797275-2ae66c80-a399-11eb-9eb6-661222712274.jpg)

[Details](url) (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action]
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{Template-ID}]
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: [Yes/No]

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. In order to investigate the issue and provide feedback, we need the PnP Correlation ID of the provisioning request. Could you please share the Correlation ID? Thanks.

**Comment by exp4bra1n** [comment]
I'm having the same problem, tried 2 times.

PnP Correlation ID: 0e3c467f-ff8f-42be-b0d4-3f56c9bc34c6
Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
Primary language of the target tenant: not sure what the LCID is but the default language is English
Are you using a Tenant Global Admin account to provision the template: **Yes**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
