### ISSUE TITLE
Your request to provision  "Leadership Connection"  template failed!

### ISSUE THREAD

**Issue by NicolasCPearl** [SharePoint/sp-provisioning-service#476]
Your request to provision

"Leadership Connection"

template failed!

Please report the issue here providing the following provisioning action correlation ID: b3d976ff-a51b-483c-8586-5e0261dbbcdc !

Please Help !!!

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
