### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways" template failed!

### ISSUE THREAD

**Issue by PhilipHaglund** [SharePoint/sp-provisioning-service#477]
**Describe the issue**
The Microsoft 365 learning pathways template failed.

**Expected behavior**
Provision without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/14297750/115881243-d819bd00-a44b-11eb-80ae-6a10f78d7bf0.png)

**Details (please complete the following information):**
- PnP Correlation ID: b64eae64-ef3f-4e6f-9fc2-f930b5bb52f1 
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: en-US
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
Nothing

**Comment by renjpk** [comment]
I am having same issue
Your request to provision
"Microsoft 365 learning pathways" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: 0f0331f3-7d02-40e4-89ee-b1e2174401e6 !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
