### ISSUE TITLE
Your request to provision "New employee corporate onboarding site"  template failed!

### ISSUE THREAD

**Issue by wilsonmcgit** [SharePoint/sp-provisioning-service#478]
correlation ID: 1e6af8e8-e47b-4c9f-9241-429bc5ba1219 !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
