### ISSUE TITLE
Provisioning a least partially failed - MICROSOFT 365 LEARNING PATHWAYS

### ISSUE THREAD

**Issue by PeMarcos** [SharePoint/sp-provisioning-service#480]
**Describe the issue**
Provisioning of M365 Learning Pathways was not successfull. Error message: unfortunately your site provisioning at least partially failed

**Expected behavior**
Full provisioning og M365LP

**Screenshots**
none

**Details (please complete the following information):**
- PnP Correlation ID: 9c532797-cfad-4a41-bdba-d0539afba5eb
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English, 1033
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PeMarcos** [comment]
Second try, we have made further progress in the provision of M365LP, but still a partial failure: 

- PnP Correlation ID: 282bc78d-7bac-4b7e-b45e-df17fac17126

**Comment by ChrisSidebotham** [comment]
Same thing here - partial failiure when deploying correlation ID: 4b3a112b-7dc9-4b43-bb51-c04b81498641

**Comment by PeMarcos** [comment]
> Same thing here - partial failiure when deploying correlation ID: 4b3a112b-7dc9-4b43-bb51-c04b81498641

Hi Chris, just to let u know: I decided to move on with a manual provisioning as described here: https://docs.microsoft.com/en-us/office365/customlearning/custom_manualsetup. this worked fine for me.

cheers
Pedro

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. We've recently seen some provisioning processes failing during the creation of the navigation nodes. We're investigating the issue and we will eventually fix it, in case it depends on our codebase. Stay tuned. Thanks for your cooperation.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.
