### ISSUE TITLE
New employee departmental onboarding site"  template failed

### ISSUE THREAD

**Issue by dramirezzz** [SharePoint/sp-provisioning-service#482]
**Describe the issue**
we tried to add this template to our tenant and got a template failed issue

**Details (please complete the following information):**
 correlation ID: 02129b01-6e62-4f41-9019-ca70a4549914 
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: 
- https://lookbook.microsoft.com/details/99d3b7ea-6ca0-430e-96bc-922d4d2de2ab
- Primary language of the target tenant: US
- Are you using a Tenant Global Admin account to provision the template: [Yes/No]
- Yes

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.

**Comment by dramirezzz** [comment]
Hi Paolo
The site got created but the webparts with preloaded content were not added to the pages.

Thanks!


Best Regards,
David Ramirez
Supv, IT
Web Systems

Epicor Software Corporation
T  +1 (512) 278-5894
C  +1 (949) 943-0823
E   ***@***.******@***.***>

***@***.***D73FF5.B9B20CB0]<https://www.epicor.com/>
