### ISSUE TITLE
Provision "Microsoft 365 learning pathways"  template failed

### ISSUE THREAD

**Issue by jwrightbso** [SharePoint/sp-provisioning-service#483]
**Describe the issue**
MS Learning Pathways template provisioning failed

**Expected behavior**
To not fail.

**Screenshots**
None

**Details (please complete the following information):**
- PnP Correlation ID: 8e83ae29-bc38-4c1e-bd49-e3d130e4f641
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
None

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. We've recently seen some provisioning processes failing during the creation of the navigation nodes. We're investigating the issue and we will eventually fix it, in case it depends on our codebase. Stay tuned. Thanks for your cooperation.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.
