### ISSUE TITLE
Provisioning  "Microsoft 365 learning pathways"  template failed

### ISSUE THREAD

**Issue by stevebazza** [SharePoint/sp-provisioning-service#484]
**Describe the issue**

1. In a demo environment, I have created an App catalog and removed English as the default language on user (global admin) that is provisioning the M365 Learning pathways
2. From https://lookbook.microsoft.com/  selected "Add to your tenant" and entered email and URL (see screen shot)
3. received two emails that the provisioning has failed

**Expected behavior**
Receive an email that the M365 Learning pathways site has beeen provisioned 

**Screenshots**
![image](https://user-images.githubusercontent.com/83318102/116325469-97cc8d00-a805-11eb-9c80-0804d02064b0.png)

**Details (please complete the following information):**
- PnP Correlation ID: 1st correlation ID: e59b8c2d-8e72-4be1-abf2-ce5cff226153 !
- 2nd correlation ID: 2f8345c9-66d8-42ac-98c2-a8f93b12f93e !
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by stevebazza** [comment]
The M365 learning pathways is in the Apps catalog, with a "No" as the value in "Tenant Deployed" field.
The site sites/LearnM365 is in Active sites.
Is it ready to use/demo?

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. We've recently seen some provisioning processes failing during the creation of the navigation nodes. We're investigating the issue and we will eventually fix it, in case it depends on our codebase. Stay tuned. Thanks for your cooperation.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.
