### ISSUE TITLE
Leadership Connection Template not Provisioning

### ISSUE THREAD

**Issue by KONegative** [SharePoint/sp-provisioning-service#485]
Your request to provision "Leadership Connection" template failed!

correlation ID: 8052a355-d191-448f-b5f6-34da8b70c19c 

https://lookbook.microsoft.com/details/c19f437b-35ca-42f2-b27a-1caa49ad8bde

**Additional context**
Tried it with our desired URL and the OOTB URL.  Both fail.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
