### ISSUE TITLE
Template provisioning consistently fails

### ISSUE THREAD

**Issue by RuthChurchman** [SharePoint/sp-provisioning-service#488]
**Describe the issue**
Re-opening this issue submitted by JaredHolgate: "Template provisioning consistently fails #417"
"Whenever I try to provision a look book, it consistently fails with this message;

Sorry, something went wrong
There was an unexpected issue.
Cannot retrieve a valid Access Token for user jared.holgate@ms.com in tenant 93c*-ed89-4fa6-80cf-b0a********4"

I particularly want to provision the Learning Pathways template and app.

**Expected behavior**
"It provisions the look book"

**Screenshots**
![image](https://user-images.githubusercontent.com/83355220/116418694-48ea1c00-a834-11eb-9dca-41b8b20535de.png)

**Details (please complete the following information):**
- PnP Correlation ID: [appId=cid-v1:ccc54f05-096c-4a72-a440-e7a8bfdf2d39]
- Reference Template: [https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239]
- Primary language of the target tenant: [UK English]
- Are you using a Tenant Global Admin account to provision the template: [Yes]

**Additional context**
PaoloPia suggested this:
Hi,
Thanks for using the Look Book site. Based on the exception that you see, the problem is that the Provisioning App can't retrieve a valid access token for consuming the Microsoft Graph. Reasons could be:

1. The grant/consent process for the app didn't go well. If this is the case, you can try to delete the app with name "SharePointPnP.ProvisioningApp.Tenant" from the Enterprise Applications in your Azure Active Directory and re-start from scratch the provisioning process.
2. There is something like Client Access Policies or MFA blocking the request to acquire an access token for Microsoft Graph.
Can you eventually see if, using the Microsoft Graph Explorer(https://developer.microsoft.com/en-us/graph/graph-explorer) and with the same tenant and user account, you can access the Microsoft Graph or not? You can for example make a request for https://graph.microsoft.com/v1.0/sites/root.
Please, let me know."

Jared is the Tenant Global Admin, but he was too busy to follow up on this. I am the SharePoint Administrator. I have looked at your instructions.
I do not have sufficient access to delete the "SharePointPnP.ProvisioningApp.Tenant" from the Enterprise Applications in your Azure Active Directory.

With my account I was able to make a request for https://graph.microsoft.com/v1.0/sites/root and get a response.

If I can't get the Learning Pathways template provisioned with my permission level, can I manually install the app?

Keen to get this sorted.

Hope you can help. 
Ruth

**Comment by PaoloPia** [comment]
Hi,
You can eventually try to manually apply the template using the source file available here (https://github.com/SharePoint/sp-dev-provisioning-templates/blob/master/tenant/M365LearningPathways/M365LP.pnp) and using PnP PowerShell.

**Comment by RuthChurchman** [comment]
Thanks. Having a go at the Manual provisioning. Will get back to you soon

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. I'm going to close this item because you did not reply back after 25 days. Please, feel free to try again the template and to create another issue, providing the Correlation ID of the request, for further investigation. Thanks for your feedback.
