### ISSUE TITLE
Provisioning "The Perspective" template failed

### ISSUE THREAD

**Issue by Joey-in-Houston** [SharePoint/sp-provisioning-service#489]
**Describe the issue**
A clear and concise description of what the issue is.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/83362509/116438801-732be180-a814-11eb-99a8-67f687ac86aa.png)

**Details (please complete the following information):**
- PnP Correlation ID: a13e4f9d-9143-41e6-a7aa-d7b2b2a56a81
- Reference Template: https://lookbook.microsoft.com/details/6944f54d-cc8e-45ca-ba13-5f887a2d5f81
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
