### ISSUE TITLE
Provisioning the New Employee pre-onboarding site failed

### ISSUE THREAD

**Issue by GuillermoBas** [SharePoint/sp-provisioning-service#490]
**Describe the issue**
Provisioning the New Employee pre-onboarding site failed
with correlation ID: e8e7339f-28e6-4cb7-8d62-75a787cfa219 

**Expected behavior**
Not failed...

**Screenshots**
![image](https://user-images.githubusercontent.com/8668582/116444878-8317e580-a855-11eb-9916-9ca3b2da5e4b.png)

**Details (please complete the following information):**
- PnP Correlation ID: e8e7339f-28e6-4cb7-8d62-75a787cfa219
- Reference Template: https://lookbook.microsoft.com/details/8fefcc9a-7ca4-457f-bd10-acee3ae63b63
- Primary language of the target tenant: 1033
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
