### ISSUE TITLE
Request to provision  "Microsoft 365 learning pathways"  template failed

### ISSUE THREAD

**Issue by willie720** [SharePoint/sp-provisioning-service#491]
**Describe the issue**
Receive an email indicated failed to provision "Microsoft 365 learning pathways"  site, however; I site is created, I'm not sure what's missing. Please advise.

**Details (please complete the following information):**
- PnP Correlation ID: correlation ID: 0d9eb4a7-7733-4954-a30b-8f0d66a58b0f
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. We've recently seen some provisioning processes failing during the creation of the navigation nodes. We're investigating the issue and we will eventually fix it, in case it depends on our codebase. Stay tuned. Thanks for your cooperation.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.
