### ISSUE TITLE
M365 learning pathways provisioning fails

### ISSUE THREAD

**Issue by Thor-So** [SharePoint/sp-provisioning-service#492]
**Issue description**
Trying to provision the Learning Pathways solution via the lookbook website I receive following error, repeatedly:
"Your request to provision "Microsoft 365 learning pathways" template failed!"

Result of the provisioning process:
- app was installed and provisioned corectly (not tenant-wide)
- site collection was created and base content provisioned

But, there seems to be a problem with provisioning the multilingual content und the error message above was the result of all attempts and varying results::
- different, incomplete content was provisioned,
- language switch was provisioned correctly one time and was missing the other time

**Expected behavior**
LP Website should be provisioned under the provided URL, including entire, multilingual content.

**Details:**
Hese are the Correlation IDs from the last two provisioning attempts:
 - 1st attempt : a6ec7940-4126-4f50-a454-9b5fc5594080
 - 2nd attempt : a3e25848-0888-473f-bc40-26bee23f2ef4

Lookbook: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239

All prerequisites were met. The webiste url was available and not in the recycle bin. The provisioning user is global admin, site collection admin of the app catalog site and has no display language set.

Primary language of the target tenant: English (1033)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. In the event log, we see (for both the provisioning attempts) a random failure while uploading a file (not the same file). Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
