### ISSUE TITLE
Failed to provision learning pathways sharepoint template. 

### ISSUE THREAD

**Issue by Juniluisthe1st** [SharePoint/sp-provisioning-service#493]
Cannot provision try two times even with different URL and it fails. 

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: d4ec0d14-80cc-4126-ac8b-0153a4c6c3ee
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/ learning pathways
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. We've recently seen some provisioning processes failing during the creation of the navigation nodes. We're investigating the issue and we will eventually fix it, in case it depends on our codebase. Stay tuned. Thanks for your cooperation.

**Comment by Juniluisthe1st** [comment]
HI Thank you very much for your feedback.

Now how will I receive an update?


Best Regards, Met vriendelijke groet, Saludo Kordial.

Luis Enrique Lorenzo Garcia.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.
