### ISSUE TITLE
Your request to provision "Team communication site"  template failed!

### ISSUE THREAD

**Issue by FSIGuy** [SharePoint/sp-provisioning-service#494]
Attempted to get a sample site added to my tenant from lookbook.  Email received that  said "Your request to provision
"Team communication site"  template failed!" and directed me to this site and to provide "the following provisioning action correlation ID: 05727e3e-1352-45ea-b0a0-63e48767357b ! "

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
