### ISSUE TITLE
SharePoint Learning Pathways - Partial Provision 

### ISSUE THREAD

**Issue by DaveJacksonNZ** [SharePoint/sp-provisioning-service#495]
Similar issue to the list of issues from the last week (is something broken)

Received this error after trying multiple times. It worked perfect on another tenant a few weeks ago
ID: 38246f9d-a09f-4e24-a58a-35a5c7bff8e4 !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
