### ISSUE TITLE
SharePoint Learning Pathways - Multiple Fails

### ISSUE THREAD

**Issue by DaveJacksonNZ** [SharePoint/sp-provisioning-service#496]
Have tried to provision again and received this error

ID: 87c063ec-5659-4cf7-8d9d-e0bed86a5cf3 !

Screenshot of issue below

![SharedScreenshot](https://user-images.githubusercontent.com/83567440/116859795-acb97e00-ac54-11eb-9fc7-a706d185abde.jpg)

I deleted the previous site that failed but did not delete the app catalogue.   Screen shot of that below also:

Yes to global admin
![SharedScreenshot](https://user-images.githubusercontent.com/83567440/116860061-15085f80-ac55-11eb-9694-d594c06a006b.jpg)

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
