### ISSUE TITLE
Microsoft 365 learning pathways template failed! - System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by PhilipHaglund** [SharePoint/sp-provisioning-service#498]
**Describe the issue**
After deploying Microsoft 365 learning pathways for the second time still receive an error.
This is after https://github.com/SharePoint/sp-provisioning-service/issues/477

**Expected behavior**
Provision without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/14297750/117022965-f78cd180-acf8-11eb-8617-ad64104d6d4d.png)

**Details (please complete the following information):**
- PnP Correlation ID: 03ad2c38-454c-4155-ae33-183aa3e9a283 ]
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: en-US
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
Exception: {"odata.error":{"code":"-2147024894, System.IO.FileNotFoundException","message":{"lang":"en-US","value":"File Not Found."}}}
Provisioning action correlation ID: 03ad2c38-454c-4155-ae33-183aa3e9a283

**Comment by PaoloPia** [comment]
Hi @PhilipHaglund,
Thanks for trying again. Unfortunately this time the exception that occurred is completely different from the one of #477. In fact, this time file upload was correctly executed, without any hiccup. However, the service failed to install the M365LP app package in the AppCatalog. Could you please verify if the SPPKG is already there, or if there is any authorization issue while accessing the AppCatalog with the account that you are using for provisioning? Thanks.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. I'm going to close this item because you did not reply back after 25 days. Please, feel free to try again the template and to create another issue, providing the Correlation ID of the request, for further investigation. Thanks for your feedback.
