### ISSUE TITLE
Not able to add the Microsoft 365 Learning Pathways template to my tenant

### ISSUE THREAD

**Issue by anjali0807** [SharePoint/sp-provisioning-service#501]
Not able to add the Microsoft 365 Learning Pathways template to my tenant.
When I try to add the template to the tenant, I get the issue as :

Sorry, something went wrong
There was an unexpected issue.
Cannot retrieve a valid Access Token for user anjali.sharma-admin@shl.com in tenant 6c22396a-d63a-4dfe-a501-4c4276368755

I am the global admin for my tenant.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Unfortunately without a PnP Correlation ID we cannot search for your issue. Please try again and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
