### ISSUE TITLE
"Workplace Transformation site" template provision failed

### ISSUE THREAD

**Issue by jescc** [SharePoint/sp-provisioning-service#502]
**Describe the issue**
"Workplace Transformation site" template from  SharePoint look book failed at provisioning

**Expected behavior**
Provisinoing as described in https://docs.microsoft.com/en-us/sharepoint/change-management-template

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: 3d93df24-8846-4b2a-9cf0-a8876a77ab19 ! 
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/b0633491-127d-48bf-ba06-a0cdb6ec749f
- Primary language of the target tenant: spanishs es 0x000A
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Unfortunately during these days, we are experiencing random hiccups on the SharePoint side, which would imply that the template should work properly. Please try again after 2 or 3 days from now and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
