### ISSUE TITLE
Microsoft 365 learning pathways template provision failed

### ISSUE THREAD

**Issue by jescc** [SharePoint/sp-provisioning-service#508]
**Describe the issue**
Request to provision "Microsoft 365 learning pathways" template failed returning the message "Unfortunately your site provisioning at least partially failed!"

**Expected behavior**
Provisioning of the site according to the look book template description

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: 5807e2b9-6a07-433a-bd42-b09cca3e69eb !
- Reference Template: [please provide the URL of the template in the Look book site.
https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: es spanish
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
