### ISSUE TITLE
Microsoft 365 Learning Pathways provisioning error

### ISSUE THREAD

**Issue by rweaver-core** [SharePoint/sp-provisioning-service#509]
Describe the issue
Request to provision "Microsoft 365 learning pathways" template failed returning the message "Unfortunately your site provisioning at least partially failed!"

Expected behavior
Provisioning of the site according to the look book template description

Details (please complete the following information):

PnP Correlation ID: bbee25dd-77f5-46ba-8df9-a579a16b17e5 !
Reference Template: [please provide the URL of the template in the Look book site.
https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
Primary language of the target tenant: english
Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. We've recently seen some provisioning processes failing during the creation of the navigation nodes. We're investigating the issue and we will eventually fix it, in case it depends on our codebase. Stay tuned. Thanks for your cooperation.

**Comment by rweaver-core** [comment]
Understood. Is there anyway for me to deploy the site manually or anything while the issue is being investigated or resolved? We are working on a M365 deployment for a client that has a deadline we are trying to hold. Thanks!

Ryan

Ryan Weaver
Principal Architect
P 440.465.0193 | E ***@***.******@***.***>

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.
