### ISSUE TITLE
Microsoft 365 learning pathways template failed

### ISSUE THREAD

**Issue by jescc** [SharePoint/sp-provisioning-service#512]
**Describe the issue**
Request to provision "Microsoft 365 learning pathways" template failed

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: 875a8b3a-1d21-40be-b79f-d7d9f2e74714 
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: spanish es
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
