### ISSUE TITLE
Your request to provision  "SharePoint Success Site"  template failed!

### ISSUE THREAD

**Issue by jamespepper81** [SharePoint/sp-provisioning-service#514]
Hi I have been trying to provision the SharePoint Success Site but this keeps failing to deploy.  I have successfully been able to deploy other SharePoint templates from lookbook as well as Microsoft 365 Learning Pathways but really struggling to get this working.

When the deployment fails it does deploy the site partially but all the menu's are in Italian.  When clicking on something within the site it goes to a page displaying all the correct headings but displays "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.]"

I also receive an email to say the provisioning of the site has failed.  I have been trying to implement this for a few weeks now and my account is a global administrator and administrator / owner of the App catalog.  Also after each attempt, I delete the site and then permanently delete the site.  I have also even tried using a different URL.  The tenant has Azure AD security defaults enabled so all users have MFA enabled which I thought may have been causing the issue but other SharePoint admins I have spoken to said they have deployed this with MFA enabled on the global admin account.

- PnP Correlation ID: da76c1e1-38b5-4192-a06e-c499e6497d1b
- Reference Template: https://lookbook.microsoft.com/details/0b860749-56a0-4c4c-992c-536d56d9accf
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

Many thanks for your help

![screenshoot](https://user-images.githubusercontent.com/84083764/117996268-eae02d00-b339-11eb-99ba-a1c905f45899.jpg)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log for your provisioning request, we see an exception while provisioning navigation nodes. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.
