### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by NoelLynam** [SharePoint/sp-provisioning-service#515]
Hi 
I tried to provision learning pathways and eventually received an email saying it failed and that i should report the issue here. What is the solution? Thanks.

Your request to provision
"Microsoft 365 learning pathways" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: 6d5a603e-dcbb-4719-8929-251cd9ad677f !

**Comment by J04nn4** [comment]
We got the same issue 

Your request to provision "Microsoft 365 learning pathways" template failed! Please report the issue here providing the following provisioning action correlation ID: 2acbddad-5e43-4b69-ae7f-5dceb4a22ba1 

Exception: The remote server returned an error: (404) Not Found. Provisioning action correlation ID: 2acbddad-5e43-4b69-ae7f-5dceb4a22ba1

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.

About your issue @J04nn4 you used an 

Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.

About your issue @J04nn4, in the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
