### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by sscarcella** [SharePoint/sp-provisioning-service#516]
**Describe the issue**
I have tried 3 times now and it keeps failing.

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: 557acfd6-9da1-47e2-9f81-ac46038c0bfa ! 
- Reference Template:
   https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by pdaswani** [comment]
I'm having the same issue trying to install this template onto my tenant 

e8223ffa-ed63-436e-88f7-7fe9c42d3577 

can you please advise?

**Comment by sscarcella** [comment]
Is there any update on this?  when will this template be working again?

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. About the first issue, we've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.

About the second issue, in the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks.
