### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by marmstrong2020** [SharePoint/sp-provisioning-service#517]
**Describe the issue**
Provisioning "Microsoft 365 learning pathways site and received provisioning status error: "Unfortunately your site provisioning at least partially failed!"

**Expected behavior**
To provisioning "Microsoft 365 learning pathways site in sharpoint

**Screenshots**
![SharePoint_Template_Provisioning](https://user-images.githubusercontent.com/84186597/118273513-a82d6a80-b489-11eb-929e-b3d5c061d7e2.JPG)

**Details (please complete the following information):**
- PnP Correlation ID: correlation ID: c3929bef-8574-4729-9c74-46a8acbd8d65 ! 
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: [English]
- Are you using a Tenant Global Admin account to provision the template: [Yes]

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.
