### ISSUE TITLE
Provision failed

### ISSUE THREAD

**Issue by JaniceApopo** [SharePoint/sp-provisioning-service#518]
**Describe the issue**
I provisioned the Learning Pathways Lookbook and it said that it partially failed 

**Expected behavior**
I expected provisioning to not fail.

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: c5b61192-29d2-439e-8a1e-f0c822c50ae
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant] English
- Are you using a Tenant Global Admin account to provision the template: [Yes/No] Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Unfortunately, we cannot find any item in the log with the PnP Correlation Id that you provided. Could you please double-check the value of the PnP Correlation Id, or submit another provisioning request? In fact, we've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. I'm going to close this item because you did not reply back after 25 days. Please, feel free to try again the template and to create another issue, providing the Correlation ID of the request, for further investigation. Thanks for your feedback.
