### ISSUE TITLE
Your request to provision "Class home page"  template failed!

### ISSUE THREAD

**Issue by NC1856** [SharePoint/sp-provisioning-service#519]
**Describe the issue**
Provision of SharePoint site template failed

**Expected behavior**
I expected it wouldn't fail

**Details (please complete the following information):**
- PnP Correlation ID: 17d66844-1bf3-45f6-86f2-a3c898a651d2 ! 
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/f70a722f-e20a-4f0e-a0e7-ed75b3c9a74a
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: [Yes]

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that there was an "access denied" exception while trying to upload a custom file (Home.aspx) into the target site. In fact, the file was checkout by a specific user. It might be that the site was in use while the provisioning was running. Could you please try again, targeting a fresh new site? Thanks for your cooperation.
