### ISSUE TITLE
Your request to provision  "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by Roleofm** [SharePoint/sp-provisioning-service#520]
**Describe the issue**
got the error measseg Your request to provision

"Microsoft 365 learning pathways"

template failed! when trying to provision this site

Exception: Object reference not set to an instance of an object.
Provisioning action correlation ID: 165ec39e-cfe7-4d36-8893-f931c4524c55

**Expected behavior**
no error

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: [165ec39e-cfe7-4d36-8893-f931c4524c55]
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{Template-ID}]
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant] default of a devlopment tenant I expect 1033
- Are you using a Tenant Global Admin account to provision the template: [Yes/No] Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.

**Comment by Roleofm** [comment]
Hi Paolo,

Thank you very much. I will give it a try.

Met vriendelijke groet,

Roelof Meijer



Van: Paolo Pialorsi ***@***.***>
Verzonden: vrijdag 21 mei 2021 10:25
Aan: SharePoint/sp-provisioning-service ***@***.***>
CC: Roelof Meijer ***@***.***>; Author ***@***.***>
Onderwerp: Re: [SharePoint/sp-provisioning-service] Your request to provision "Microsoft 365 learning pathways" template failed! (#520)


Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.

-
