### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by therockett** [SharePoint/sp-provisioning-service#521]
SharePoint Provisioning Service 
Your request to provision "Microsoft 365 learning pathways" template failed!
Please report the issue here providing the following provisioning action correlation ID: 4fb026a8-b2ae-4d96-86db-fb502079a54d ! 

Please provide use feedback around your used template or the service in general by using our feedback form . Thank you for your input advance. 

Exception: Object reference not set to an instance of an object.
Provisioning action correlation ID: 4fb026a8-b2ae-4d96-86db-fb502079a54d

![image](https://user-images.githubusercontent.com/70723803/118718504-eeb5f880-b7ec-11eb-9337-d399336fff86.png)

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.

**Comment by therockett** [comment]
Thank you very much and have a wonderful weekend. We will try it again today. 🙂

Regards,

Johnny Crockett Lopez
Microsoft MVP<https://mvp.microsoft.com/en-us/PublicProfile/5004098>
about.me/JCLopez81<https://about.me/JCLopez81?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>
Cell: 713-586-9227
***@***.***

[cid:8098bc35-4ce5-47ff-9642-28818468f30b]  [cid:f1c97265-5586-4836-b6cc-03f3f779ac64] [cid:26e36e10-8d14-436d-a82d-9dd9d348f075] [cid:a46305e8-40c3-4672-9695-9dc103e10f1f]



________________________________
