### ISSUE TITLE
Request to provision Microsoft learning pathways template failed

### ISSUE THREAD

**Issue by helenwalker7** [SharePoint/sp-provisioning-service#522]
**Describe the issue**
Trying to install Microsoft 365 learning pathways app via the 'Add to your tenant' option here: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239

**Expected behavior**
As per here: https://docs.microsoft.com/en-us/office365/customlearning/custom_provision

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: ee25abc5-8e07-4ba0-864f-bd9fa0da5b70 
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: [Yes/No] Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.

**Comment by helenwalker7** [comment]
Paolo – thank you! I now have the Learning Pathways site. Some of my menu items are appearing in Dutch, but apart from that, all is working well.

Wishing you a great weekend.

Helen
