### ISSUE TITLE
SharePoint

### ISSUE THREAD

**Issue by isaactyndall** [SharePoint/sp-provisioning-service#523]
I'm using the SharePoint provisioning service and getting an error message when trying to add a site.

**ID: 53167b59-bf28-44ef-8016-85ffa2fd7c82 !**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
