### ISSUE TITLE
Template Provisioning Failure - Learning Pathways

### ISSUE THREAD

**Issue by Matt-Laurie** [SharePoint/sp-provisioning-service#524]
**Describe the issue**
Followed provisioning documentation included prerequisites. Provisioning ended with an error stating: 
Unfortunately your site provisioning at least partially failed!

**Expected behavior**
Completed Provision

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: 797f2281-1e6d-4b19-bb1d-db2891ba945c
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: EN
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.
