### ISSUE TITLE
Provision "Crisis Communications"  template failed

### ISSUE THREAD

**Issue by macboahughes** [SharePoint/sp-provisioning-service#525]
**Describe the issue**
I tried provisioning the crisis communication template to my tenant, it failed

**Expected behavior**
Expected to have this template site available in our site collection for use.

**Screenshots**
n/a

**Details (please complete the following information):**
- PnP Correlation ID: eb3424d5-b8e7-4355-8c96-2c48ee5e56eb
- Reference Template: https://lookbook.microsoft.com/details/8f8337d2-b1f6-4a84-91a4-9081f841f0f6
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
N/a

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
