### ISSUE TITLE
Request to provision "Microsoft 365 learning pathways" template failed!

### ISSUE THREAD

**Issue by carl-kelly** [SharePoint/sp-provisioning-service#527]
**Describe the issue**
We are trying to add the below lookbook template to our tenant and it failed.

- provisioning action correlation ID: 0b8e03ed-91a9-4606-8d11-32c01e9e5ca3 
- lookbook url: https://provisioning.sharepointpnp.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- language: English
- Are you using a Tenant Global Admin account to provision the template: [Yes]

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
