### ISSUE TITLE
Request to provision "School home page"  template failed!

### ISSUE THREAD

**Issue by 2NV-Dev** [SharePoint/sp-provisioning-service#528]
**Describe the issue**
I tried to provision a template from lookbook

**Expected behavior**
I expected the site to be ready to use 

**Screenshots**
![image](https://user-images.githubusercontent.com/72281486/119200050-c975f400-ba51-11eb-9459-98b8572de0e6.png)

**Details (please complete the following information):**
- PnP Correlation ID: bed02950-c8ad-429a-8fee-0e473b33ff05 !
- Reference Template: https://lookbook.microsoft.com/details/44dc3585-9140-4183-81fc-bdb057f71ac1
- Primary language of the target tenant: Spanisg
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
N/A

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
