### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed

### ISSUE THREAD

**Issue by jrhollan** [SharePoint/sp-provisioning-service#529]
**Describe the issue**
Attempting to install 365 Learning Pathways and I receive the below error:

Your request to provision "Microsoft 365 learning pathways" template failed!
Correlation ID: 723bdd16-b0c8-4731-ab82-4c0d4264a6c3 

I've tried multiple times over the past two weeks and all attempts have failed.  Global Admin, new site collection, non-MFA.

**Expected behavior**
Template should install successfully.

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: 723bdd16-b0c8-4731-ab82-4c0d4264a6c3
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
I've seen posts where some suggest a manual install via PNP.  If that's the workaround, could you point me to the instructions?  

Cheers,
Jim

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.

**Comment by jrhollan** [comment]
That worked, thanks Paolo!
