### ISSUE TITLE
Provision of Microsoft 365 learning pathways template failed

### ISSUE THREAD

**Issue by ToughDBlue** [SharePoint/sp-provisioning-service#53]
I tried to provision the Microsoft 365 Learning Pathways template to my Office 365 Tenant but I received an email saying that it failed.

PnP Correlation ID: 345eed21-814c-4965-be5f-df4f98ef006c

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
