### ISSUE TITLE
Sharepoint Provisioning Fail

### ISSUE THREAD

**Issue by cherrishyourhealth** [SharePoint/sp-provisioning-service#532]
Trying to provision the Retail Operations template and keep getting this error.

Your request to provision
"Retail Operations" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: 99db0a24-531c-485f-b287-e33993639ef0 !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
