### ISSUE TITLE
URL to provision Microsoft New Employee Onboarding sites

### ISSUE THREAD

**Issue by mvcsharepointdev** [SharePoint/sp-provisioning-service#533]
I am reading this article @ [provision-neo-hub](https://docs.microsoft.com/en-us/sharepoint/provision-neo-hub) on how to provision NEO hub sites, but when i click on this link :-

![image](https://user-images.githubusercontent.com/79726511/120247242-1d16e780-c273-11eb-897c-01b53cc82a4a.png)

I will be redirected to a page to provision the "MICROSOFT 365 LEARNING PATHWAYS" and not the NEO sites.. any advice please? what is the URL to provision the NEO sites?

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. We're working on fixing the wrong link. The correct one is: https://docs.microsoft.com/it-it/sharepoint/provision-neo-hub

Thanks.
