### ISSUE TITLE
Provisioning lookbok template failed for an existing sharepoint site

### ISSUE THREAD

**Issue by andrerdz** [SharePoint/sp-provisioning-service#534]
**Describe the issue**
Provisioning lookbok template failed for an existing sharepoint site

**Expected behavior**
Provisioning successful

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: 19ecd97f-54a0-46ac-81bb-ef98a85ea77d
- Reference Template: https://lookbook.microsoft.com/details/81e2fee3-02a0-427b-af8b-8c7f42010fde
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.

**Comment by andrerdz** [comment]
Hi Paolo,
This exception of Forbidden how can be modified? Is it some field in which it should be approved?
I think if I re-try without modifying anything, I might have the same result. 
Thanks.
