### ISSUE TITLE
Request to provision "Microsoft 365 learning pathways" template failed

### ISSUE THREAD

**Issue by githubsfinest** [SharePoint/sp-provisioning-service#536]
**Describe the issue**
My request to provision Microsoft 365 learning pathways template failed.
The Lookbook SharePoint provisioning service page gives the Provisioning Status as "Unfortunately your site provisioning at least partially failed!"

**Expected behavior**
Successful completion of provisioning

**Details (please complete the following information):**
- PnP Correlation ID: 8da97ba5-9619-4590-bbf1-065de866904b !
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English, but no languages selected in tenant admin account
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
The request for provisioning was submitted a few minutes after I had created an App Catalog site collection through the SharePoint admin center

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. The provisioning failed while trying to upload the customization package (SPPKG) into the AppCatalog. Could you please verify that you have write access to the AppCatalog and that the SPPKG of the Learning Pathways solutions can be overwritten, if it is already existing? I will close this item. Please, create a new one in case of any further issue. Thanks.
