### ISSUE TITLE
Provision Failed: HR Hub

### ISSUE THREAD

**Issue by ericmez** [SharePoint/sp-provisioning-service#537]
**Describe the issue**
Unfortunately your site provisioning at least partially failed!

**Expected behavior**
I expected provisioning to not fail.

**Details (please complete the following information):**
- PnP Correlation ID: 2c0843bb-e2e0-4bb4-8589-0681b5e83da8
- Reference Template: HUMAN RESOURCE HUB https://lookbook.microsoft.com/details/ebb9432c-3bbd-4f64-8f74-e75a8b4f96de
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: No

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Inpsecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while creating the target Communication Site (the exception was 403 - "Forbidden"). Could you please try to provision the solution to a different site URL or with a different user account? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
