### ISSUE TITLE
Request to provision MS learning pathways template failed

### ISSUE THREAD

**Issue by nirajparajuli** [SharePoint/sp-provisioning-service#538]
**Describe the issue**
Your request to provision "Microsoft 365 learning pathways" template failed!
The remote name could not be resolved: '*****-admin.**.com'
We use custom SharePoint Admin URL. From the exception it looks like it is failing to find the correct SP Admin URL. 

**Expected behavior**
MS Learning Pathway SharePoint site should be provisioned.

**Details (please complete the following information):**
- PnP Correlation ID: 668396e8-6d72-4099-b978-800614542eaa
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. It looks like you are using a vanity domain for your tenant. Unfortunately, vanity domains are not supported by the PnP Provisioning Engine. Eventually, you can manually setup the template following this document: https://docs.microsoft.com/en-us/office365/customlearning/custom_manualsetup. Thanks.

**Comment by nirajparajuli** [comment]
Thanks @PaoloPia i was able to setup MS learning pathways site manually. however, all the supporting pages like Get-started-with-Microsoft-365.aspx were not created. the home page is also blank. How do i setup these pages. Only 2 pages: CustomLearningAdmin.aspx and CustomLearningViewer.aspx were created with the manual steps.
