### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by MarianNerd** [SharePoint/sp-provisioning-service#539]
**Describe the issue**
Your request to provision "Microsoft 365 learning pathways" template failed!

**Expected behavior**
MS Learning Pathway SharePoint site should be provisioned.

**Details** 

provisioning action correlation ID: d83fd6b9-a419-461a-b1fe-eabe66c955f2 
Reference Template: https://lookbook.microsoft.com/tenant/Home/Provision?returnUrl=https%3A%2F%2Flookbook.microsoft.com%2Fdetails%2F3df8bd55-b872-4c9d-88e3-6b2f05344239&source=default

Primary language of the target tenant: Dutch
Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
