### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by basebash** [SharePoint/sp-provisioning-service#541]
when i check permission have "The following factors also affect the level of access for" xxxx

**Comment by PaoloPia** [comment]
Hi,
Could you please be more specific? I'd like to understand the context of your issue. As such, I need at least to know the template that you are trying to apply and the correlation ID of the provisioning. Thanks.

**Comment by basebash** [comment]
"The Landing" i am trying to edit it using sharepoint designer and am getting "404..." when i checked my permissions thats what i got an a global admin with designer permissions. Thank you.

**Comment by PaoloPia** [comment]
Hi @basebash,
Thanks for the update. Unfortunately, you are not supposed to use SharePoint Designer to edit pages of a modern site. I'm sorry.
