### ISSUE TITLE
Issue provisioning Sales Hub template with error "Unfortunately your site provisioning at least partially failed"

### ISSUE THREAD

**Issue by pawsnapier** [SharePoint/sp-provisioning-service#543]
**Describe the issue**
After clicking on Install template for Sales hub (), after a couple of minutes the provisioning status says "Unfortunately your site provisioning at least partially failed"

**Expected behavior**
Successful installation of template.

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: e7523e41-8703-4677-84a8-45c6327b46fc
- Reference Template: https://lookbook.microsoft.com/details/4541e5c4-dff6-4cd7-87be-4646b56d6000
- Primary language of the target tenant: EN-US
- Are you using a Tenant Global Admin account to provision the template: No

**Additional context**

**Comment by clazaro-admin** [comment]
Also having same issue, even if a global admin creates it
Error: Your request to provision
"Workplace Transformation site" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: 661e2774-6143-4595-b90a-5d205dabed24 !

**Comment by PaoloPia** [comment]
Hi @pawsnapier,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.

Hi @clazaro-admin,
In your scenario, it seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
