### ISSUE TITLE
Your request to provision  "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by ahmedmahmoudR** [SharePoint/sp-provisioning-service#544]
**Describe the issue**
Your request to provision

"Microsoft 365 learning pathways"

template failed!

**Details (please complete the following information):**

- PnP Correlation ID: [Provide a correlation ID for the provisioning action]
- correlation ID: 1e189243-b226-449c-86e6-4cccfe465543 !
- 
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239

- Are you using a Tenant Global Admin account to provision the template: [Yes/No]
- Yes

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that there was an issue while trying to upload in the App Catalog the SPPKG of the SharePoint Framework solution. Could you please try to remove the SPPKG and then try again provisioning the site with a fresh new URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
