### ISSUE TITLE
Unable to add Microsoft Learning lookbook

### ISSUE THREAD

**Issue by ravi261985** [SharePoint/sp-provisioning-service#545]
[Your request to provision
"Microsoft 365 learning pathways" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: a1e835f8-50eb-410a-adaa-052d4bd9c2f5 ! 

Exception: {"odata.error":{"code":"-2130575306, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The file \"https://chavansin.sharepoint.com/sites/appcatalog/AppCatalog/customlearning.sppkg\" is checked out for editing by i:0#.f|membership|manasi.sabnis@chavans.."}}}
Provisioning action correlation ID: a1e835f8-50eb-410a-adaa-052d4bd9c2f5

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that there was an issue while trying to upload in the App Catalog the SPPKG of the SharePoint Framework solution. Could you please try to remove the SPPKG and then try again provisioning the site with a fresh new URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
