### ISSUE TITLE
Can we build more than one

### ISSUE THREAD

**Issue by ahmedmahmoudR** [SharePoint/sp-provisioning-service#546]
**Is your feature request related to a problem? Please describe.**
Can we Create more than one Learning Pathways in the same office 365 tenant ?

**Comment by PaoloPia** [comment]
Hi,
Thanks for asking. As far as I know, you can't have more than one Learning Pathways instance configured in your tenant. Of course, you can provision the site multiple times with multiple URLs, but just the last one will be the official and configured one at tenant level.
