### ISSUE TITLE
Provisioning failed SiteStatus: 3

### ISSUE THREAD

**Issue by zcholla** [SharePoint/sp-provisioning-service#547]
**Describe the issue**
I am trying to provision a new Site with a URL that had been used previously. It was a Microsoft 365 Group. I have gone through the process of removing the Group and having it permanently deleted.  I keep getting an error when provisioning this site but there are no details as to why it is failing. I am a Sharepoint Admin but not a global admin.

**Expected behavior**
I expect a new site to be provisioned.

**Screenshots**
N/A

**Details (please complete the following information):**
- PnP Correlation ID: 3d78c715-53ba-44c5-bba0-6682edab92f5
- Reference Template: https://lookbook.microsoft.com/details/b0633491-127d-48bf-ba06-a0cdb6ec749f
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: [Yes/No] No

**Additional context**
The site URL was previously a Microsoft 365 group that has been permanently deleted. We are trying to provision this site with the lookbook template using the previous URL

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
