### ISSUE TITLE
Provisioning Microsoft 365 learning pathways failed

### ISSUE THREAD

**Issue by delmela** [SharePoint/sp-provisioning-service#548]
**Describe the issue**
Provisioning Microsoft 365 learning pathways failed. 
Tried from https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
We have received an email reporting a provisioning error.

**Details (please complete the following information):**
- PnP Correlation ID: c0783d74-d8a2-429e-81d2-b1694556271d
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: Spanish
- Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
