### ISSUE TITLE
SharePoint PnP Failed

### ISSUE THREAD

**Issue by GingerSec** [SharePoint/sp-provisioning-service#550]
Your request to provision
"Microsoft 365 learning pathways" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: 9785c2e2-112c-47fe-813d-f4eba33d4c26 !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Inspecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while uploading the SPPKG package in the app catalog. Could you please try to manually remove any already existing SPPKG of Microsoft 365 Learning Pathway from the app catalog? Then try new provisioning. In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
