### ISSUE TITLE
Need  to understand why the app "SharepointPnp.Provisioningapp.tenant" is requesting access to our site collections in the tenant

### ISSUE THREAD

**Issue by Mohandass123** [SharePoint/sp-provisioning-service#552]
Need  to understand why the app "SharepointPnp.Provisioningapp.tenant" is requesting access to our site collections in the tenant. PFA. Any suggestion or information would be helpful. We are not comfortable with this access privileges that this app is published in our tenant

![SharePointPnp provisioning app tenant](https://user-images.githubusercontent.com/87190437/125086995-bd8dd200-e091-11eb-93de-d1dcf77e32e4.png)

**Comment by panderson25** [comment]
I have the same question.  We understand that we can consent, provision, then remove permissions, which is great.  To add detail, we want to know:
1) Who "owns" the app that is actually performing the actions in this point in time?
2) From where is it being hosted/executed?
3) Exactly which changes are being made?

**Comment by VesaJuvonen** [comment]
That permissions is needed so that site collection specific settings can be applied after the provisioning is completed. This includes for example settings like site title, site logo, description and some branding settings. Unfortunately even the site title setting requires this monstrous permission grant as there's no other permission grant. None of the templates in the look book service contain tenant level settings which would be adjusted.

This is only a provisioning time setting and you can remove the granted permissions after provisioning is completed.

This solution is registered as a 3rd party solution, but it's hosted by Microsoft.

**Comment by VesaJuvonen** [comment]
Closing as answered.

**Comment by HEVARY** [comment]
As per @Mohandass123 
If my understanding is correct settings on site logo, site title settings or branding etc is specific to NEO template sites or it's required for all the site collection that app is requesting the permission for to have setting by default as mentioned.

I think for all new site collection we can manage the site setting based on the permissions set up but the case here seems like app is deciding settings mentioned for the tenant site collections. I generally didn't think app permissions is the decide factor but please take a look at the response and re phrase if my understanding is different.

@VesaJuvonen - Could you please re-phrase this for the customer

**Comment by VesaJuvonen** [comment]
These logo and title settings are ONLY managed on the newly created site collection, but there's no site collection specific permission scope in Azure AD, which forces the solution to ask tenant level scope.

So - permissions are needed for completing the provisioning properly. If customer does not want to use the look book, they could potentially also use PnP PowerShell and templates directly from https://github.com/SharePoint/sp-dev-provisioning-templates, but as PnP PowerShell also used AAD for permission management, this scope is needed for this automation.

**Comment by Mohandass123** [comment]
Hi Vesa,

If my understanding is correct on your mail, you mean to say app "SharepointPnp.Provisioningapp.tenant" is still require access to all site collections in tenant to create the NEO templates from the lookbook. If so, we are not encouraged or allowed to do this since we think it would end up with some security issues/risk.

We don't want to do this by having this app allowed access to all site collections at any point of time. Our Intention was able to create the neo template without having to give the app permission to all the site collections.

If there are other options you can provide us step by step instructions to create without any violations, then we are happy to try the steps.


Mohan

Office Automation - Cloud Collaboration

Walgreen Co. │ Chennai, India
Telephone  224 300 5086



Member of Walgreens Boots Alliance


To report an incident : Please submit ticket in below link and select "SharePoint" under product category

URL:https://walgreens-myit.onbmc.com/dwp/app/#/srm/profile/SRGAA5V0F202JAPJXHKLPJA6LZ01QB/srm<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwalgreens-myit.onbmc.com%2Fdwp%2Fapp%2F%23%2Fsrm%2Fprofile%2FSRGAA5V0F202JAPJXHKLPJA6LZ01QB%2Fsrm&data=04%7C01%7CCloudCollaboration%40walgreens.com%7Cef81602a3a2a417ba1b408d948490e77%7C92cb778e8ba74f34a0114ba6e7366996%7C0%7C0%7C637620300866626963%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LTjXqLZCzW1BhSyClv88NZrZqRThebWoRFGsIruiAOk%3D&reserved=0> (Login using your Authenticator credentials)


________________________________

**Comment by Mohandass123** [comment]
Hi Vesa,

As you are mentioning in one of the emails, can you please update us the steps how do we temporarily grant permission to app and the revoke back to Original settings.

We are not comfortable to provide permissions to app for all site collection, but we are ok to do temporarily. Please update.

[cid:bd9c0f65-c3fd-46a1-8376-a2412f4b0ed7]

Awaiting your response.

Mohan

Office Automation - Cloud Collaboration

Walgreen Co. │ Chennai, India
Telephone  224 300 5086



Member of Walgreens Boots Alliance


To report an incident : Please submit ticket in below link and select "SharePoint" under product category

URL:https://walgreens-myit.onbmc.com/dwp/app/#/srm/profile/SRGAA5V0F202JAPJXHKLPJA6LZ01QB/srm<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwalgreens-myit.onbmc.com%2Fdwp%2Fapp%2F%23%2Fsrm%2Fprofile%2FSRGAA5V0F202JAPJXHKLPJA6LZ01QB%2Fsrm&data=04%7C01%7CCloudCollaboration%40walgreens.com%7C0e8cdf34e0df43adb39b08d951b959bf%7C92cb778e8ba74f34a0114ba6e7366996%7C0%7C0%7C637630678780281217%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=52pPbXoUAthw9tcwzjeQmKTUklNOh5ZDDNHOlEKAVFU%3D&reserved=0> (Login using your Authenticator credentials)

________________________________

**Comment by VesaJuvonen** [comment]
To be able to automate the site collection creation and more importantly to have the site settings set based on the template, this high permission is needed. There's no other way to do this, given that for example Site.Title property requires tenant wide permissions for apps to set that. We do as the minimal set of permissions required for the automation.

This permission is ONLY required during provisioning time - you can remove the Azure AD app registration right after the provisioning/creation is completed.

If you do not allow this permission, you cannot use the service to automatically provisioning the sites. There's no workarounds.

**Comment by VesaJuvonen** [comment]
If there's any further questions, please open a new issue. We do not track closed issues.
