### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by bdbdb** [SharePoint/sp-provisioning-service#553]
stjohnscollege.ac.nz

Email	administrator@stjohnscollege.ac.nz
Site URL	
https://sjc365.sharepoint.com/sites/NewEmployeePreOnboarding
Site Title	Pre-Onboarding
Provisioning Status	
Unfortunately your site provisioning at least partially failed!
correlation ID: ba0d8e7e-5e71-45b7-b8db-a3659b301523 ! 

**Describe the issue**
A clear and concise description of what the issue is.

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action]
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{Template-ID}]
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: [Yes/No]

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
