### ISSUE TITLE
How is it done? oO

### ISSUE THREAD

**Issue by Gennady-G** [SharePoint/sp-provisioning-service#554]
Greetings! 

This is not issue but question. 

I'm looking at Your templates 

![1-2021-07-15_171702](https://user-images.githubusercontent.com/5569346/125794296-fa6029ad-c268-437e-ab21-29438866db2e.jpg)

and on "Product Marketing" site there is customized Modern Display Form:
![2-2021-07-15_171647](https://user-images.githubusercontent.com/5569346/125794303-0661fff8-b9a2-4f6c-a393-e68f9fb7f2f2.jpg)

Text field become image on display form. How is it done?..
It is not 'Configure Layout' functional, and AFAIK there is no out-of-the-box ways to customize ootb Forms in SharePoint.

How can I, as SharePoint developer - do the same? Or You created and deployed some custom field (SPF Extension), and it works behind the scenes?..

Best regards, Gennady

**Comment by PaoloPia** [comment]
Hi,
Here (https://github.com/SharePoint/sp-dev-provisioning-templates/tree/master/tenant/ProductMarketingContoso/source) you can find the source code of the template. You can take inspiration from there. Best of luck!
