### ISSUE TITLE
Your request to provision  "Product Support"  template failed!

### ISSUE THREAD

**Issue by ATJSM** [SharePoint/sp-provisioning-service#555]
Please report the issue here providing the following provisioning action correlation ID: 692bed7d-2d3e-499a-81bb-0c5af7850afb !
Message: The remote name could not be resolved: 'domainName.sharepoint.com'. (domainName omitted)
I can deploy other templates like "The Landing" with no issues.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
