### ISSUE TITLE
ApplyProvisioningTemplate: "A duplicate field {GUID} was found"

### ISSUE THREAD

**Issue by rafakil** [SharePoint/sp-provisioning-service#557]
**Describe the issue**
If I run ApplyProvisioningTemplate, an exception is thrown "A duplicate field {GUID} was found" after just the 1st Taxonomy Field, the field is created though.
The issue concerns The Fields of Type="TaxonomyFieldType".

**Expected behavior**
I expected the apply template to run untill everthing is applied.

Using:
Microsoft.SharePoint2019.CSOM 16.0.10337.12109
SharePointPnPCore2019 3.28.2012
SP on-premise 2019.

**Comment by PaoloPia** [comment]
Hi,
Thanks for reaching out. Unfortunately, this repo is about the PnP Provisioning Service and the lookbook.microsoft.com site, not about the PnP Provisioning Engine. Nevertheless, I would advise you to upgrade your project to the latest PnP Framework (available here: https://github.com/pnp/pnpframework) and in case of any further issues to create an item in the issue list of the PnP Framework repository. I will close this item.
