### ISSUE TITLE
"Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by fnawei** [SharePoint/sp-provisioning-service#560]
**Describe the issue**
"Microsoft 365 learning pathways" template failed with the following provisioning action correlation ID: 3fad4105-1c1a-4dce-bd09-650e7cd6dee3 

**Expected behavior**
Successful creation of M365 Learning Pathways

**Screenshots**
-

**Details (please complete the following information):**
- PnP Correlation ID: 3fad4105-1c1a-4dce-bd09-650e7cd6dee3 
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
-

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log I can see that the provisioning failed while trying to upload the Learning Pathways SPPKG package into the App Catalog. Could you please check if there is already such a package in the App Catalog? If the answer is yes, please try to remove it. Delete the site, empty the Admin site collection recycle bin, and try again. In case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
