### ISSUE TITLE
The Perspective Provisioning Template will not be recreated once deleted

### ISSUE THREAD

**Issue by lkolbbmcproperties** [SharePoint/sp-provisioning-service#562]
The Perspective Provisioning template was created, but we were unable to modify the web parts.  We deleted it, and deleted it from the Deleted folder, and tried to recreate it and got an error message:
- correlation ID: 1a2ba2da-7cc2-470d-8af6-bc6c76a532ef !

**Expected behavior**
We expected to be able to recreate the Perspective Provisioning template again, after deleting it completely from our active sites.

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action]
- - correlation ID: 1a2ba2da-7cc2-470d-8af6-bc6c76a532ef !
- Reference Template: The Perspective - https://lookbook.microsoft.com/details/{Template-ID}]
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: [Yes/No]

**Additional context**
Exception: {"error":{"code":"-2147024894, System.IO.FileNotFoundException","message":"File Not Found."}}
Provisioning action correlation ID: 1a2ba2da-7cc2-470d-8af6-bc6c76a532ef

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the error in the event log, I'd suggest you try using a different URL. If it is not possible to change the URL, you should ensure to completely remove the previously created site collection (delete and empty the admin site collections recycle bin). I don't completely understand what you mean by "deleted it from the Deleted folder", but please ensure that the site is not in the recycle bin if you want to reuse the same URL. In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
