### ISSUE TITLE
Service Description - FAQ not up to date: "Is the service code open-source?"

### ISSUE THREAD

**Issue by andikrueger** [SharePoint/sp-provisioning-service#565]
Currently the [FAQ](https://lookbook.microsoft.com/service-description) states the following

`
Is the service code open-source?

Code used by the service will be released as an open-source sample later 2019. Provisioning uses the PnP Provisioning Engine, which is already open-sourced and available using code or PowerShell.
`

The source code is already available. It would be great to provide a direct link to this repository and the source code.

**Comment by PaoloPia** [comment]
Thanks for your feedback. Changes have been applied and will go live in the upcoming hours.
