### ISSUE TITLE
Provisioning Failed

### ISSUE THREAD

**Issue by RobotRising** [SharePoint/sp-provisioning-service#567]
**Describe the issue**
"Your request to provision microsoft 365 learning pathways template failed"
**Expected behavior**
installation of ms lp

**Screenshots**
![Snag_7327753](https://user-images.githubusercontent.com/88802610/129103687-b5acf18b-8b21-4be2-8a8b-6ec4fcbc6196.png)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the log I can see that the customlearning.sppkg package file is already installed in your tenant App Catalog and the file is checked out by someone. As such, the provisioning process cannot update it. Please, check in the file, or completely remove it, and run the provisioning again eventually providing a different URL for the target site. If you want to use the same URL, please delete the already existing site and empty the admin site collections recycle bin. In case of any further error, please create a new issue and provide the correlation ID as text and not as an image, to make it easier to search for it. Thanks for your cooperation.
