### ISSUE TITLE
Your request to provision "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by E-Wald** [SharePoint/sp-provisioning-service#568]
**Describe the issue**
Provisioning of Microsoft 365 learning pathways fails.

**Expected behavior**
Provisioning of Microsoft 365 learning pathways works.

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: 1e7b9b2d-d9f7-4e3b-b09e-c60e9db8f643
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English 
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
