### ISSUE TITLE
Unfortunately, your request to provision "Microsoft 365 learning pathways"  template failed. 

### ISSUE THREAD

**Issue by Trevor-SDG** [SharePoint/sp-provisioning-service#57]
Here is the exception that occurred:
In order to provision the template you need to have an App Catalog in your tenant. Please, create one (for instructions you can read this document: https://go.microsoft.com/fwlink/?linkid=2087251), wait up to 30 minutes, and try again. 

PnP Correlation ID: eeb2ed46-cec2-4e02-80e8-f4cc7d8c2e4e

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
