### ISSUE TITLE
Provisioning Failed

### ISSUE THREAD

**Issue by DWSP** [SharePoint/sp-provisioning-service#570]
**Describe the issue**
Trying to provision "The Landing" template from Lookbook and it gave an error.

**Expected behavior**
Expected the template to create.

**Screenshots**
![image](https://user-images.githubusercontent.com/88908450/129417769-6334124c-7d6c-4659-91b5-fdbb36f378fb.png)

**Details (please complete the following information):**
- PnP Correlation ID: 346cf2bb-f787-4df1-82d1-da7913b6f0ca ! **
- Reference Template: https://lookbook.microsoft.com/details/c9300e94-6e83-471a-b767-b7878689e97e
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
