### ISSUE TITLE
Provision Failed using 'Global Marketing Hub' template

### ISSUE THREAD

**Issue by sydneyng17** [SharePoint/sp-provisioning-service#571]
I'm receiving an issue using a template from the look book. I have administration rights and have created communication sites before, but when it comes to creating a communication site via a Lookbook, the provision is always failing. Please help.

Here is the email I received: 
![image](https://user-images.githubusercontent.com/89050919/129644175-d588c72d-6016-4466-be2a-62d1e249a6aa.png)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Inpsecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while creating the target Communication Site (the exception was 403 - "Forbidden"). Could you please try to provision the solution to a different site URL or with a different user account? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
