### ISSUE TITLE
"Staff Home Page" not provisioning on subsite where it is the main template on the parent

### ISSUE THREAD

**Issue by ianrobinett** [SharePoint/sp-provisioning-service#572]
**Describe the issue**
When going through the provisioning on a subsite with the Staff Home Page, the provisioning fails.  The parent site for this subsite already has the Staff Home Page template, but the subsite is not inheriting it.

**Expected behavior**
Either the subsite needs to inherit the template or the provisioning needs to work on a subsite as well.

**Details (please complete the following information):**
I am a SharePoint admin on our tenant, and have provisioned sites before.  This is the first time I have had to apply it to a subsite.  I expected the subsite to pull the template through, but it did not and I cannot find a way to switch it to matching the main site.  I have also created a completely new site with no content and tried to apply it, and it still fails on the subsite.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Unfortunately, provisioning templates at sub-site level is not supported. You can only apply templates at site collection level. I'm sorry.
