### ISSUE TITLE
Page Scheduling in Site Pages creates Null value in First Published column. Learning Pathways

### ISSUE THREAD

**Issue by gfrick** [SharePoint/sp-provisioning-service#573]
When I setup approval and page scheduling in the SitePages library of the Microsoft Learning Pathways solution provisioned through the provisioning service. The page is published on the scheduled date, but the First Published Date column contains a null value so the page does not display at the top of the Highlighted Content web part. Is this a know problem? Is there a solution?  I have bee setting the dates prior approval with powershell, but I am looking for a more automated process.  Thanks - Greg

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Unfortunately, the issue you filed is out of scope for this repository. Please, create the issue in a GitHub repository about Microsoft 365 Learning Pathways, like this one: https://github.com/SharePoint/sp-provisioning-service/issues/573. Thanks.
