### ISSUE TITLE
The Perspective cannot be created or used as a template a 2nd time....why not?

### ISSUE THREAD

**Issue by lkolbbmcproperties** [SharePoint/sp-provisioning-service#576]
**Describe the issue**
The 2nd time we tried to utilize The Perspective template, we received an error message.  

 
Your request to provision"The Perspective"template failed!Please report the issue here providing the following provisioning action correlation ID: 0761b43a-8ee3-437f-bc69-004319380991 ! | Your request to provision"The Perspective"template failed!Please report the issue here providing the following provisioning action correlation ID: 0761b43a-8ee3-437f-bc69-004319380991 ! | Your request to provision"The Perspective"template failed!Please report the issue here providing the following provisioning action correlation ID: 0761b43a-8ee3-437f-bc69-004319380991 !

Your request to provision"The Perspective"template failed!Please report the issue here providing the following provisioning action correlation ID: 0761b43a-8ee3-437f-bc69-004319380991 !

**Expected behavior**
Create second intranet site using the perspective, with the newly assigned site name.

**Screenshots**
No site created.

**Details (please complete the following information):**
- PnP Correlation ID: correlation ID: 0761b43a-8ee3-437f-bc69-004319380991
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/The Persepctive
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: No

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site, but when the engine tried to apply the template the site was not existing anymore. Could it be that you deleted the site right after starting the provisioning? Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
