### ISSUE TITLE
Re-create site after old site deleted

### ISSUE THREAD

**Issue by luzcrifier** [SharePoint/sp-provisioning-service#577]
I have deleted the old site and want to create a new site. I would like to use the same url as the old site but an error came out during provisioning process. 

The process should replace the old deleted site with the same url.

**Screenshots**
![image](https://user-images.githubusercontent.com/90169965/132160364-a7409ede-5382-4e63-8fba-74e7bd7903d3.png)

**Details (please complete the following information):**
- PnP Correlation ID: b208e7a0-ba27-4721-aafe-b7cedf0eb06d
- Reference Template: https://lookbook.microsoft.com/details/2917bedd-e7bf-4b46-bd0b-9895e33bd680
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Not sure, currently login as user in organization

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the creation of the site failed. However, if you deleted the previous site and emptied the site collection recycle bin, you should be good to go. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
