### ISSUE TITLE
SharePoint Provisioning Failure

### ISSUE THREAD

**Issue by Bruner2018** [SharePoint/sp-provisioning-service#578]
provisioning action correlation ID: 2ac27b21-e387-4f09-a8e7-346fd3f2a7ff !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, it looks like there was an issue uploading/updating the SPPKG of the solution in the App Catalog. Please, verify that you have proper permissions to access the App Catalog, and eventually remove the already existing SPPKG solution if you are upgrading the Learning Pathways site on your target tenant. Once you have done that, please try again and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
