### ISSUE TITLE
Unable to provision Learning Pathways in multi-tenant setup

### ISSUE THREAD

**Issue by kumaranMunusamy** [SharePoint/sp-provisioning-service#579]
we are trying to provision Learning Pathways in a Multi-Geo setup but unable to choose different locations. There is no option to choose different multi-geo tenant.

![image](https://user-images.githubusercontent.com/90440497/132810065-11476ae0-3d97-45a1-89fe-0eb0fca4403e.png)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Unfortunately, the Look Book site does not support multi-geo tenants. Eventually, you can manually provision the Learning Pathways template (https://docs.microsoft.com/en-us/office365/customlearning/custom_manualsetup). Thanks.
