### ISSUE TITLE
Your request to provision  "Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by Le021** [SharePoint/sp-provisioning-service#580]
**Describe the issue**
I was attempting to provision the M365 Learning pathways for my tenant and it keeps failing. I delete the site once and tried again with the same issue. "Cannot contact site at the specified URL, The system cannot find the path specified. (Exception from HRESULT: 0x80070003)"

**Expected behavior**
I was hoping that the provision would be successful and that I can navigate to the CustomLearningAdmin.aspx in order to set up the learning pathways for first use. 

**Screenshots**
![image](https://user-images.githubusercontent.com/90489693/132933644-b1310ea8-7f57-41f7-8d24-73f804a8faae.png)

**Details (please complete the following information):**
- PnP Correlation ID: 88613f3c-e116-49c4-962d-77cf0c3bea20 
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{Template-ID}] N/A
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by Le021** [comment]
I deleted the M365 Learning Pathway site and tried to provision again with the same error message. 
![image](https://user-images.githubusercontent.com/90489693/133156082-958d6c48-2c0f-4c37-8e88-57e53f23c58c.png)

**Comment by RobotRising** [comment]
Leo, did you find a solution to this? Running into the same issue
