### ISSUE TITLE
Sahepoint Templte Fail

### ISSUE THREAD

**Issue by jmoralest** [SharePoint/sp-provisioning-service#581]
**Describe the issue**

Your request to provision
"The Landing"
template failed!

**Expected behavior**
Get the recuestes template

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID 69f5dd9f-1354-44e6-b032-dffe27800917

- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{C9300e94-6e83-471a-b767-b7878689e97e?source+default}]
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: YES

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.

**Comment by jmoralest** [comment]
Thenk’s for your help!

 

JMT

 

De: Paolo Pialorsi ***@***.***> 
Enviado el: viernes, 17 de septiembre de 2021 11:01
Para: SharePoint/sp-provisioning-service ***@***.***>
CC: jmoralest ***@***.***>; Author ***@***.***>
Asunto: Re: [SharePoint/sp-provisioning-service] Sahepoint Templte Fail (#581)

 

Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.
