### ISSUE TITLE
Company and organization news

### ISSUE THREAD

**Issue by ognjensim** [SharePoint/sp-provisioning-service#588]
**Describe the issue**
Trying to add to tenant this site: https://lookbook.microsoft.com/details/34756b7e-e6f6-4327-ba4a-96494a50dca3
Recive error: correlation ID: d9c98ca7-5268-4887-be82-e16d2fbb184a ! 
I am not sure what I am doing wrong?

**Expected behavior**
I am expecting this site added to my organizatio sites.
**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: d9c98ca7-5268-4887-be82-e16d2fbb184a
- Reference Template: https://lookbook.microsoft.com/details/34756b7e-e6f6-4327-ba4a-96494a50dca3
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
