### ISSUE TITLE
Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by Leaderfit** [SharePoint/sp-provisioning-service#589]
**Describe the issue**
Provisioning of M365 Learning Pathways was not successfull. Error message: unfortunately your site provisioning at least partially failed

**Expected behavior**
Full provisioning og M365LP

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: a9c69a79-232f-4e0d-9509-e58c4ac094dc ! 
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/a9c69a79-232f-4e0d-9509-e58c4ac094dc]
- Primary language of the target tenant: French
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
