### ISSUE TITLE
Unfortunately, your request to provision "Microsoft 365 learning pathways"  template failed. 

### ISSUE THREAD

**Issue by mrstevejames** [SharePoint/sp-provisioning-service#59]
Here is the exception that occurred:
Type =     System.Net.WebException Message = The remote server returned an error:     (404) Not Found. Source = System Status = ProtocolError Response =     System.Net.HttpWebResponse TargetSite = System.Net.WebResponse     EndGetResponse(System.IAsyncResult) StackTrace = at     System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) at     System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar,     Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean     requiresSynchronization) --- End of stack trace from previous location     where exception was thrown --- at     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at Microsoft.SharePoint.Client.SPWebRequestExecutor.<ExecuteAsync>d__0.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientContext.<GetFormDigestInfoPrivateAsync>d__b.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientContext.<EnsureFormDigestAsync>d__8.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at     Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()     in C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\ClientContextExtensions.cs:line     156 --- End of stack trace from previous location where exception was     thrown --- at     System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at     Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()     in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\ClientContextExtensions.cs:line     223 --- End of stack trace from previous location where exception was     thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at     Microsoft.SharePoint.Client.ClientObjectExtensions.<EnsurePropertyImplementation>d__5`2.MoveNext()     in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\ClientObjectExtensions.cs:line     130 --- End of stack trace from previous location where exception was     thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at     Microsoft.SharePoint.Client.ClientObjectExtensions.EnsureProperty[T,TResult](T     clientObject, Expression`1 propertySelector) in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\ClientObjectExtensions.cs:line     70 at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceSites.ProvisionObjects(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser     tokenParser, ProvisioningTemplateApplyingInformation applyingInformation)     in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectHierarchySequenceSites.cs:line     150 at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation provisioningInfo) in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line     209 at     Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation applyingInformation) in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\TenantExtensions.cs:line     42 at     SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__2.MoveNext()     in C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line     398 HResult = -2146233079 | Here is the exception that occurred:     Type =     System.Net.WebException Message = The remote server returned an error:     (404) Not Found. Source = System Status = ProtocolError Response =     System.Net.HttpWebResponse TargetSite = System.Net.WebResponse     EndGetResponse(System.IAsyncResult) StackTrace = at     System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) at     System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar,     Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean     requiresSynchronization) --- End of stack trace from previous location     where exception was thrown --- at     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at Microsoft.SharePoint.Client.SPWebRequestExecutor.<ExecuteAsync>d__0.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientContext.<GetFormDigestInfoPrivateAsync>d__b.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientContext.<EnsureFormDigestAsync>d__8.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at     Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()     in C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\ClientContextExtensions.cs:line     156 --- End of stack trace from previous location where exception was     thrown --- at     System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at     Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()     in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\ClientContextExtensions.cs:line     223 --- End of stack trace from previous location where exception was     thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at     Microsoft.SharePoint.Client.ClientObjectExtensions.<EnsurePropertyImplementation>d__5`2.MoveNext()     in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\ClientObjectExtensions.cs:line     130 --- End of stack trace from previous location where exception was     thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at     Microsoft.SharePoint.Client.ClientObjectExtensions.EnsureProperty[T,TResult](T     clientObject, Expression`1 propertySelector) in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\ClientObjectExtensions.cs:line     70 at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceSites.ProvisionObjects(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser     tokenParser, ProvisioningTemplateApplyingInformation applyingInformation)     in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectHierarchySequenceSites.cs:line     150 at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation provisioningInfo) in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line     209 at     Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation applyingInformation) in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\TenantExtensions.cs:line     42 at     SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__2.MoveNext()     in C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line     398 HResult = -2146233079
-- | --
Here is the exception that occurred:     Type =     System.Net.WebException Message = The remote server returned an error:     (404) Not Found. Source = System Status = ProtocolError Response =     System.Net.HttpWebResponse TargetSite = System.Net.WebResponse     EndGetResponse(System.IAsyncResult) StackTrace = at     System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) at     System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar,     Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean     requiresSynchronization) --- End of stack trace from previous location     where exception was thrown --- at     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at Microsoft.SharePoint.Client.SPWebRequestExecutor.<ExecuteAsync>d__0.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientContext.<GetFormDigestInfoPrivateAsync>d__b.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at     Microsoft.SharePoint.Client.ClientContext.<EnsureFormDigestAsync>d__8.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()     --- End of stack trace from previous location where exception was thrown     --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at     Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()     in C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\ClientContextExtensions.cs:line     156 --- End of stack trace from previous location where exception was     thrown --- at     System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at     Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()     in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\ClientContextExtensions.cs:line     223 --- End of stack trace from previous location where exception was     thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at     Microsoft.SharePoint.Client.ClientObjectExtensions.<EnsurePropertyImplementation>d__5`2.MoveNext()     in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\ClientObjectExtensions.cs:line     130 --- End of stack trace from previous location where exception was     thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task     task) at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task     task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at     Microsoft.SharePoint.Client.ClientObjectExtensions.EnsureProperty[T,TResult](T     clientObject, Expression`1 propertySelector) in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\ClientObjectExtensions.cs:line     70 at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchySequenceSites.ProvisionObjects(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser     tokenParser, ProvisioningTemplateApplyingInformation applyingInformation)     in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectHierarchySequenceSites.cs:line     150 at     OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation provisioningInfo) in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line     209 at     Microsoft.SharePoint.Client.TenantExtensions.ApplyProvisionHierarchy(Tenant     tenant, ProvisioningHierarchy hierarchy, String sequenceId,     ProvisioningTemplateApplyingInformation applyingInformation) in     C:\github\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\TenantExtensions.cs:line     42 at     SharePointPnP.ProvisioningApp.WebJob.ProvisioningFunction.<RunAsync>d__2.MoveNext()     in C:\github\sp-provisioning-service\SharePointPnP.ProvisioningApp\SharePointPnP.ProvisioningApp.WebJob\ProvisioningFunction.cs:line     398 HResult = -2146233079
 
PnP     Correlation ID: 0c0f7274-6f56-40cc-8895-ce3eb42ca387

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
