### ISSUE TITLE
New employee corporate onboarding site - template failed

### ISSUE THREAD

**Issue by SplinterGSA** [SharePoint/sp-provisioning-service#590]
**Describe the issue**
Requested the provisioning of the template. The progress screen said it completed; however, the email said it failed.

**Expected behavior**
A new site collection based on the template would be created.

**Screenshots**
None.

**Details (please complete the following information):**
- PnP Correlation ID: 06548202-96f8-46a0-a8e9-7249f4603e3d
- Reference Template:https://lookbook.microsoft.com/details/388a159f-475b-4557-9088-c9073a26c576
- Primary language of the target tenant: 1033
- Are you using a Tenant Global Admin account to provision the template: SharePoint Tenant Admin

**Additional context**
None

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
