### ISSUE TITLE
Look Book Template Provisioning Issue with DevOps Pipeline

### ISSUE THREAD

**Issue by manoj1201** [SharePoint/sp-provisioning-service#591]
**Describe the issue**
Applying lookbook template package file i.e. ".pnp" via DevOps pipeline execute half template activity not completely. On the other hand, if same activity i try with SPO Management shell. it execute fine.

Template file downloaded from here https://github.com/SharePoint/sp-dev-provisioning-templates/blob/master/tenant/benefits/benefits.pnp
Used Copy task to place the file into Artifact folder. It moved like "D:\a\1\lookbooktemplatesartifacts\LookBook\Tenant\Benefits\benefits.pnp"

**PowerShell used for DevOps Pipeline -> Execute Partially ** 
`if (-not(Get-Module -ListAvailable -Name PnP.PowerShell) ){
    Install-Module -Name "PnP.PowerShell" -AllowPrerelease -Force
  } 
$creds = New-Object System.Management.Automation.PSCredential -ArgumentList ("user email id", "secure string as password")
            try {
            
            Invoke-PnPTenantTemplate -Path "<<replace with .pnp absolute file path>>" 
            Get-PnPException -All
            }
            catch {
            }
template is getting store into artifact library and below is generate path is getting generated.
D:\a\1\lookbooktemplatesartifacts\LookBook\Tenant\Benefits\benefits.pnp
`

**PowerShell used with SharePoint Online Management Shell - Execute Fine**
`$creds = Get-Credential
 Connect-PnPOnline -Url "https://m365x6151710-admin.sharepoint.com/" -Credentials $creds
            try {
            Invoke-PnPTenantTemplate -Path "<<replace with .pnp absolute file path>>" 
            Get-PnPException -All
            }
            catch {
            }`

**Expected behavior**
Whenever we run ` Invoke-PnPTenantTemplate -Path "<<replace with .pnp absolute file path>>`
It should have same behavior SPO Management Shell & DevOps Pipeline.  Pipeline execute partially and come out without any error. 

**Screenshots**
DevOps Pipeline ran successfully
![image](https://user-images.githubusercontent.com/12584102/135607789-bc5a6bce-08e2-4b2f-8d7b-cfaf4d3ccbdf.png)

**Details (please complete the following information):**
Even used Get-PnPException -All -> No error pop up.
Lookbook Template : https://github.com/SharePoint/sp-dev-provisioning-templates/blob/master/tenant/benefits/benefits.pnp
Even i am facing same issue with other template also i.e. Tenant or Site Level.

Primary Language for Tenant : English
DevOps Pipeline & Power Shell Script ran with account which has Global Administrator & SPO Administrator privilege's

**Additional context**

**Comment by PaoloPia** [comment]
Hi @manoj1201,
Thanks for your request. I'm sorry but we cannot support you here. This repo is about the PnP Provisioning Service and the Look Book site. Your question is more in the area of PnP PowerShell (https://github.com/pnp/powershell). Do you mind creating an issue in that repo? Unfortunately, I cannot transfer this one straight to the right repository, because here we are in a different Organization. Thanks.
