### ISSUE TITLE
Your request to provision "The Landing" template failed!

### ISSUE THREAD

**Issue by RPushpangadan** [SharePoint/sp-provisioning-service#592]
Hi

I was trying to provision this template to the existing site, the initial validation was successful and it failed during the process. please see the details below.

providing the following provisioning action correlation ID: 98065615-3e03-461f-9835-e13a98e7fe4e 
<img width="1368" alt="Template" src="https://user-images.githubusercontent.com/91881356/135832981-46ad1b80-b944-46a8-a01a-3b71416281a8.png">
!

**Comment by RPushpangadan** [comment]
Hi , wondering if any updates on this?

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
