### ISSUE TITLE
ID: 640f17d9-877e-4fd9-95ee-61774ae79114 ! 

### ISSUE THREAD

**Issue by kblanchard1** [SharePoint/sp-provisioning-service#593]
i just deployed Microsoft 365 learning pathways site. i received this error via email 640f17d9-877e-4fd9-95ee-61774ae79114 !  i am not sure what to do next. please assist. thank you!

**Comment by PaoloPia** [comment]
Hi,
Thanks for your message. Here we provide technical support to people using the PnP Provisioning Service and the Look Book site. Your question is more in the area of how to use the Microsoft 365 Learning Pathways solution, and it is out of scope here. I kindly advise you to refer to the official documentation about Microsoft 365 Learning Pathways (https://docs.microsoft.com/en-us/office365/customlearning/) and eventually start a new thread within Microsoft Tech Community (https://techcommunity.microsoft.com/). Thanks.
