### ISSUE TITLE
Deployment fails when the URL already exists in an archived site

### ISSUE THREAD

**Issue by jaoord** [SharePoint/sp-provisioning-service#595]
**Describe the issue**
When I try to deploy a template to a url that already exists in an archived site, the provisioning service does not return an warning and attempts to deploy the template. However, after a while the deployment will fail.

**Expected behavior**
Immediate warning that the URL already exists in an archived website - or allow urls to be duplicate when they are archived

**Details (please complete the following information):**
- PnP Correlation ID: 09384332-f9e0-48af-ba6c-0e2ce3669d64 
- Reference Template: https://lookbook.microsoft.com/details/119bf67e-a31b-4ba2-969a-4ff33abc034a
- Primary language of the target tenant: nl-NL
- Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.

**Comment by jaoord** [comment]
Please fix the error message so it is more clear that the provisioning service also looks in removed websites
