### ISSUE TITLE
Microsoft 365 learning pathways"  template failed!

### ISSUE THREAD

**Issue by gholtslander** [SharePoint/sp-provisioning-service#596]
provisioning action correlation ID: f07df1e4-0632-44a4-880a-e64794d2c726 !

**Comment by lema07** [comment]
same here, correlation ID: 455e23ef-c9f1-433d-bcee-db0e39ff16de !

**Comment by lema07** [comment]
I found out we did already have a Microsoft 365 learning pathways site thus the error. All fine now

**Comment by PaoloPia** [comment]
Hi @gholtslander,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
