### ISSUE TITLE
SharePoint provisioning failed for HR Hub

### ISSUE THREAD

**Issue by TubaZafar** [SharePoint/sp-provisioning-service#597]
SharePoint provisioning failed for HR Hub

correlation ID: 4d35e33a-beb7-4f40-84e1-968b7a572c99 !
![image](https://user-images.githubusercontent.com/77906184/136731615-b240f7aa-67cf-4f5e-bd41-5340f08d1d0a.png)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
