### ISSUE TITLE
MS Learning Pathways site not provisioning

### ISSUE THREAD

**Issue by seancorryio** [SharePoint/sp-provisioning-service#599]
Hi, I previously had deployed learning pathways site, but no one did anything with it. The business decided to take another crack at it so I deleted the old site, and the app from SharePoint, but I cannot get a new site to provision. I have already verified the URL is available, I am owner/admin of app collection. I have also verified not a graph issue as I get a good 200 for the following via graph explorer, https://graph.microsoft.com/v1.0/sites/root . What am I missing?!

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Have you emptied the site collection recycle bin?

**Comment by seancorryio** [comment]
Not sure what you mean.... I deleted the site, then permanently deleted the site from the deleted sites list in the admin portal. The app was provisioned in app store and says deployed with no errors. but the site was not created (URL is confirmed available). 

Please report the issue here providing the following provisioning action correlation ID: 7d4e376c-e251-49d2-80ac-4e8273c10dea !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. We've just refreshed the solution and I invite you to test it now. In case of any problem, please create a new issue and provide the PnP Correlation ID (that you get by email together with the provisioning outcome), so that we can investigate it further. Thanks.
