### ISSUE TITLE
Can I provision multiple templates within same tenant at the same time?

### ISSUE THREAD

**Issue by sneranacdw** [SharePoint/sp-provisioning-service#602]
Describe the issue
I am currently provisioning Human Resources Hub template on multiple sites within same tenant. The issue is that it does not provision this template on multiple sites within same tenant

Expected behavior
Can I provision templates across multiple sites?

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Technically speaking, the Provisioning Service behind the scenes of the Look Book site can provision as many sites as you like on a single tenant. If you're experiencing issues with the Human Resources Hub, I'd suggest you double-check the documentation of that specific template to see if there are any technical constraints.
