### ISSUE TITLE
Human Resources Hub Site template takes long time to provision

### ISSUE THREAD

**Issue by sneranacdw** [SharePoint/sp-provisioning-service#603]
**Describe the issue**
I have been provisioning Human Resources Hub Site template and it takes very long time to provision. Previously it didn't take this long to provision

Is there any issue with the source template on the lookbook site?

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. As far as I know, there were no issues. However, we've just updated the service (a bit of technology refresh) so I invite you to try it again and see if it performs better. Nevertheless, keep into account that the provisioning of a site can take up to 15-20 mins, and that's a "normal" time.
