### ISSUE TITLE
Sites are being created by users who do not haver permissions to

### ISSUE THREAD

**Issue by srlact** [SharePoint/sp-provisioning-service#604]
Hi!

Users are creating new sites on our tenant from lookbook templates without the permissions to. We have site creation only allowed to SharePoint admins. Do you have an ideia why this is happening?

Thank you! 

SR

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. The Provisioning Service, behind the scenes of the Look Book site, creates sites with the requesting user's delegated access token. As such, I guess your users have permission to create sites.
