### ISSUE TITLE
Unable to provision template

### ISSUE THREAD

**Issue by rwbanks** [SharePoint/sp-provisioning-service#606]
**Describe the issue**
I have been attempting to provision 'The Landing' template to a new site, /teams/NBS.  The site does not currently exist.  When I attempt to provision, I receive an error, "Unfortunately your site provisioning at least partially failed!"  

**Expected behavior**
Attempting to utilize the Landing template to start with my new sharepoint team site.  

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action]    4f99bf26-8689-4478-8c8c-96febeeaba3a 
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{Template-ID}]    https://lookbook.microsoft.com/tenant/home/provision?packageId=c9300e94-6e83-471a-b767-b7878689e97e&returnUrl=https%3A%2F%2Flookbook.microsoft.com%2Fdetails%2Fc9300e94-6e83-471a-b767-b7878689e97e
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]  English
- Are you using a Tenant Global Admin account to provision the template: [Yes/No]  No, using my personal ID

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.

**Comment by rwbanks** [comment]
Thank you for the reply.  I have been trying to provision a template for a new site since Dec.  Lookbook was down for the month of Jan.  Now, as soon as I select a template and select the ‘add your tenet’ button, I receive this error for any of the templates.

Your feedback is appreciated.



Bob Banks, MBA, PMP
Sr. Manager, Program & Project Mgt.
National Benefit Solutions
National Benefits Administration (NBA)
501 Lennon Lane
Walnut Creek, CA 94598
(925) 926-5100 (Office)
(925) 324-7194 (Mobile)

***@***.***

Kaiser Permanente
HPPSA – National Benefit Administration (NBA)
kp.org/thrive<http://kp.org/thrive>
