### ISSUE TITLE
Unable to provision the site using "Collaboration team site" template

### ISSUE THREAD

**Issue by bhanu-bysani** [SharePoint/sp-provisioning-service#607]
**Describe the issue**
I have been attempting to provision 'Collaboration team site' template to a new site, /teams/Accounting. The site does not currently exist. When I attempt to provision, I receive an error, "Your request to provision "Collaboration team site" template failed!

Please report the issue here providing the following provisioning action correlation ID: 2872aeeb-8dfb-4df6-9b1b-b165053b27b7 !"

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing group alias. In fact, the exception from the service is: "The group alias already exists". Could you please try to provision the solution with a different name? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
