### ISSUE TITLE
correlation ID: 84b61c08-8704-4efe-8382-7eaa30dbfe7c

### ISSUE THREAD

**Issue by Naincy89** [SharePoint/sp-provisioning-service#608]
Hi Team,

While provisioning the MS learnings Pathway to the tenant, faced issue for the subjected correlation id.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/95854795/145380560-a034e1b8-782d-4026-84d9-5d9d126abc96.png)

**Comment by Naincy89** [comment]
Can we have the updates on the reported issue.
We are not able to proceed further.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you provided a vanity URL name for your target tenant and we do not support that scenario. You can eventually follow the manual provisioning steps illustrated here: https://docs.microsoft.com/en-us/office365/customlearning/custom_manualsetup. Thanks for your cooperation.
