### ISSUE TITLE
M365 Learning Pathways - Corrupt Playlists - Assets cannot be viewed or updated

### ISSUE THREAD

**Issue by LarsKragKongsgaard** [SharePoint/sp-provisioning-service#609]
[M365LP Bad playlists.zip](https://github.com/SharePoint/sp-provisioning-service/files/7687537/M365LP.Bad.playlists.zip)

9 out of 45 custom playlists seems to be corrupt and it is not possible to  view assets or update assets.

Please see attached screen shots of corrupt custom playlists.

Please help!

**Comment by dcashpeterson** [comment]
Hi @LarsKragKongsgaard thanks for submitting this. This looks like an issue with Learning Pathways and not a LookBook issue. If you could submit it to https://github.com/pnp/custom-learning-office-365/issues and fill out the template with any errors you are seeing in the console that team can assist you better.

**Comment by LarsKragKongsgaard** [comment]
Please just close this issue!
