### ISSUE TITLE
Service Down

### ISSUE THREAD

**Issue by Reddzman** [SharePoint/sp-provisioning-service#611]
**Describe the issue**
The service appears to be down.  When you select add to your tenant the page doesn't load properly. https://lookbook.microsoft.com/tenant/home/provision?packageId=3df8bd55-b872-4c9d-88e3-6b2f05344239&returnUrl=https%3A%2F%2Flookbook.microsoft.com%2Fdetails%2F3df8bd55-b872-4c9d-88e3-6b2f05344239

**Expected behavior**
The pages should load properly and allow you to authenticate to your tenant.

**Screenshots**
![image](https://user-images.githubusercontent.com/26889712/147496437-ac079bb4-a83f-4ee0-a4c8-089432467591.png)

**Details (please complete the following information):**
- Device: MS Surface Laptop 4 w/ Windows 11
- OS: Windows 11
- Browser: Edge Chromium

**Additional context**
Attempting to provision learning pathways to a dev tenant.  I tested a couple other templates and they all seem to have a similar behavior. I am guessing a service needs to be restarted.

**Comment by Matt-Thomp** [comment]
Does anyone know when the SharePoint Lookbook will be back online, as it only states Jan 2022.

**Comment by hvandesa** [comment]
Any updates?  This is impacting our migration as we use these templates.

**Comment by BlakeSweeting** [comment]
Do we know when the Lookbook service will be back online?

**Comment by fabizkk** [comment]
Any updates on the given issue

**Comment by fixittech99** [comment]
Looking for an update as well.  Tried the manual provisioning and it came back with errors too.

**Comment by BlakeSweeting** [comment]
Any update?

**Comment by DigitalLifeAdvisor** [comment]
Still no update?

**Comment by igord93** [comment]
Any update? We are planning to initiate the SharePoint Online deployment in the company but this is holding us back.

**Comment by BlakeSweeting** [comment]
Someone who knows how, can you leave some step by step instructions on how to manually provision the templates please

**Comment by PaoloPia** [comment]
Hi,
The Look Book service is back to work: https://lookbook.microsoft.com/
