### ISSUE TITLE
Unfortunately your site provisioning at least partially failed!

### ISSUE THREAD

**Issue by reochris** [SharePoint/sp-provisioning-service#616]
**Describe the issue**
When trying to provision sites from look book templates I consistently receive the error message "Unfortunately your site provisioning at least partially failed!"  with no further explanation.

Specifically I'm trying to do a "New employee corporate onboarding site", although I've tried a couple of other templates with the same result.

I've attempted this while logged into two different accounts with 365 global admin permissions.  Also attempted disabling MFA on one of these, but that didn't make a difference.

**Expected behavior**
I expected provisioning to complete successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/98765562/151838806-4c47f8c2-2f4e-4aef-946e-27e7227bd740.png)

**Details (please complete the following information):**
- PnP Correlation ID: It doesn't supply one of these.
- Reference Template: https://lookbook.microsoft.com/tenant/Home/Provision?returnUrl=https%3A%2F%2Flookbook.microsoft.com%2Fdetails%2F388a159f-475b-4557-9088-c9073a26c576&source=default
- Primary language of the target tenant: US English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by rizzped** [comment]
Im getting the same Issue as well.

**Comment by reochris** [comment]
> Im getting the same Issue as well.

I managed to get around it by provisioning manually using PnP PowerShell and the template files from this github.

https://pnp.github.io/powershell/articles/installation.html

It was buried, but I found a Microsoft site that said look book provisioning was offline "until January 2022" - I'm thinking maybe they haven't gotten back up and running yet.

**Comment by BlakeSweeting** [comment]
Same here

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. We've just refreshed the solution and I invite you to test it now. In case of any problem, please create a new issue and provide the PnP Correlation ID (that you get by email together with the provisioning outcome), so that we can investigate it further. Thanks.
