### ISSUE TITLE
M365 Learning Pathways Failing to Provision

### ISSUE THREAD

**Issue by giacinto41** [SharePoint/sp-provisioning-service#617]
**Issue**
While the Provisioning service was down, I tried provisioning manually. It succeeded but the site didn't look right so I decided to delete the Learning Pathways site that was created and the customlearning package I added to the App Catalog. I waited for the provisioning service to come back online and tried again. 

I filled in the fields to provision the site, once the popup "Validating Prerequisites" came up, it would disappear and I wouldn't get the popup confirming what would be provisioned.

**Expected behavior**
A popup confirming what would be provisioned.

**Comment by jean-luc-chatton** [comment]
Hi, I've got the same issue. Is it possible that the provisioning is still not functioning after the maintenance?

**Comment by giacinto41** [comment]
Could be but since I tried to manually provision beforehand, maybe there are still remnants of the previous install that I am not noticing or that I forgot to remove.

Anyone able to shed some light on this??

Thanks

**Comment by jean-luc-chatton** [comment]
Now it goes a step further: it starts the provisioning, says "in progress" and finally "complete". But no site is created and the SharePoint app in not loaded.

**Comment by giacinto41** [comment]
Yep tried that myself and that's where I get now as well. Did you get the email that says provisioning is complete and successful?

**Comment by giacinto41** [comment]
My provisioning was completed and I see that the app and site were created but I did not get an email confirming that it was completed, nor did I get the link to finish the setup (CustomLearningAdmin.aspx). Should I go to this link manually or wait for the email?? If so what would be the rest of the URL after my M365 Site URL?

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. We've just refreshed the solution and I invite you to test it now. In case of any problem, please create a new issue and provide the PnP Correlation ID (that you get by email together with the provisioning outcome), so that we can investigate it further. Thanks.
