### ISSUE TITLE
New Employee pre-onboarding site Template

### ISSUE THREAD

**Issue by github-scottd** [SharePoint/sp-provisioning-service#618]
**Describe the issue**
A clear and concise description of what the issue is.

Unfortunately your site provisioning at least partially failed!

**Expected behavior**

Creation of New Employee pre-onboarding site template into SP.

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: None provided.
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/8fefcc9a-7ca4-457f-bd10-acee3ae63b63
- Primary language of the target tenant: UK British
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Unfortunately, without any actual detail about the provisioning (PnP Correlation ID, or tenant name, etc.) we cannot investigate the issue further. Could you please try to provision the solution again and eventually look for the exception you will get by email? In the exception there should also be the PnP Correlation ID. Thanks for your cooperation.

**Comment by github-scottd** [comment]
Hi,

No PnP Correlation ID or email is provided when trying to provision the solution.
