### ISSUE TITLE
Issue provisioning Lookbook template

### ISSUE THREAD

**Issue by rwbanks** [SharePoint/sp-provisioning-service#620]
I am unable to  provision the Leadership template using Lookbook.  After selecting the template, I select the 'add to your tenant' button and receive the following error.  This occurs no matter which template I select.  please advise

Sorry, something went wrong
There was an unexpected issue.
An item with the same key has already been added

**Comment by PaoloPia** [comment]
Hi,
Thanks for using Look Book. What kind of tenant are you targeting? Is it a demo or Gov tenant? I'd like to have additional details in order to help you. Thanks.

**Comment by rwbanks** [comment]
Thank you so much.  I am looking to provision the Professional template located at SharePoint look book - Leadership Connection (microsoft.com)<https://lookbook.microsoft.com/details/c19f437b-35ca-42f2-b27a-1caa49ad8bde>

Thank you



Bob Banks, MBA, PMP
Sr. Manager, Program & Project Mgt.
National Benefit Solutions
National Benefits Administration (NBA)
501 Lennon Lane
Walnut Creek, CA 94598
(925) 926-5100 (Office)
(925) 324-7194 (Mobile)

***@***.***

Kaiser Permanente
HPPSA – National Benefit Administration (NBA)
kp.org/thrive<http://kp.org/thrive>

**Comment by igord93** [comment]
From my side provisioning is not working too, why were the other issues closed if it is still not working?

Your request to provision
"The Landing" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: 73b14413-e2a3-4d58-950c-d610ad855d45 !

**Comment by igord93** [comment]
Even though now the SharePoint "passes" the provisioning site, when you go to access the created site it does not bring the template wanted.

**Comment by PaoloPia** [comment]
Hi,
here are some details:
- @rwbanks: please give me your tenant ID or PnP Correlation ID so that I can check the logs. Unfortunately, the name of template you are trying to apply is not enough to investigate your issue. Thanks.
- @igord93: the exception on your side is "Current user is not a tenant administrator". If you are not a tenant admin, you cannot provision the template called "The Landing". In fact, as stated on the template page "You must be a tenant administrator to deploy this template."

**Comment by rwbanks** [comment]
Thank you.  I’m not sure what the ID is, but here is the URL for the template I am trying to provision.

SharePoint look book - Leadership Connection (microsoft.com)<https://lookbook.microsoft.com/details/c19f437b-35ca-42f2-b27a-1caa49ad8bde>





Bob Banks, MBA, PMP
Sr. Manager, Program & Project Mgt.
National Benefit Solutions
National Benefits Administration (NBA)
501 Lennon Lane
Walnut Creek, CA 94598
(925) 926-5100 (Office)
(925) 324-7194 (Mobile)

***@***.***

Kaiser Permanente
HPPSA – National Benefit Administration (NBA)
kp.org/thrive<http://kp.org/thrive>

**Comment by PaoloPia** [comment]
Hi,
I would simply suggest you try again. We improved a lot the service in the last few days.
In case of any issue, please create another item in this issue and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
