### ISSUE TITLE
Language issue with Microsoft 365 learning pathways 

### ISSUE THREAD

**Issue by jean-luc-chatton** [SharePoint/sp-provisioning-service#621]
**Describe the issue**
After provisioning, there are 2 multi-language issues:
1) 9 languages can be chosen  although I removed all but English, French and Spanish 
2) The contents of the training pages are not translated (text and videos)

**Expected behavior**
1) Only the selected languages should appear in the language menu
2) Contents of training pages are supposed to be translated 

**Screenshots**
![image](https://user-images.githubusercontent.com/55661955/152303984-3246fa89-dc1b-420d-a0dc-4c71487181c1.png)
![image](https://user-images.githubusercontent.com/55661955/152304021-11c3782d-d0d0-4a8a-809e-07fc9c75ff07.png)
![image](https://user-images.githubusercontent.com/55661955/152304034-57c9e82c-ec99-4240-ab9e-d5f69ded1e49.png)

**Details (please complete the following information):**
- PnP Correlation ID: N/A
- Reference Template :Microsoft 365 learning pathways
- Primary language of the target tenant: Englsih
- Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by AgathaL** [comment]
My problem is similar to the one described above

When  installing Microsoft Learning Pathways, I checked that the multiple languages are .As shown in the prints below.

 
![image](https://user-images.githubusercontent.com/102544649/160452968-b49e921f-4345-4e3c-8e9e-e46af7240f07.png)

![image](https://user-images.githubusercontent.com/102544649/160453041-17d6e442-9bf0-4844-b97e-e75e1a5eec4e.png)
 

However, when you go to the site and select a different language, the page is not full translated.


Where I circulated the content were automatically translated, but the word Noticias and Add, did not translate. Just like the header and web part of content did not translate as well, and they are pages that already come with the site.
 

![image](https://user-images.githubusercontent.com/102544649/160453112-8dccc8d9-7b17-4d2f-b941-cefb4fc929d6.png)



These pages come by default and are found in the content of the site as shown below:


![image](https://user-images.githubusercontent.com/102544649/160453151-ee22f29a-595e-4646-bd04-3e258ed0c8fa.png)
 

On the screen below, is the folder where the screens already created by Microsoft come by default when doing the installation.

 
![image](https://user-images.githubusercontent.com/102544649/160453192-ae115003-759d-4566-a70b-eb04aaf42f42.png)

![image](https://user-images.githubusercontent.com/102544649/160453231-52a60653-df25-4cd8-a9b2-fdd5d6f96445.png)
 

But when I select the pages created in there, some come translated in half, and others translated in full.


Content translated in half (untranslated header)
 
![image](https://user-images.githubusercontent.com/102544649/160453264-d7410318-d3e2-4d13-a01d-ca49984ebfd5.png)


Full translated content (less header)

 
![image](https://user-images.githubusercontent.com/102544649/160453285-99c5ce19-e8fb-460c-ae79-ec9bcca8fc08.png)

 
![image](https://user-images.githubusercontent.com/102544649/160453299-3cec811c-293b-4d9a-be92-b2be9c22a097.png)



Only when I click the Microsoft 365 training tab are translations not done entirely. The other flaps are normal. Regardless of my regional choice.
With that, could you please help me  understanding the reason for some pages come translated whole and others in half. And knowing why the head doesn't come translated, if it would be standard or we'd have to customize that translation ?
I watched the videos of the content you sent about some parts of this translation issue, but that part of content that already comes on the site I have no way to change and I believe that the default pages should already be translated within each folder of each language.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. I'm going to close this item because it has been stale for a long time. Thanks for your understanding.
