### ISSUE TITLE
Provisioning passes but does not apply the template.

### ISSUE THREAD

**Issue by igord93** [SharePoint/sp-provisioning-service#622]
**Describe the issue**
Even though now the SharePoint "passes" the provisioning site, when you go to access the created site it does not bring the template wanted.

**Expected behavior**
Site should have the look we have chosen.

**Screenshots**
![image](https://user-images.githubusercontent.com/98459206/152580848-9baf6617-47a6-4e34-b7a2-e8fc8f2792d3.png)
![image](https://user-images.githubusercontent.com/98459206/152580622-e4eade68-cbd6-4fa3-b570-79a424b2f9d5.png)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Could you please provide additional details like the PnP Correlation ID or the tenant ID?Thanks for your cooperation.

**Comment by igord93** [comment]
Here is the correlation ID from my last try, not the one in the screenshots:

8ded3466-a8be-4c1d-a02b-c41624307d1f

**Comment by PaoloPia** [comment]
Hi,
Thanks for the additional details. Based on what I see on the logs, it looks like you simply experienced some hiccups, plus you tried to reuse the same site URL more than one time. My advice is to delete the previously created sites, remove them from the site collections recycle bin, and then try again. Or you can eventually simply provide the URL of a site that does not exist in your tenant. The service will create it for you and do the actual provisionioning. Please, let me know ...

**Comment by igord93** [comment]
We tried again with a totally different name and it worked, funny that the example I gave when as described. Thank you
