### ISSUE TITLE
Your request to provision "Human resources hub"  template failed!

### ISSUE THREAD

**Issue by joshjames1109** [SharePoint/sp-provisioning-service#623]
I am trying to set up an employee portal/HR page via sharepoint. Tried using the Human resources hub template and it has failed several times. I am not sure what to do from here but here is the code the error email provided. correlation ID: b4b62044-3bab-426d-962f-5548d4786b92 !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you applied the template providing the URL of a site that was already in the recycle bin of SharePoint Online. Please, provide a different URL or empty the recycle bin. Thanks.

**Comment by joshjames1109** [comment]
Hi, 
thank you for your reply. I actually do not see anything in my recycle bin.

**Comment by PaoloPia** [comment]
Please, check the site collection recycle bin in the SPO Admin Center. I clearly see the following error message: " The requested Communications Site at https://****.sharepoint.com/sites/hr-works is in the Recycle Bin and cannot be created "
