### ISSUE TITLE
Your request to provision "The Landing"  template failed!

### ISSUE THREAD

**Issue by khelmi84** [SharePoint/sp-provisioning-service#624]
Your request to provision "The Landing" template failed!

This has happened multiple times....

provisioning action correlation ID: 
c918b676-678b-426a-a43e-56b24de2d3a6 ! 

Reference Template: 
https://lookbook.microsoft.com/details/c9300e94-6e83-471a-b767-b7878689e97e

Thanks - Karim

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Inpsecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while creating the target Communication Site (the exception was 403 - "Forbidden"). Could you please try to provision the solution to a different site URL or with a different user account? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.

**Comment by khelmi84** [comment]
Thank you. I tried and I get the same...
Your request to provision
"The Landing" 
template failed!
provisioning action correlation ID: c449037e-3489-4430-aef6-019613dbfe9e !
