### ISSUE TITLE
correlation ID: 7833b77f-7ac3-4176-9d4e-dce49ac38964 ! 

### ISSUE THREAD

**Issue by yabbas** [SharePoint/sp-provisioning-service#626]
**Describe the issue**
Trying to apply class template.

**Expected behavior**
Template applied.

**Screenshots**
Correlation ID: 7833b77f-7ac3-4176-9d4e-dce49ac38964 ! 

**Details (please complete the following information):**
- PnP Correlation ID: 7833b77f-7ac3-4176-9d4e-dce49ac38964 ! 
- Reference Template: https://lookbook.microsoft.com/details/f70a722f-e20a-4f0e-a0e7-ed75b3c9a74a
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: [No]

**Additional context**
Admin isn't willing to give any access rights - could this be it?  He's afraid!

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Inspecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while trying to get the access token to access the admin services of SharePoint Online. So, it might be that the tenant admin did not consent permissions for the app. Could you please try provisioning the solution with a different user account (tenant admin)? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
