### ISSUE TITLE
LookBook Shows Provisioning completed but hasn't created the SharePoint Site

### ISSUE THREAD

**Issue by Matt-Thomp** [SharePoint/sp-provisioning-service#627]
**Describe the issue**
Go to SharePoint look and try and provision a site.  It validates everything and when you click provision, it finishes quicker than normal and shows provisioning completed.

If you then try and access SPO site via the url you get 404 file not found.

In the SharePoint admin centre the site doesn't appear to have even been created.

**Expected behavior**
After provisioning the site expect to click on the url and start customising the site.  And the site to appear in the SPO Admin centre.

**Screenshots**
![image](https://user-images.githubusercontent.com/97171268/153216342-9af4fb59-6d68-40d0-ae24-b84c848944df.png)

**Details (please complete the following information):**
https://lookbook.microsoft.com/tenant/Home/Provision?returnUrl=https%3A%2F%2Flookbook.microsoft.com%2Fdetails%2Fc9300e94-6e83-471a-b767-b7878689e97e&source=default
- Reference Template: 
- https://lookbook.microsoft.com/tenant/home/provision?packageId=c9300e94-6e83-471a-b767-b7878689e97e&returnUrl=https%3A%2F%2Flookbook.microsoft.com%2Fdetails%2Fc9300e94-6e83-471a-b767-b7878689e97e
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: [Yes/No] YES

**Additional context**

**Comment by Matt-Thomp** [comment]
@PaoloPia another user has logged the same issue #628 I wonder if it has something to do with the global outage the other week where you couldn't access the admin portals or portal.office.com as it was working up until that point.

**Comment by PaoloPia** [comment]
Hi @Matt-Thomp,
Thanks for using the Look Book site. These days we're processing a huge amount of requests and sometimes it takes longer than usual to provision a template. For sure, you should not see the provisioning as "completed" if it is not, and we're investigating that issue. However, I would advise you to trigger a new request and wait for up to one hour. Meanwhile, we're planning to scale out the service more. Thanks.

**Comment by Matt-Thomp** [comment]
@PaoloPia sure I will try a new request and see what happens and feedback.

**Comment by Matt-Thomp** [comment]
@PaoloPia  just tried another site and it has provision and received an email confirmation as normal.  Not sure what happen earlier with the lookbook site, still no email confirmation on the other site that seem to be provision on the website and not in the SPO admin centre.  I guess you close it off as I will re-provision the earlier sites again.

**Comment by PaoloPia** [comment]
Thanks for the update.
