### ISSUE TITLE
Provisioning completed but gettting file not found.

### ISSUE THREAD

**Issue by michaelpayne636** [SharePoint/sp-provisioning-service#628]
**Describe the issue**
Provisioned the Learning Pathways template. Provisioning Status: Provisioning completed. But when navigating to <YOUR-SITE-COLLECTION-URL>sites/<YOUR-SITE-NAME>/SitePages/CustomLearningAdmin.aspx I get 404 FILE NOT FOUND.

**Expected behavior**
Sucessful provisioning of template.

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: None
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English US
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
I was able to deploy and access the following template. https://lookbook.microsoft.com/details/99d3b7ea-6ca0-430e-96bc-922d4d2de2ab

**Comment by Matt-Thomp** [comment]
I'm having the same problem unable to provision sites at the moment.  I wonder if it has something to do with global outage where you couldn't access the admin portals or portal.office.com the other week.  Was working fine until that happened.

**Comment by michaelpayne636** [comment]
Tried deploying again under a different name. This time I received an email that said provisioning failed.
correlation ID: bbf8eb39-2e5c-470c-a848-fb4840f3c391

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the log I can see that the issue was an "Access Denied" while trying to upload the customlearning.sppkg file to the App Catalog. Could you please check that you have proper permissions and eventually manually remove the file from the App Catalog before applying the template? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.

**Comment by Matt-Thomp** [comment]
@michaelpayne636 @PaoloPia  Nope I don't get that.  Just get provisioning completed and then '404 FILE NOT FOUND' site doesn't appear in the admin centre.  I have global admin and SPO Admin rights.

**Comment by PaoloPia** [comment]
@Matt-Thomp my reply was for @michaelpayne636. I'm going to reply to you in the issue tha you opened (#627).

**Comment by michaelpayne636** [comment]
FYI - someone had removed administrative permissions to the app catalog. After re-adding them I was able to provision the template successfully.
