### ISSUE TITLE
Issue with Provisioning "Learning Pathways" using look book template

### ISSUE THREAD

**Issue by amitkh22** [SharePoint/sp-provisioning-service#631]
**Describe the issue**
Getting error "Provisioning Status: Unfortunately your site provisioning at least partially failed!"

**Expected behavior**
It should provision a communication site with Learning Pathways webpart.

**Details (please complete the following information):**
I'm trying to provision Learning Pathways site using lookbook but getting error "Provisioning Status: Unfortunately your site provisioning at least partially failed!" I'm using a global admin account to provision it.
Below are some of the points which I observed - 

      - Package gets added to app catalog and the version is 4.3.0.0. However, the latest version of Learning Pathways webpart is 4.3.1.0
      - Site collection gets created and lists also created.
      - No content in the lists and no site pages created

- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

@dcashpeterson

**Comment by rkhouri-cec** [comment]
I have the same issue.  Thanks for posting it in the right place amit.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Could you please provide some detailed information like the PnP Correlation ID (you can find it in the email we've sent you) or the tenant ID? Thanks for your cooperation.

**Comment by amitkh22** [comment]
Hi @PaoloPia, I do not have any correlation Id as I didn't receive any email for it. My tenant ID is 5852d859-73b5-4d57-9814-f2131d8e92e6.

**Comment by PaoloPia** [comment]
Hi,
This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. It stopped during views creation. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
