### ISSUE TITLE
Unfortunately your site provisioning at least partially failed!

### ISSUE THREAD

**Issue by rkhouri-cec** [SharePoint/sp-provisioning-service#632]
**Describe the issue**
Trying to install the M365 learning pathways template from lookbook but it keeps failing with the error
"Unfortunately your site provisioning at least partially failed! ".  Only the web part is being installed to the app catalog, but the site collection is never created.   

**Expected behavior**
The expected behavior is for the site collection M365LP  and web part to be installed. 

**Screenshots**
![M365LP fail​](https://user-images.githubusercontent.com/99621836/154192140-761c0e34-2ca2-4a41-9772-8a4945f27188.png)
![app catalog](https://user-images.githubusercontent.com/99621836/154192150-2adfaec1-2557-4307-8da5-fa082c16b278.png)

**Details (please complete the following information):**
- PnP Correlation ID: I am not able to provide the correlation ID because the site collection is not getting created
- TenantID:  ba563343-fb55-4793-949a-e252d6714fa3
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
I have tried to remove the app from both stages of the catalog recycle bin and verified I do not have site collections with the same name ie.) M365LP.   Still the same result

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site, which is a scenario that we do not support. Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
