### ISSUE TITLE
Hi, We are trying to access to learning path package to deploy in a customer environment but URL: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239. doesn't work. Could you help us? Thanks

### ISSUE THREAD

**Issue by AGGMI** [SharePoint/sp-provisioning-service#633]
Hi, We are trying to access to learning path package to deploy in a customer environment but URL: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239. doesn't work. Could you help us? Thanks

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. It was a temporary issue, which is now fixed. Please try again. Thanks.
