### ISSUE TITLE
Template is not Provisioned in the Tenancy

### ISSUE THREAD

**Issue by micha3l2022** [SharePoint/sp-provisioning-service#634]
When I try to provision a Look Book template in our Sharepoint, I'm unable to access the Site URL.
![Sharepoint 2](https://user-images.githubusercontent.com/104752971/166217601-c90a2528-9694-4d01-8d7c-ffc6888aa598.png)
![Sharepoint 1](https://user-images.githubusercontent.com/104752971/166217608-fd1a5e4d-32d9-4ef2-a2af-575d9bb73d59.png)

- PnP Correlation ID: 
- Reference Template: https://lookbook.microsoft.com/details/bb8e1900-b40f-4791-b667-f963af651111
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
