### ISSUE TITLE
Template on Microsoft LookBook for TheLanding template fails with not specific error codes

### ISSUE THREAD

**Issue by ghost** [SharePoint/sp-provisioning-service#635]
**Describe the issue**
My coworker and myself have tried several times this week to deploy TheLanding template from Microsoft Lookbook.  I my case it stated that it partially failed.  I can see the site but I have no idea what is missing.

**Expected behavior**
I have deployed other templates from Microsoft Lookbook, I expected it to deploy so I could continue our work.

**Screenshots**
![image](https://user-images.githubusercontent.com/7130015/166583396-03ca18bc-9745-4ddd-914c-1dcdcde03b52.png)

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action]
I don't have this one.
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{Template-ID}]
- https://lookbook.microsoft.com/tenant/Home/Provision?returnUrl=https%3A%2F%2Flookbook.microsoft.com%2Fdetails%2Fc9300e94-6e83-471a-b767-b7878689e97e&source=default

- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- English
- Are you using a Tenant Global Admin account to provision the template: [Yes/No] YES

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This seems to be a random hiccup on the SharePoint side which would imply that the template should work properly if you try it one more time. Seems that the provisioning did succeed partially. Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow. Thanks.
