### ISSUE TITLE
Unable to access the SharePoint lookbook M365LP

### ISSUE THREAD

**Issue by Emilie-Garnaud** [SharePoint/sp-provisioning-service#638]
**Describe the issue**
I have 2 issues :
1. I tried, this morning, to provision de M365LP, unfortunately I didn't know that a site with the same URL already exists in my tenant and I had an issue during the povisioning. I cheched in my App Catalogue, and "Microsoft 365 learning pathways" is in my applications list. But not deployed on a site collection. So I wanted to start again the process.

2. But now, I'm unable to access this link https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239 to install learning pathways into my tenant. this link redirect me on th SharePoint look book home page.

**Details (please complete the following information):**
- PnP Correlation ID: 
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: 
- Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. This was a random hiccup. Please try again, it should be fine now. Thanks.
