### ISSUE TITLE
Error on NEW EMPLOYEE DEPARTMENTAL ONBOARDING SITE Template

### ISSUE THREAD

**Issue by salviroshan89** [SharePoint/sp-provisioning-service#652]
**Describe the issue**
Getting Sorry, Something went wrong when we click on Add to your tenant option for below temaplate:
https://lookbook.microsoft.com/details/99d3b7ea-6ca0-430e-96bc-922d4d2de2ab
I am a SharePoint Online Adminstrator

**Expected behavior**
It should allow to create site using NEW EMPLOYEE DEPARTMENTAL ONBOARDING SITE Template.

**Screenshots**
![SiteProvisioningError](https://user-images.githubusercontent.com/108810665/177554032-d691b459-bf56-4c8c-812a-fd27e8ad34eb.PNG)

**Details (please complete the following information):**
- PnP Correlation ID: Didnt got any correrelation id on error page
- Reference Template: https://lookbook.microsoft.com/details/99d3b7ea-6ca0-430e-96bc-922d4d2de2ab
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: [Yes/No] No. I am SharePoint Administrator.

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Unfortunately, without a Correlation ID, it is really difficult to figure out what went wrong.  Can you test this one more time and, in case of any failure, share the updated Correlation ID (by creating a new issue) for us to double-check the flow? You can eventually find the Correlation ID in the error email that you will receive or by pressing F12 in the browser during provisioning and searching for a request for https://lookbook.microsoft.com/tenant/home/IsProvisioningCompleted?correlationId=<Correlation ID>. Thanks.
