### ISSUE TITLE
Learning Pathways missing from SharePoint Lookbook Provisioning site

### ISSUE THREAD

**Issue by Matt-Mueller-MSFT** [SharePoint/sp-provisioning-service#657]
Looks like the Learning Pathways is not showing up on the SharePoint Lookbook Provisioning service as of today. I know it was there Friday. But today it is missing under solutions and all the links I had that pointed to it only just go to the Lookbook page itself. Any updates here?

**Comment by PaoloPia** [comment]
Hi, Thanks for your message. It was a temporary hiccup.
