### ISSUE TITLE
Problem with the Learning pathway template

### ISSUE THREAD

**Issue by maye-vargas** [SharePoint/sp-provisioning-service#663]
At the moment I enter the link https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
It doesn't let me log in or it doesn't show me the LP template, which doesn't let me generate the learning pathway template.
![image](https://user-images.githubusercontent.com/86726190/187252285-b0101a1e-e719-4d9e-a7d5-3c70fa684864.png)

**Comment by VesaJuvonen** [comment]
Thank you for flagging this. We have started looking into this, but there's no ETA for resolving this. We have a hunch on what could be the root cause, but we'll need to still have a closer look. Issue resolution can be expected to be in around 24/48 hours.

**Comment by maye-vargas** [comment]
@VesaJuvonen Ok, but for the moment is there any other link that I can use for the implementation of the learning pathway?

**Comment by VesaJuvonen** [comment]
A bit faster than expected - Learning Pathways is back online at https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
