### ISSUE TITLE
Sample config files

### ISSUE THREAD

**Issue by Jonas-buriti** [SharePoint/sp-provisioning-service#682]
Hi!

Can you guys provide sample config files?
I see that is missing on Infrastructure, WebJob, and other projects.

I'm currently working on updates to support PnP Framework lib, and the config models would help to setup a functional dev enviroment.

Tks!

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. I'm going to close this item because it has been stale for a long time. Thanks for your understanding.
