### ISSUE TITLE
LookBook Provisioning Error

### ISSUE THREAD

**Issue by kwoulfe-calchamber** [SharePoint/sp-provisioning-service#685]
Unfortunately your site provisioning at least partially failed!

I see a lot of people with this same problem, but not a lot of resolution. I get this error when attempting to provision a template from LookBook. It seems that others have an issue with emptying their recycle bin, which I have done. But that did not help.

Any help appreciated!

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Can you provide detailed information about the provisioning that failed? Can you share the provisioning ID? Thanks.

**Comment by ejselloria** [comment]
Hi, I am currently encountering this error when adding a lookbook template to the tenant. Note that I have been guided by a Microsoft agent and walked through the admin properties required.

How do I go further on this?

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Can you please provide the provisioning ID of the failing action, or at least any detail about the target tenant name and date/time of provisioning so that we can investigate the service logs and try to give you proper support? Thanks.

**Comment by ejselloria** [comment]
Hi,

Please take note of the following:
1. Message received when provisioning:
![MicrosoftTeams-image](https://github.com/SharePoint/sp-provisioning-service/assets/45184995/71f7fc02-ea33-49d2-a44e-0817bcbf61b7)

2. Tenant:
unitedlaboratoriesinc.sharepoint.com

3. Network logs:
[lookbook.microsoft.com_networklogs.txt](https://github.com/SharePoint/sp-provisioning-service/files/12034742/lookbook.microsoft.com_networklogs.txt)

Thank you!

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. I'm going to close this item because it has been stale for a long time. Thanks for your understanding.
