### ISSUE TITLE
SharePoint Look Book 'Learning Pathways' - Guest Users Unable To Access

### ISSUE THREAD

**Issue by SaraW-SoCo** [SharePoint/sp-provisioning-service#687]
**Describe the issue**
I've provisioned the 'Microsoft 365 Learning Pathways' into my tenant, and while access for users who are tenant members works as expected, **I've been unable to grant access to tenant Guest users**.
The Guest users are added as VISITORS (I've also tried adding them as MEMBERS - no difference); and while they can get to the initial home page of the Learning Pathways site, as soon as they try to access any content a "Something went wrong..." error comes up; the TECHNICAL DETAILS are always identical, regardless of Guest user.

**Expected behavior**
Tenant Guests should be able to access the 'Microsoft 365 Learning Pathways' training resources.

**Screenshots**
The ERROR and CALL STACK are always the same:
<img width="912" alt="image" src="https://github.com/SharePoint/sp-provisioning-service/assets/134746217/aa7795e7-021b-4cf4-8378-5dcf5cdb5bc5">

**Details (please complete the following information):**
- PnP Correlation ID: [I'm sorry, but I don't know where to find this information]
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: English US
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
I did find a reference somewhere that Guest users also needed READ permission to the App Library for the content to work, and I *think* I added those permissions as well; no change.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. I'm going to close this item because it has been stale for a long time. Thanks for your understanding.

**Comment by SaraW-SoCo** [comment]
Of course – and thank you for responding! It’s been quite some time since I looked at this.
Best regards,
Sara Windsor

--------------------------------------------------
Sara Windsor
Network Analyst, DCO
707.565.3062
