### ISSUE TITLE
Unable to provision SharePoint Starter Kit or Microsoft 365 learning pathways

### ISSUE THREAD

**Issue by KrimsonAce** [SharePoint/sp-provisioning-service#69]
Hello, I was pointed here to report my issue by Office 365 support. I hope you'll be able to help me as I'd like to push SharePoint within the business and I think these solutions will help greatly with that.

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Being able to provision both of the solutions available at https://provisioning.sharepointpnp.com/

#### Observed Behavior

Receiving an error that prerequisites are not fulfilled, requesting that I have full control permissions on the app catalog, which I do.

[FireShot Capture 018 - SharePoint Online Provisioning Service - provisioning.sharepointpnp.com.pdf](https://github.com/SharePoint/sp-dev-docs/files/3627039/FireShot.Capture.018.-.SharePoint.Online.Provisioning.Service.-.provisioning.sharepointpnp.com.pdf)
[FireShot Capture 019 - Manage site collections - zeusjuice-admin.sharepoint.com.pdf](https://github.com/SharePoint/sp-dev-docs/files/3627040/FireShot.Capture.019.-.Manage.site.collections.-.zeusjuice-admin.sharepoint.com.pdf)

#### Steps to Reproduce

- Visiting https://provisioning.sharepointpnp.com/
- Signing into my Office 365 Admin account
- Selecting the solutions tab
- Selecting either SharePoint Starter Kit or Microsoft 365 learning pathways
- Selecting add to tenant
- Filling out the required information and selecting provision

Many thanks

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
