### ISSUE TITLE
No support for RTL languages

### ISSUE THREAD

**Issue by rafi4242** [SharePoint/sp-provisioning-service#691]
**Describe the issue**
When provisioning a site with Lookbook you can't choose language, as opposed to create a regular communication website. 
When I create a communication website and choose a RTL langauge, such as Hebrew, the site UI can become RTL.
With lookbook all websites are LTR.

**Expected behavior**
Be able to choose different language when provisioning a website, as possible with a creation of regular communication site.

**Screenshots**
![image](https://github.com/SharePoint/sp-provisioning-service/assets/96187050/860e1030-9398-457a-b6c6-4776e5c2d550)

**Details (please complete the following information):**
- Device: Desktop
- OS: Win10
- Browser: Edge Chromium/Edge/Chrome

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. I'm going to close this item because it has been stale for a long time. Thanks for your understanding.
