### ISSUE TITLE
Pre-requirements not fullfilled

### ISSUE THREAD

**Issue by walterwalldmg** [SharePoint/sp-provisioning-service#695]
**Describe the issue**
We are trying to activated the Contracts Management form here: https://lookbook.microsoft.com/details/a8fc15e1-2bbe-43b9-98a0-99d3a997589c

**Expected behavior**
We configured the Microsoft Snytax Pay-Go as descriped at the documentation https://learn.microsoft.com/en-us/microsoft-365/syntex/syntex-azure-billing

**Screenshots**
![image](https://github.com/SharePoint/sp-provisioning-service/assets/66826084/d098fe6a-113c-4985-b6f5-1f9469d282ce)

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action]
- Reference Template: https://lookbook.microsoft.com/details/a8fc15e1-2bbe-43b9-98a0-99d3a997589c
- Primary language of the target tenant: english
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi, Thanks for using the Look Book site. About your issue, you should move to the out of the box templates available in the product. We just disabled the templates for Syntex in the Look Book site.

**Comment by walterwalldmg** [comment]
Where can i find this out of the box templates?

**Comment by walterwalldmg** [comment]
Hi @PaoloPia where can I find this out of the box templates?
