### ISSUE TITLE
Delete lookbook application from tenant.

### ISSUE THREAD

**Issue by PBC-SureshYarabarla** [SharePoint/sp-provisioning-service#697]
**Describe the issue**
Disable or delete Look book template feature in SharePoint tenant.

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
We had added look book template to our tenant and currently anyone in the organization is able to create a new SharePoint site using this template. Our current security configuration is limited to few people creating SharePoint site and now anyone can do it. Can this be controlled? If not, how do we get the feature removed from our tenant? We are not able to find lookbook in registered apps.

- Device: [Desktop/Tablet/SmartPhone]
 Desktop
- OS: [Windows/MacOs/iOS/Android/etc.]
Windows
- Browser: [Edge Chromium/Edge/Chrome/Firefox/etc.]
Edge & Chrome

**Additional context**

**Comment by PaoloPia** [comment]
Hi, you can remove the multi-tenant application from you tenant, under the Enterprise Applications section of Azure Entra ID, and no one will able to provision sites via Look Book anymore. I'm going to close this item. Thanks for your feedback.
