### ISSUE TITLE
"add to your tenant" redirects to the manual install guide

### ISSUE THREAD

**Issue by ExecuteRestart66** [SharePoint/sp-provisioning-service#698]
Pretty straightforward here. 

when I try to access any of these lookbook templates like this one
https://lookbook.microsoft.com/details/8fefcc9a-7ca4-457f-bd10-acee3ae63b63

and I click "add to tenant" 

I get redirected here
https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/applying-pnp-templates

I can't find any documentation or post about the provisioning service being down or discontinued. But all the guides and videos I watch online clearly show the provisioning service working.

**Comment by ExecuteRestart66** [comment]
https://provisioning.sharepointpnp.com/

when I go to this site (which is shown in some install videos) https://www.youtube.com/watch?v=kvtHij0oZjo 

It takes me to some soccer website. That doesnt seem right?

**Comment by ekreddy** [comment]
Seems something changed yesterday. Last week I am able to use look book > add to tenant . It worked no issues. 

Something might be changed on **04/10/2024** because this page : https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/applying-pnp-templates modified on **04/10/2024**

**Comment by PaoloPia** [comment]
Hi,
Thanks for reaching out and for using the look book site. We changed the behavior of the site and now you can manually install site templates following the provided guidance. Thanks.
