### ISSUE TITLE
Missing Config files

### ISSUE THREAD

**Issue by RichardPriddy** [SharePoint/sp-provisioning-service#7]
Having cloned the repository and attempted a build of the SharePointPnP.ProvisioningApp.sln, most of the projects are missing either the App.config or Web.config files.

**Comment by PaoloPia** [comment]
Hi @RichardPriddy,
Thanks for the feedback. Actually, there are model config files in the projects. They are called Web-Model.config for web sites or App.Model.Config for webjobs. You should take them, configure and rename them as the official config files for your solution.

**Comment by SubratoPati** [comment]
Hi @RichardPriddy ,
Were you able to get the solution up and running?
