### ISSUE TITLE
App catalog provision error while installing MLP

### ISSUE THREAD

**Issue by vijay9177** [SharePoint/sp-provisioning-service#70]
@juliemturner 

We are getting the following error message while trying to install MLP in our stage tenant.

in order to provision the template you need to have an App Catalog in your tenant. Please, create one (for instructions you can read this document: https://go.microsoft.com/fwlink/?linkid=2087251), wait up to 30 minutes, and try again. 

![image](https://user-images.githubusercontent.com/55848691/65706644-80895480-e050-11e9-8cf8-9c3c7e509825.png)

We already have App catalog site in our tenant. We are using tenant admin account to install this app .That account has site admin rights on AppCatalog SiteCollection.

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
