### ISSUE TITLE
Deleting a provisioned site. 

### ISSUE THREAD

**Issue by ExecuteRestart66** [SharePoint/sp-provisioning-service#700]
Just wanted to make sure. If I provisioned a site with one of the PNP template files, and now I want to delete it. Is there anything special I need to do? or can I just simply delete the site? 

Or does it create a lot of 'stuff' other than just a site in sharepoint?

**Comment by PaoloPia** [comment]
Hi,
Thanks for reaching out and for using the look book site. You can simply delete the site from your tenant.
