### ISSUE TITLE
Link "Add to your tenant" is broken at lookbook.microsoft.com

### ISSUE THREAD

**Issue by pedrojcmarcos** [SharePoint/sp-provisioning-service#701]
**Describe the issue**
It's not really a bug in the solution itself. The link "add to your tenant" points to a page "Applying PnP Templates to SharePoint Sites".
go to lookbook.micorsoft.com & try to deploy M365LP by clicking on "add to your tenant"

**Expected behavior**
I would expect the form where to name the tenant, site, ...

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action]
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/{Template-ID}]
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant]
- Are you using a Tenant Global Admin account to provision the template: [Yes/No]

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. The automated provisioning has been disabled and you can now follow instructions provided in the document (https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/applying-pnp-templates) referenced by the site. Thanks.
