### ISSUE TITLE
Cannot deploy the school lookbook template anymore

### ISSUE THREAD

**Issue by AlphaLeonR** [SharePoint/sp-provisioning-service#705]
**Describe the issue**
I cannot deploy this image from the https://lookbook.microsoft.com/details/44dc3585-9140-4183-81fc-bdb057f71ac1 .  I used to be able to deploy using the "Add to your tenant" button.  
![image](https://github.com/SharePoint/sp-provisioning-service/assets/171324052/04396070-85fc-4125-a97e-83d454822b60)
This is no longer working, it just takes me to a site that tells you how to apply the lookbook (which includes clicking the "add to your tenant" button!) https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/applying-pnp-templates.
![image](https://github.com/SharePoint/sp-provisioning-service/assets/171324052/6265f895-f86e-4454-a910-6333ae85c869)

**Expected behavior**
I expected the template to start deploying as it has in the past.  It normally asks for the name, url, and email to notify.

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action]
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: [https://lookbook.microsoft.com/details/{Template-ID}]](https://lookbook.microsoft.com/details/44dc3585-9140-4183-81fc-bdb057f71ac1)
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: [Yes/No] Yes

**Additional context**

**Comment by dlamriben** [comment]
I am having the same issue with trying to provision learning pathways

**Comment by PaoloPia** [comment]
Hi,
Thanks for reaching out and for using the look book site. We changed the behaviour of the site and now you can manually install site templates following the provided guidance. Thanks.
